### ISSUE TITLE
OPF cannot construct growing-sized CLA 

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#1360]
It's possible to construct a TP as a fixed, or growing size model

The default is growing size, which is possible to initialize `TP()` (did not check if other methods fail to run later with it).

When I set this in `permutations.py` in swarming, I get:

```
Results from all experiments:
----------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mmm/nupic/nupic-source/scripts/run_swarm.py", line 187, in <module>
    runPermutations(sys.argv[1:])
  File "/home/mmm/nupic/nupic-source/scripts/run_swarm.py", line 181, in runPermutations
    fileArgPath, optionsDict, outputLabel, permWorkDir)
  File "/home/mmm/nupic/nupic-source/nupic/swarming/permutations_runner.py", line 346, in runWithPermutationsScript
    return _runAction(runOptions)
  File "/home/mmm/nupic/nupic-source/nupic/swarming/permutations_runner.py", line 217, in _runAction
    returnValue = _runHyperSearch(runOptions)
  File "/home/mmm/nupic/nupic-source/nupic/swarming/permutations_runner.py", line 160, in _runHyperSearch
    metricsKeys=search.getDiscoveredMetricsKeys())
  File "/home/mmm/nupic/nupic-source/nupic/swarming/permutations_runner.py", line 822, in generateReport
    raise Exception(jobInfo.workerCompletionMsg)
Exception: E10002: Exiting due to receiving too many models failing from exceptions (6 out of 6). 
Model Exception: Exception occurred while running model 77094: OverflowError("in method 'Cells4_setMaxSegmentsPerCell', argument 2 of type 'int'",) (<type 'exceptions.OverflowError'>)
Traceback (most recent call last):
  File "/home/mmm/nupic/nupic-source/nupic/swarming/utils.py", line 430, in runModelGivenBaseAndParams
    (completionReason, completionMsg) = runner.run()
  File "/home/mmm/nupic/nupic-source/nupic/swarming/ModelRunner.py", line 245, in run
    self._model = ModelFactory.create(modelDescription)
  File "/home/mmm/nupic/nupic-source/nupic/frameworks/opf/modelfactory.py", line 80, in create
    return modelClass(**modelConfig['modelParams'])
  File "/home/mmm/nupic/nupic-source/nupic/frameworks/opf/clamodel.py", line 203, in __init__
    clParams, anomalyParams)
  File "/home/mmm/nupic/nupic-source/nupic/frameworks/opf/clamodel.py", line 1180, in __createCLANetwork
    n.initialize()
  File "/home/mmm/nupic/nupic-source/nupic/engine/__init__.py", line 694, in initialize
    engine.Network.initialize(self, *args, **kwargs)
  File "/home/mmm/nupic/nupic-source/nupic/bindings/engine_internal.py", line 1077, in initialize
    return _engine_internal.Network_initialize(self)
  File "/home/mmm/nupic/nupic-source/nupic/regions/TPRegion.py", line 405, in initialize
    **autoArgs)
  File "/home/mmm/nupic/nupic-source/nupic/research/TP10X2.py", line 154, in __init__
    outputType = outputType,
  File "/home/mmm/nupic/nupic-source/nupic/research/TP.py", line 319, in __init__
    self._initEphemerals()
  File "/home/mmm/nupic/nupic-source/nupic/research/TP10X2.py", line 247, in _initEphemerals
    self.cells4.setMaxSegmentsPerCell(self.maxSegmentsPerCell)
  File "/home/mmm/nupic/nupic-source/nupic/bindings/algorithms.py", line 2436, in setMaxSegmentsPerCell
    return _algorithms.Cells4_setMaxSegmentsPerCell(self, *args, **kwargs)
OverflowError: in method 'Cells4_setMaxSegmentsPerCell', argument 2 of type 'int'
```

**Comment by scottpurdy** [comment]
All of the algorithm components are fixed size resources. But this corresponds to the maximum size. They will take up less space initially. But they do have a maximum size. Does that differ from your understanding, @breznak

**Comment by breznak** [comment]
@scottpurdy yes, I think that's what I mean :) 
`maxSegmentsPerCell = 0, ...` aka. "non fixed-sized" = less space initially, segments grow with time as needed && 
max limit is UInt, compared to given limit with fixed-sized.

**Comment by scottpurdy** [comment]
So we have three options:

1. Require the caller to specify the max segments per cell
2. Set a default fixed value for max segments per cell
3. Set a default unbounded value for max segments per cell

I don't see a use case for the unbounded option. Perhaps @chetan51 can weigh in on 1 vs 2?

**Comment by chetan51** [comment]
I would prefer setting a default fixed value, and letting the caller override it (like we do with all other parameters). I wouldn't mind having an unbounded value (like 0), but that is not implemented currently.

**Comment by chetan51** [comment]
Actually, unless there's a valid use case for an unbounded model, we shouldn't need to implement it.

**Comment by chetan51** [comment]
This issue is about the old temporal memory (TP.py). We should be using the new temporal memory moving forward, which specifies a default value of max segments per cell, and allows the caller to override it.
