### ISSUE TITLE
Swarming test fails locally - Model not found

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#1662]
One of the integration swarming tests fails, with 'Model not found' error. 

```
AssertionError: Model not found: jobID=1831 AND (paramsHash='@E\xde\x1e\xd7\xe3<\xae1\xf4\x0c\xbc\xd8\x1cyA' OR particleHash='\x98\x10\xd0O:\xf1\xa1\xf1\x8d\x80Yu~\x86y\xcf'); numRowsFound=0
```

Output: 

```
tests/swarming/nupic/swarming/swarming_test.py:2204: MultiNodeTests.testOrphanedModelConnection FAILED

=========================================================================================================== FAILURES ============================================================================================================
__________________________________________________________________________________________ MultiNodeTests.testOrphanedModelConnection ___________________________________________________________________________________________
self = <tests.swarming.nupic.swarming.swarming_test.MultiNodeTests testMethod=testOrphanedModelConnection>

    def testOrphanedModelConnection(self):
      """Test for the correct behavior when a model uses a different connection id
        than what is stored in the db. The correct behavior is for the worker to log
        this as a warning and move on to a new model"""
    
      self._printTestHeader()
    
      # -----------------------------------------------------------------------
      # Trigger "Using connection from another worker" exception inside
      # ModelRunner
      # -----------------------------------------------------------------------
      expDir = os.path.join(g_myEnv.testSrcExpDir, 'dummy_multi_v2')
    
      numModels = 2
    
      env = dict()
      env["NTA_CONF_PROP_nupic_hypersearch_modelOrphanIntervalSecs"] = '1'
    
      (jobID, jobInfo, resultInfos, metricResults, minErrScore) \
      = self.runPermutations(expDir,
                            hsImp='v2',
                            loggingLevel=g_myEnv.options.logLevel,
                            maxModels=numModels,
                            env=env,
                            onCluster=True,
                            waitForCompletion=True,
                            dummyModel={'metricValue':  ['25','50'],
                                        'sleepModelRange': '0, 1:5',
                                        'iterations': 20,
                                        }
                            )
    
      cjDB = ClientJobsDAO.get()
    
      self.assertGreaterEqual(len(resultInfos), numModels,
                       "%d were run. Expecting %s"%(len(resultInfos), numModels+1))
      completionReasons = [x.completionReason for x in resultInfos]
>     self.assertGreaterEqual(completionReasons.count(cjDB.CMPL_REASON_EOF), numModels)
E     AssertionError: 1 not greater than or equal to 2

tests/swarming/nupic/swarming/swarming_test.py:2241: AssertionError
-------------------------------------------------------------------------------------------------------- Captured stdout --------------------------------------------------------------------------------------------------------

CURRENT DIRECTORY: /home/mmm/nupic/nupic-source
###############################################################
Running test: <class 'tests.swarming.nupic.swarming.swarming_test.MultiNodeTests'>.testOrphanedModelConnection...

==================================================================
Running Hypersearch job on cluster
==================================================================
2014-12-27 19:55:14,867 - com.numenta.nupic.database.Connection.ConnectionFactory(20713) - INFO - Creating db connection policy via provider <bound method type._createDefaultPolicy of <class 'nupic.database.Connection.ConnectionFactory'>>
2014-12-27 19:55:14,882 - com.numenta.nupic.database.Connection.PooledConnectionPolicy(20713) - INFO - Created PooledConnectionPolicy
2014-12-27 19:55:14,901 - com.numenta.nupic.database.ClientJobsDAO.ClientJobsDAO(20713) - INFO - clientJobsConnectionID=148
2014-12-27 19:55:15,124 - com.numenta.nupic.database.ClientJobsDAO.ClientJobsDAO(20713) - INFO - jobInsert: returning jobID=1831. jobType='hypersearch'; client='test'; clientInfo=''; clientKey=''; jobHash='\xe4\x91\xc5B\x8d\xf9\x11\xe4\xbbd\x90+4Y\xcd\xcc'; cmdLine='export NTA_CONF_PROP_nupic_hypersearch_modelOrphanIntervalSecs=1;export NTA_DATA_PATH=/home/mmm/nupic/nupic-source/tests/swarming/nupic/swarming/data; python -m nupic.swarming.HypersearchWorker --jobID={JOBID} --logLevel=20'
Successfully submitted new test job, jobID=1831
Each of 4 workers executing the command line:  export NTA_CONF_PROP_nupic_hypersearch_modelOrphanIntervalSecs=1;export NTA_DATA_PATH=/home/mmm/nupic/nupic-source/tests/swarming/nupic/swarming/data; python -m nupic.swarming.HypersearchWorker --jobID={JOBID} --logLevel=20

jobStatus          modelsStarted   modelsCompleted modelErrs       modelOrphans   
-------------------------------------------------------------------
# Swarm job now running. jobID=1831
running         1               0               0               0              
running         2               0               0               0              
running         2               1               0               0              
running         2               2               0               1              
completed       2               2               0               1              

<< completed       2               2               0               1              

------------------------------------------------------------------
Hadoop completion reason: success
Worker completion reason: error
Worker completion msg: E10003: Exception occurred in Hypersearch Worker: AssertionError("Model not found: jobID=1831 AND (paramsHash='@E\\xde\\x1e\\xd7\\xe3<\\xae1\\xf4\\x0c\\xbc\\xd8\\x1cyA' OR particleHash='\\x98\\x10\\xd0O:\\xf1\\xa1\\xf1\\x8d\\x80Yu~\\x86y\\xcf'); numRowsFound=0",)
Traceback (most recent call last):
  File "/home/mmm/nupic/nupic-source/nupic/swarming/HypersearchWorker.py", line 551, in main
    jobID = hst.run()
  File "/home/mmm/nupic/nupic-source/nupic/swarming/HypersearchWorker.py", line 358, in run
    jsonModelParams, modelParamsHash, particleHash)
  File "nupic/support/decorators.py", line 59, in exceptionLoggingWrap
    return func(*args, **kwargs)
  File "nupic/database/ClientJobsDAO.py", line 2472, in modelInsertAndStart
    return insertModelWithRetries()
  File "nupic/support/decorators.py", line 214, in retryWrap
    result = func(*args, **kwargs)
  File "nupic/database/ClientJobsDAO.py", line 2467, in insertModelWithRetries
    'numRowsFound=%r') % (jobID, paramsHash, particleHash, numRowsFound)
AssertionError: Model not found: jobID=1831 AND (paramsHash='@E\xde\x1e\xd7\xe3<\xae1\xf4\x0c\xbc\xd8\x1cyA' OR particleHash='\x98\x10\xd0O:\xf1\xa1\xf1\x8d\x80Yu~\x86y\xcf'); numRowsFound=0


Engine worker state:
---------------------------------------------------------------
{u'activeSwarms': [u'modelParams|sensorParams|encoders|consumption'],
 u'blackListedEncoders': [],
 u'lastGoodSprint': None,
 u'lastUpdateTime': 1419706515.646717,
 u'searchOver': False,
 u'sprints': [{u'bestErrScore': None,
               u'bestModelId': None,
               u'status': u'active'}],
 u'swarms': {u'modelParams|sensorParams|encoders|consumption': {u'bestErrScore': None,
                                                                u'bestModelId': None,
                                                                u'sprintIdx': 0,
                                                                u'status': u'active'}}}
Model params for best model: 
{u'particleState': {u'genIdx': 0,
                    u'id': u'150.0',
                    u'swarmId': u'modelParams|sensorParams|encoders|consumption',
                    u'varStates': {u'__model_num': {u'_position': 0.0,
                                                    u'bestPosition': 0,
                                                    u'bestResult': None,
                                                    u'position': 0,
                                                    u'velocity': -1.8},
                                   u'modelParams|sensorParams|encoders|consumption:maxval': {u'_position': 100.0,
                                                                                             u'bestPosition': 100,
                                                                                             u'bestResult': None,
                                                                                             u'position': 100,
                                                                                             u'velocity': -40.0},
                                   u'modelParams|sensorParams|encoders|consumption:n': {u'_position': 500.0,
                                                                                        u'bestPosition': 493,
                                                                                        u'bestResult': None,
                                                                                        u'position': 493,
                                                                                        u'velocity': -97.4},
                                   u'modelParams|tpParams|activationThreshold': {u'_position': 12.0,
                                                                                 u'bestPosition': 12,
                                                                                 u'bestResult': None,
                                                                                 u'position': 12,
                                                                                 u'velocity': -0.8},
                                   u'modelParams|tpParams|minThreshold': {u'_position': 9.0,
                                                                          u'bestPosition': 9,
                                                                          u'bestResult': None,
                                                                          u'position': 9,
                                                                          u'velocity': -0.6}}},
 u'structuredParams': {u'__model_num': 0,
                       u'modelParams': {u'sensorParams': {u'encoders': {u'address': None,
                                                                        u'consumption': {u'fieldname': u'consumption',
                                                                                         u'maxval': 100,
                                                                                         u'minval': 0,
                                                                                         u'n': 493,
                                                                                         u'name': u'consumption',
                                                                                         u'type': u'ScalarEncoder',
                                                                                         u'w': 7},
                                                                        u'gym': None,
                                                                        u'timestamp_dayOfWeek': None,
                                                                        u'timestamp_timeOfDay': None}},
                                        u'tpParams': {u'activationThreshold': 12,
                                                      u'minThreshold': 9}}}}
Best model result: 25.000000
-------------------------------------------------------------------------------------------------------- Captured stderr --------------------------------------------------------------------------------------------------------
Using logging configuration file: /home/mmm/nupic/nupic-source/nupic/support/nupic-logging.conf
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failure
```

**Comment by breznak** [comment]
some glitch, not reproducible anymore...closing.
