### ISSUE TITLE
Swarming fails on "bool" field type

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#1775]
Swarming [docs about field types](https://github.com/numenta/nupic/wiki/NuPIC-Input-Data-File-Format#row-2-field-types) show that `bool` is a valid field type. But when I run this input data into a swarm...

```
bit0,bit1,bit2,bit3,bit4,bit5,bit6,bit7,bit8,bit9,bit10
bool,bool,bool,bool,bool,bool,bool,bool,bool,bool,bool
,,,,,,,,,,
1,0,1,1,0,1,1,0,1,0,0
1,0,1,0,0,1,0,0,1,1,0
0,0,1,1,1,1,1,1,1,0,1
1,1,1,0,0,0,0,0,0,0,1
1,0,0,1,0,0,0,0,0,1,1
1,1,1,1,1,0,0,0,1,1,0
1,0,0,0,0,1,0,1,1,0,0
1,1,0,0,1,1,0,1,0,1,1
1,0,1,1,1,0,0,1,0,1,0
0,0,1,0,0,1,1,1,0,1,1
```

I get this error:

```
Traceback (most recent call last):
  File "swarm.py", line 76, in <module>
    swarm(INPUT_FILE)
  File "swarm.py", line 69, in swarm
    modelParams = swarmForBestModelParams(SWARM_DESCRIPTION, name)
  File "swarm.py", line 46, in swarmForBestModelParams
    verbosity=0
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nupic-0.1.1.dev0-py2.7-macosx-10.10-intel.egg/nupic/swarming/permutations_runner.py", line 266, in runWithConfig
    _generateExpFilesFromSwarmDescription(swarmConfig, outDir)
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nupic-0.1.1.dev0-py2.7-macosx-10.10-intel.egg/nupic/swarming/permutations_runner.py", line 197, in _generateExpFilesFromSwarmDescription
    "--outDir=%s" % (outDir)])
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nupic-0.1.1.dev0-py2.7-macosx-10.10-intel.egg/nupic/frameworks/opf/exp_generator/ExpGenerator.py", line 2027, in expGenerator
    claDescriptionTemplateFile = options.claDescriptionTemplateFile)
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nupic-0.1.1.dev0-py2.7-macosx-10.10-intel.egg/nupic/frameworks/opf/exp_generator/ExpGenerator.py", line 191, in _handleDescriptionOption
    claDescriptionTemplateFile = claDescriptionTemplateFile)
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nupic-0.1.1.dev0-py2.7-macosx-10.10-intel.egg/nupic/frameworks/opf/exp_generator/ExpGenerator.py", line 1199, in _generateExperiment
    _generateEncoderStringsV2(includedFields, options)
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nupic-0.1.1.dev0-py2.7-macosx-10.10-intel.egg/nupic/frameworks/opf/exp_generator/ExpGenerator.py", line 914, in _generateEncoderStringsV2
    raise RuntimeError("Unsupported field type '%s'" % (fieldType))
RuntimeError: Unsupported field type 'bool'
```

Looking at the code in `ExpGenerator.py`, it does not look like the `bool` data type is actually supported. 

Possible solutions:
- Update docs and remove the `bool` type or specify that it can only be used for boolean flags.
- Update swarming code to handle `bool` type.

**Comment by munnybearz** [comment]
I just ran into this. 

I'm pretty new to Nupic so might be talking gibberish.. I changed the datatype to String and it's swarming now. I guess another way if you had 1's and 0's is change the datatype to int and flag that column as C to make nupic use a category encoder.

Matt is this an appropriate workaround?

**Comment by rhyolight** [comment]
Yes, changing to string is a decent workaround. You'll probably want to change the 0s and 1s to "True"/"False" like this:

```
bit_0,bit_1,bit_2,bit_3,bit_4,bit_5,bit_6,bit_7,bit_8,bit_9,bit_10,bit_11,bit_12,bit_13,bit_14,bit_15,bit_16,bit_17,bit_18,bit_19,bit_20
string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string,string
,,,,,,,,,,,,,,,,,,,,
True,True,False,False,True,False,True,True,True,False,True,True,False,True,False,False,True,True,True,False,True
False,False,True,True,True,False,True,False,False,False,True,False,False,True,True,True,True,False,False,False,True
```

**Comment by priyankyadav31** [comment]
Or instead, if I change the datatype to int instead of bool , will It give the correct value

**Comment by rhyolight** [comment]
> Or instead, if I change the datatype to int instead of bool , will It give the correct value

I think using a category would be better, because introducing integers increases the number of parameters the swarm permutes over.

**Comment by priyankyadav31** [comment]
**It is showing me attribution error in both cases 1) datatype: string, special flag: C
                                                                            2) datatype: int , special flag: C**

-------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "swarm.py", line 112, in <module>
    swarm(INPUT_FILE)
  File "swarm.py", line 104, in swarm
    modelParams = swarmForBestModelParams(SWARM_DESCRIPTION, name)
  File "swarm.py", line 78, in swarmForBestModelParams
    verbosity=0
  File "C:\Users\priyank02.TRN\AppData\Local\Continuum\Anaconda2\lib\site-packag
es\nupic\swarming\permutations_runner.py", line 277, in runWithConfig
    return _runAction(runOptions)
  File "C:\Users\priyank02.TRN\AppData\Local\Continuum\Anaconda2\lib\site-packag
es\nupic\swarming\permutations_runner.py", line 218, in _runAction
    returnValue = _runHyperSearch(runOptions)
  File "C:\Users\priyank02.TRN\AppData\Local\Continuum\Anaconda2\lib\site-packag
es\nupic\swarming\permutations_runner.py", line 161, in _runHyperSearch
    metricsKeys=search.getDiscoveredMetricsKeys())
  File "C:\Users\priyank02.TRN\AppData\Local\Continuum\Anaconda2\lib\site-packag
es\nupic\swarming\permutations_runner.py", line 825, in generateReport
    raise Exception(jobInfo.workerCompletionMsg)
Exception: E10002: Exiting due to receiving too many models failing from excepti
ons (6 out of 6).
Model Exception: Exception occurred while running model 20096: AssertionError()
(<type 'exceptions.AssertionError'>)
Traceback (most recent call last):
  File "C:\Users\priyank02.TRN\AppData\Local\Continuum\Anaconda2\lib\site-packag
es\nupic\swarming\hypersearch\utils.py", line 435, in runModelGivenBaseAndParams

    (completionReason, completionMsg) = runner.run()
  File "C:\Users\priyank02.TRN\AppData\Local\Continuum\Anaconda2\lib\site-packag
es\nupic\swarming\ModelRunner.py", line 236, in run
    maxTimeout=readTimeout)
  File "C:\Users\priyank02.TRN\AppData\Local\Continuum\Anaconda2\lib\site-packag
es\nupic\data\stream_reader.py", line 201, in __init__
    bookmark, firstRecordIdx)
  File "C:\Users\priyank02.TRN\AppData\Local\Continuum\Anaconda2\lib\site-packag
es\nupic\data\stream_reader.py", line 297, in _openStream
    firstRecord=firstRecordIdx)
  File "C:\Users\priyank02.TRN\AppData\Local\Continuum\Anaconda2\lib\site-packag
es\nupic\data\file_record_stream.py", line 231, in __init__
    assert types[self._resetIdx] == FieldMetaType.integer
AssertionError

**Comment by priyankyadav31** [comment]
**I am getting following error while using C (category encoder)as special flag in both cases:
1) datatype: string , special flag: C
2) datatype: int , special flag: C**
----------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "swarm.py", line 112, in <module>
    swarm(INPUT_FILE)
  File "swarm.py", line 104, in swarm
    modelParams = swarmForBestModelParams(SWARM_DESCRIPTION, name)
  File "swarm.py", line 78, in swarmForBestModelParams
    verbosity=0
  File "C:\Users\priyank02.TRN\AppData\Local\Continuum\Anaconda2\lib\site-packag
es\nupic\swarming\permutations_runner.py", line 277, in runWithConfig
    return _runAction(runOptions)
  File "C:\Users\priyank02.TRN\AppData\Local\Continuum\Anaconda2\lib\site-packag
es\nupic\swarming\permutations_runner.py", line 218, in _runAction
    returnValue = _runHyperSearch(runOptions)
  File "C:\Users\priyank02.TRN\AppData\Local\Continuum\Anaconda2\lib\site-packag
es\nupic\swarming\permutations_runner.py", line 161, in _runHyperSearch
    metricsKeys=search.getDiscoveredMetricsKeys())
  File "C:\Users\priyank02.TRN\AppData\Local\Continuum\Anaconda2\lib\site-packag
es\nupic\swarming\permutations_runner.py", line 825, in generateReport
    raise Exception(jobInfo.workerCompletionMsg)
Exception: E10002: Exiting due to receiving too many models failing from excepti
ons (6 out of 6).
Model Exception: Exception occurred while running model 20867: AssertionError()
(<type 'exceptions.AssertionError'>)
Traceback (most recent call last):
  File "C:\Users\priyank02.TRN\AppData\Local\Continuum\Anaconda2\lib\site-packag
es\nupic\swarming\hypersearch\utils.py", line 435, in runModelGivenBaseAndParams

    (completionReason, completionMsg) = runner.run()
  File "C:\Users\priyank02.TRN\AppData\Local\Continuum\Anaconda2\lib\site-packag
es\nupic\swarming\ModelRunner.py", line 236, in run
    maxTimeout=readTimeout)
  File "C:\Users\priyank02.TRN\AppData\Local\Continuum\Anaconda2\lib\site-packag
es\nupic\data\stream_reader.py", line 201, in __init__
    bookmark, firstRecordIdx)
  File "C:\Users\priyank02.TRN\AppData\Local\Continuum\Anaconda2\lib\site-packag
es\nupic\data\stream_reader.py", line 297, in _openStream
    firstRecord=firstRecordIdx)
  File "C:\Users\priyank02.TRN\AppData\Local\Continuum\Anaconda2\lib\site-packag
es\nupic\data\file_record_stream.py", line 231, in __init__
    assert types[self._resetIdx] == FieldMetaType.integer
AssertionError

**Comment by rhyolight** [comment]
@priyankyadav31 I don't think your error has anything to do with this issue. You can ask for help on the [NuPIC Forum](https://discourse.numenta.org/c/nupic).
