### ISSUE TITLE
Unable to find library '.../nupic/libcpp_region.so’ [OS X 10.10 Binary Installation]

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#1804]
This report is from a brand new OS X 10.10 installation. Here are the only steps I took to prepare to install NuPIC:

- installed brew
- installed xcode command line tools
- `brew install git`
- `sudo easy_install pip`

Python version: system python 2.7.6 (**not** homebrew python)

## Binary Installation

    pip install nupic —user

This worked with no errors.

### Testing Binary Installation

- downloaded nupic source from github
- attempted to run simple hotgym example 

I downloaded nupic source from github and attempted to run simple hotgym example with error:

```
C02GW171DV7NMBP:nupic-master numenta$ python examples/opf/clients/hotgym/simple/hotgym.py
ERROR:  Unable to find library '/Users/numenta/Desktop/nupic-master/nupic/libcpp_region.so' [/Users/travis/build/numenta/nupic.core/src/nupic/engine/RegionImplFactory.cpp line 84]
Traceback (most recent call last):
  File "examples/opf/clients/hotgym/simple/hotgym.py", line 94, in <module>
    runHotgym()
  File "examples/opf/clients/hotgym/simple/hotgym.py", line 65, in runHotgym
    model = createModel()
  File "examples/opf/clients/hotgym/simple/hotgym.py", line 60, in createModel
    return ModelFactory.create(model_params.MODEL_PARAMS)
  File "/Users/numenta/Library/Python/2.7/lib/python/site-packages/nupic/frameworks/opf/modelfactory.py", line 80, in create
    return modelClass(**modelConfig['modelParams'])
  File "/Users/numenta/Library/Python/2.7/lib/python/site-packages/nupic/frameworks/opf/clamodel.py", line 198, in __init__
    clParams, anomalyParams)
  File "/Users/numenta/Library/Python/2.7/lib/python/site-packages/nupic/frameworks/opf/clamodel.py", line 1031, in __createCLANetwork
    n.addRegion("sensor", "py.RecordSensor", json.dumps(dict(verbosity=sensorParams['verbosity'])))
  File "/Users/numenta/Library/Python/2.7/lib/python/site-packages/nupic/engine/__init__.py", line 636, in addRegion
    engine.Network.addRegion(self, name, nodeType, nodeParams)
  File "/Users/numenta/Library/Python/2.7/lib/python/site-packages/nupic/bindings/engine_internal.py", line 1086, in addRegion
    return _engine_internal.Network_addRegion(self, *args, **kwargs)
RuntimeError: Unable to find library '/Users/numenta/Desktop/nupic-master/nupic/libcpp_region.so’
```

**Comment by rhyolight** [comment]
Working since `nupic-0.2.0`.
