### ISSUE TITLE
Unable to locate hot gym data file [OS X & Linux Binary Installation]

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#1805]
This report is from a brand new OS X 10.10 installation. Here are the only steps I took to prepare to install NuPIC:

- installed brew
- installed xcode command line tools
- `brew install git`
- `sudo easy_install pip`

Python version: system python 2.7.6 (**not** homebrew python)

## Binary Installation

    pip install nupic —user

This worked with no errors.

### Testing Binary Installation

- downloaded nupic source from github
- `export NUPIC=<path to nupic>`
- attempted to run simple hotgym example 

[This error occurs](https://github.com/numenta/nupic/issues/1804) when running from the NuPIC project root using `python examples/opf/clients/hotgym/simple/hotgym.py`. But if I cd into `examples/opf/clients/hotgym/simple/` and run it, I get a different error:

```
C02GW171DV7NMBP:simple numenta$ pwd
/Users/numenta/Desktop/nupic-master/examples/opf/clients/hotgym/simple
C02GW171DV7NMBP:simple numenta$ python hotgym.py
Traceback (most recent call last):
  File "hotgym.py", line 94, in <module>
    runHotgym()
  File "hotgym.py", line 69, in runHotgym
    with open (findDataset(_DATA_PATH)) as fin:
  File "/Users/numenta/Library/Python/2.7/lib/python/site-packages/nupic/data/datasethelpers.py", line 79, in findDataset
    (datasetPath, os.environ.get('NTA_DATA_PATH', '')))
Exception: Unable to locate: extra/hotgym/rec-center-hourly.csv using NTA_DATA_PATH of
```

This error might make sense if the `NUPIC` environment variable was unset, but I set it to the root directory of the NuPIC download from GitHub.

**Comment by rhyolight** [comment]
This error did not occur when using homebrew python.

**Comment by rhyolight** [comment]
Also reported [for Ubuntu](http://lists.numenta.org/pipermail/nupic_lists.numenta.org/2015-February/010371.html).

**Comment by rhyolight** [comment]
The real problem here is that the examples in the NuPIC repo are meant to be run from locally installed source code, against the given file structure of the repository. I think the real solution here would be to create a new repository to contain NuPIC examples.

**Comment by rhyolight** [comment]
Depends on #1899.
