### ISSUE TITLE
IndexError when python audiostream_tp.py

### ISSUE THREAD

**Issue by RDaneelOlivav** [numenta/nupic#1946]
/home/rdaneel/Envs/kodama_NuPIC_env/local/lib/python2.7/site-packages/pkg_resources/__init__.py:1222: UserWarning: /home/rdaneel/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
Number of columns:	512
Max size of input:	51
Sampling rate (Hz):	44100
Passband filter (Hz):	500 - 10000
Passband filter (bin):	46 - 928
Bin difference:		882
Buffersize:		4096
Traceback (most recent call last):
  File "audiostream_tp.py", line 292, in <module>
    audiostream = AudioStream()
  File "audiostream_tp.py", line 211, in __init__
    self.processAudio()
  File "audiostream_tp.py", line 250, in processAudio
    actualInt = self.e.encode(ufs)
  File "/home/rdaneel/Envs/kodama_NuPIC_env/local/lib/python2.7/site-packages/nupic-0.3.0.dev0-py2.7-linux-x86_64.egg/nupic/encoders/base.py", line 138, in encode
    self.encodeIntoArray(inputData, output)
  File "/home/rdaneel/Envs/kodama_NuPIC_env/local/lib/python2.7/site-packages/nupic-0.3.0.dev0-py2.7-linux-x86_64.egg/nupic/encoders/sparse_pass_through_encoder.py", line 54, in encodeIntoArray
    denseInput[input] = 1
IndexError: arrays used as indices must be of integer (or boolean) type

**Comment by rhyolight** [comment]
This example only runs on OS X. From your console output, it looks like you're running on Linux. I've submitted a PR to update the README to specify this requirement.

**Comment by RDaneelOlivav** [comment]
Ok, so there isn't any way of useing self.e.encode(ufs) ( indirectly SparsePassThroughEncoder ) ?
Is this function for somereason not working in Linux? Why exactly? Could it be made the same thing as in audiostream_tp encoding the fft's :+1: 

ys = self.fft(self.audio, self.highpass, self.lowpass)
    fs = numpy.sort(ys.argsort()[-self.numInput:])
    rfs = fs.astype(numpy.float32) / (self.lowpass - self.highpass) * self.numCols
    ufs = numpy.unique(rfs)
    actualInt = self.e.encode(ufs)
    actual = actualInt.astype(numpy.float32)

  but in LinuxEncoding friendly Nupic Encoders? Because it seems really convenient this SparsePassThroughEncoder.

**Comment by rhyolight** [comment]
The problem isn't in nupic, I think. The only OS X specific code has to do with how the audio from the computer is captured and processed. 

Hey @macrintr! Can you confirm this? (he wrote the example)

**Comment by RDaneelOlivav** [comment]
So any progress in this matter? Because I just don't understand why a the
error occurs. I tried turning the input into a list, or integers or
booleans, but thats not what it's supposed to work. Has the creator of the
example have any idea of why it could be happening?

2015-03-25 21:58 GMT+01:00 Matthew Taylor <notifications@github.com>:

**Comment by rhyolight** [comment]
@breznak Let's use this as the main issue to get this example working on linux.

**Comment by breznak** [comment]
:+1: thanks

**Comment by rhyolight** [comment]
I would still love to hear from @macrintr...

**Comment by macrintr** [comment]
@RDaneelOlivav & @rhyolight: I'm not active on this project anymore, but happy to offer my web searching expertise. 

Seems like the top of those error messages is an issue between PyAudio and Ubuntu that can be fixed per [StackOverflow](http://stackoverflow.com/questions/15182336/pyaudio-does-not-work-and-bricks-sound-on-ubuntu). 

And the bottom of those errors seem to indicate that the 'ufs' variable on line 252 needs to be cast as an int type (i.e. `ufs = numpy.unique(rfs).astype(numpy.int32)`). Play around with that. I'm guessing that the encoder input requirements changed when @scottpurdy updated the BitMapArrayEncoder to SparsePassThroughEncoder ([b418e7cae18af32b135915117414327020cbbe1c](https://github.com/numenta/nupic/commit/b418e7cae18af32b135915117414327020cbbe1c)).

**Comment by RDaneelOlivav** [comment]
I'm trying to bypass it by encoding it one by one, because it seems that
the self.e.encode() doesnt allow more than one element .
I hacreated this function , but its still in work process. I just wanna
know it this is the right track, in interpretation of tha data I mean.

def create_encoding_for_fft_max_freq_list(self, max_index_list):
  """
  Takes a list of the maximum frequency indexes and encodes one by one
and after it adds them up
  :return: encoded_freq_array
  """
  actual_int_list = []

  for index in max_index_list:
      actual_int_list.append(self.e.encode(index))

  map(sum, zip(*actual_int_list))
  return actual_int_list


And arround the line 249, when encode the fft's

rfs = fs.astype(numpy.float32) / (self.lowpass - self.highpass) * self.numCols
ufs = numpy.unique(rfs).astype(numpy.int32).tolist()
*actualInt = self.create_encoding_for_fft_max_freq_list(ufs)*

actual = actualInt.astype(numpy.float32)
actual = numpy.asarray(actual)


I'm getting this error for the moment, sure I got something missing ,
did it really fast ;)

Traceback (most recent call last):

File "audiostream_tp.py", line 323, in <module> audiostream = AudioStream()
File "audiostream_tp.py", line 214, in __init__ self.processAudio() File
"audiostream_tp.py", line 262, in processAudio actual =
actualInt.astype(numpy.float32) AttributeError: 'list' object has no
attribute 'astype'



2015-03-27 4:06 GMT+01:00 Thomas Macrina <notifications@github.com>:

**Comment by scottpurdy** [comment]
@RDaneelOlivav - Looks like you are getting numpy arrays and lists mixed up. The most recent traceback is the result of calling `.astype()` on a Python list rather than a numpy.array. If you need it to be an array, you can do `actualIntArray = numpy.array(actualInt, dtype=numpy.float32)`

**Comment by jdiligence** [comment]
I am getting what seems to be this same issue and am using OSX. 

monster:audiostream john$ python audiostream_tp.py 
Number of columns:	512
Max size of input:	51
Sampling rate (Hz):	44100
Passband filter (Hz):	500 - 10000
Passband filter (bin):	46 - 928
Bin difference:		882
Buffersize:		4096
Traceback (most recent call last):
  File "audiostream_tp.py", line 297, in <module>
    audiostream = AudioStream()
  File "audiostream_tp.py", line 214, in __init__
    self.processAudio()
  File "audiostream_tp.py", line 253, in processAudio
    actualInt = self.e.encode(ufs)
  File "/Library/Python/2.7/site-packages/nupic-0.3.0.dev0-py2.7-macosx-10.10-intel.egg/nupic/encoders/base.py", line 133, in encode
    self.encodeIntoArray(inputData, output)
  File "/Library/Python/2.7/site-packages/nupic-0.3.0.dev0-py2.7-macosx-10.10-intel.egg/nupic/encoders/sparse_pass_through_encoder.py", line 54, in encodeIntoArray
    denseInput[input] = 1
IndexError: arrays used as indices must be of integer (or boolean) type

**Comment by RDaneelOlivav** [comment]
I launch this question: How would be the best way / most efficient to
encode now audio based on doing the Fast Fourier just like the audiostream
does that works on the current versions of Nupic? I'll be working on it in
a few weeks but it would be great to have some ideas from the community
because I'm more of a Nupic newbie and knowing the opinion of the veterans
would undoubtly help to build a better sound generic encoder ;).

2015-04-22 16:24 GMT+02:00 John Baker <notifications@github.com>:

**Comment by breznak** [comment]
Hi @RDaneelOlivav , 
you definitely should get in touch with https://github.com/nupic-community/nupic.audio

**Comment by RDaneelOlivav** [comment]
Wow, thanks breznak ! ;) I will sure dive into this ;)

2015-04-23 10:15 GMT+02:00 breznak <notifications@github.com>:

**Comment by siavashr** [comment]
I'm on OSX 10.10.3 and I'm getting this error also.

siavash$ python audiostream_tp.py
Number of columns:	512
Max size of input:	51
Sampling rate (Hz):	44100
Passband filter (Hz):	500 - 10000
Passband filter (bin):	46 - 928
Bin difference:		882
Buffersize:		4096
Traceback (most recent call last):
  File "audiostream_tp.py", line 297, in <module>
    audiostream = AudioStream()
  File "audiostream_tp.py", line 214, in __init__
    self.processAudio()
  File "audiostream_tp.py", line 253, in processAudio
    actualInt = self.e.encode(ufs)
  File "/Library/Python/2.7/site-packages/nupic/encoders/base.py", line 138, in encode
    self.encodeIntoArray(inputData, output)
  File "/Library/Python/2.7/site-packages/nupic/encoders/sparse_pass_through_encoder.py", line 54, in encodeIntoArray
    denseInput[input] = 1
IndexError: arrays used as indices must be of integer (or boolean) type

**Comment by gazhayes** [comment]
Same error on 10.10.2
