### ISSUE TITLE
Obtuse build error if nupic.core is not installed

### ISSUE THREAD

**Issue by subutai** [numenta/nupic#2052]
If you don't install nupic.core properly and try to build NuPIC, you get the following obtuse error. For example:
```
[nupic] > ARCHFLAGS="-arch x86_64" python setup.py develop --nupic-core-dir="/Users/Subutai/nta/nupic.core/build/release" --prefix=/Users/Subutai/local
Using nupic.core binaries at /Users/Subutai/nta/nupic.core/build/release
Traceback (most recent call last):
  File "setup.py", line 651, in <module>
    nupicCoreReleaseDir = prepareNupicCore(options, platform, bitness)
  File "setup.py", line 606, in prepareNupicCore
    protoSourceDir = glob.glob(os.path.join(nupicCoreReleaseDir, "include/nupic/proto/"))[0]
IndexError: list index out of range
```

It would be much nicer if it just said "NuPIC core is not installed. Please see xyz" or something to that effect.

**Comment by vitaly-krugl** [comment]
Even through we build nupic.core, we actually install nupic.bindings. @subutai, should the error messages reference "nupic.bindings" or "nupic.core"?

**Comment by subutai** [comment]
@vitaly-krugl It would be most helpful to mention both. The user might not have downloaded nupic.core at all, or they could have just built nupic.core without installing the bindings. Maybe something that says "Unable to access nupic.bindings. NuPIC depends on Python bindings to C++ code in the nupic.core repository. Please be sure to download nupic.core, build nupic.core, and install nupic.bindings."

**Comment by rhyolight** [comment]
I think the error reported in the original issue may not be the same error that happens anymore, but this issue is still value. The NuPIC installation process should immediately check to see that the correct version of nupic.bindings is in place and fail fast of not.
