### ISSUE TITLE
One hotgym swarm.py results in KjException

### ISSUE THREAD

**Issue by scottpurdy** [numenta/nupic#2070]
I just reinstalled with latest nupic.core and nupic. Here is the terminal output:

```
$ python examples/opf/clients/hotgym/prediction/one_gym/swarm.py
This script runs a swarm on the input data (rec-center-hourly.csv) and
creates a model parameters file in the `model_params` directory containing
the best model found by the swarm. Dumps a bunch of crud to stdout because
that is just what swarming does at this point. You really don't need to
pay any attention to it.

=================================================
= Swarming on rec-center-hourly data...
= Medium swarm. Sit back and relax, this could take awhile.
=================================================
Generating experiment files in directory: /Users/spurdy/nta/nupic/swarm...
Writing  313 lines...
Writing  113 lines...
done.
None
Successfully submitted new HyperSearch job, jobID=1103
Evaluated 0 models
HyperSearch finished!
Worker completion message: E10003: Exception occurred in Hypersearch Worker: KjException()
Traceback (most recent call last):
  File "/Users/spurdy/nta/nupic/nupic/swarming/HypersearchWorker.py", line 551, in main
    jobID = hst.run()
  File "/Users/spurdy/nta/nupic/nupic/swarming/HypersearchWorker.py", line 312, in run
    cjDAO=cjDAO, jobID=options.jobID, logLevel=options.logLevel)
  File "nupic/swarming/HypersearchV2.py", line 2577, in __init__
    modelDescription, _ = opfhelpers.loadExperiment(self._basePath)
  File "nupic/frameworks/opf/opfhelpers.py", line 46, in loadExperiment
    descriptionPyModule = loadExperimentDescriptionScriptFromDir(path)
  File "nupic/frameworks/opf/opfhelpers.py", line 60, in loadExperimentDescriptionScriptFromDir
    module = _loadDescriptionFile(descriptionScriptPath)
  File "nupic/frameworks/opf/opfhelpers.py", line 92, in _loadDescriptionFile
    descriptionPyPath)
  File "/var/folders/wh/wvw3wp_946j4rk609p3qdmxh0000gn/T/tmpmoGBKC/description.py", line 37, in <module>
  File "nupic/frameworks/opf/clamodelcallbacks.py", line 29, in <module>
    from clamodel import CLAModel
  File "nupic/frameworks/opf/clamodel.py", line 44, in <module>
    from nupic.encoders import MultiEncoder, DeltaEncoder
  File "nupic/encoders/__init__.py", line 34, in <module>
    from multi import MultiEncoder
  File "nupic/encoders/multi.py", line 40, in <module>
    from nupic.encoders.scalar_capnp import ScalarEncoderProto
  File "capnp/lib/capnp.pyx", line 3773, in capnp.lib.capnp._Loader.load_module (capnp/lib/capnp.cpp:71749)
    module = load(self.path, fullname, imports=imports)
  File "capnp/lib/capnp.pyx", line 3752, in capnp.lib.capnp.load (capnp/lib/capnp.cpp:71239)
    return _global_schema_parser.load(file_name, display_name, imports)
  File "capnp/lib/capnp.pyx", line 3126, in capnp.lib.capnp.SchemaParser.load (capnp/lib/capnp.cpp:63334)
    fileSchema = parser._parse_disk_file(display_name, file_name, imports)
KjException: /Users/spurdy/nta/nupic/nupic/encoders/scalar.capnp:0: failed: Duplicate ID @0xfa7d16f86048a6e4.
stack: 0x104ba5bb7 0x1049a80b0 0x1049a82d7 0x10499a5fe 0x10499a2db 0x10499ea67 0x1049a07e1 0x1049a100d 0x1049a5b2b 0x1049a5a8d 0x10481f397 0x104849095 0x104831048 0x10482fd39 0x101dc52ac 0x101dd00cf


Results from all experiments:
----------------------------------------------------------------
Generating experiment files in directory: /var/folders/wh/wvw3wp_946j4rk609p3qdmxh0000gn/T/tmpBdkIZD...
Writing  313 lines...
Writing  113 lines...
done.
None
Traceback (most recent call last):
  File "examples/opf/clients/hotgym/prediction/one_gym/swarm.py", line 109, in <module>
    swarm(INPUT_FILE)
  File "examples/opf/clients/hotgym/prediction/one_gym/swarm.py", line 101, in swarm
    modelParams = swarmForBestModelParams(SWARM_DESCRIPTION, name)
  File "examples/opf/clients/hotgym/prediction/one_gym/swarm.py", line 78, in swarmForBestModelParams
    verbosity=0
  File "/Users/spurdy/nta/nupic/nupic/swarming/permutations_runner.py", line 276, in runWithConfig
    return _runAction(runOptions)
  File "/Users/spurdy/nta/nupic/nupic/swarming/permutations_runner.py", line 217, in _runAction
    returnValue = _runHyperSearch(runOptions)
  File "/Users/spurdy/nta/nupic/nupic/swarming/permutations_runner.py", line 160, in _runHyperSearch
    metricsKeys=search.getDiscoveredMetricsKeys())
  File "/Users/spurdy/nta/nupic/nupic/swarming/permutations_runner.py", line 822, in generateReport
    raise Exception(jobInfo.workerCompletionMsg)
Exception: E10003: Exception occurred in Hypersearch Worker: KjException()
Traceback (most recent call last):
  File "/Users/spurdy/nta/nupic/nupic/swarming/HypersearchWorker.py", line 551, in main
    jobID = hst.run()
  File "/Users/spurdy/nta/nupic/nupic/swarming/HypersearchWorker.py", line 312, in run
    cjDAO=cjDAO, jobID=options.jobID, logLevel=options.logLevel)
  File "nupic/swarming/HypersearchV2.py", line 2577, in __init__
    modelDescription, _ = opfhelpers.loadExperiment(self._basePath)
  File "nupic/frameworks/opf/opfhelpers.py", line 46, in loadExperiment
    descriptionPyModule = loadExperimentDescriptionScriptFromDir(path)
  File "nupic/frameworks/opf/opfhelpers.py", line 60, in loadExperimentDescriptionScriptFromDir
    module = _loadDescriptionFile(descriptionScriptPath)
  File "nupic/frameworks/opf/opfhelpers.py", line 92, in _loadDescriptionFile
    descriptionPyPath)
  File "/var/folders/wh/wvw3wp_946j4rk609p3qdmxh0000gn/T/tmpmoGBKC/description.py", line 37, in <module>
  File "nupic/frameworks/opf/clamodelcallbacks.py", line 29, in <module>
    from clamodel import CLAModel
  File "nupic/frameworks/opf/clamodel.py", line 44, in <module>
    from nupic.encoders import MultiEncoder, DeltaEncoder
  File "nupic/encoders/__init__.py", line 34, in <module>
    from multi import MultiEncoder
  File "nupic/encoders/multi.py", line 40, in <module>
    from nupic.encoders.scalar_capnp import ScalarEncoderProto
  File "capnp/lib/capnp.pyx", line 3773, in capnp.lib.capnp._Loader.load_module (capnp/lib/capnp.cpp:71749)
    module = load(self.path, fullname, imports=imports)
  File "capnp/lib/capnp.pyx", line 3752, in capnp.lib.capnp.load (capnp/lib/capnp.cpp:71239)
    return _global_schema_parser.load(file_name, display_name, imports)
  File "capnp/lib/capnp.pyx", line 3126, in capnp.lib.capnp.SchemaParser.load (capnp/lib/capnp.cpp:63334)
    fileSchema = parser._parse_disk_file(display_name, file_name, imports)
KjException: /Users/spurdy/nta/nupic/nupic/encoders/scalar.capnp:0: failed: Duplicate ID @0xfa7d16f86048a6e4.
stack: 0x104ba5bb7 0x1049a80b0 0x1049a82d7 0x10499a5fe 0x10499a2db 0x10499ea67 0x1049a07e1 0x1049a100d 0x1049a5b2b 0x1049a5a8d 0x10481f397 0x104849095 0x104831048 0x10482fd39 0x101dc52ac 0x101dd00cf
```

Pycapnp version:

```
$ pip freeze | grep pycapnp
pycapnp==0.5.5
```

**Comment by scottpurdy** [comment]
@oxtopus - do you get the same error?

**Comment by oxtopus** [comment]
Fails for me, too

**Comment by breznak** [comment]
same as #2067

**Comment by oxtopus** [comment]
@scottpurdy when I change the capnp imports to relative, it doesn't raise the exception, but it does fail for another reason:

```
Traceback (most recent call last):
  File "examples/opf/clients/hotgym/prediction/one_gym/swarm.py", line 109, in <module>
    swarm(INPUT_FILE)
  File "examples/opf/clients/hotgym/prediction/one_gym/swarm.py", line 101, in swarm
    modelParams = swarmForBestModelParams(SWARM_DESCRIPTION, name)
  File "examples/opf/clients/hotgym/prediction/one_gym/swarm.py", line 78, in swarmForBestModelParams
    verbosity=0
  File "/Users/amarshall/nta/nupic/nupic/swarming/permutations_runner.py", line 276, in runWithConfig
    return _runAction(runOptions)
  File "/Users/amarshall/nta/nupic/nupic/swarming/permutations_runner.py", line 217, in _runAction
    returnValue = _runHyperSearch(runOptions)
  File "/Users/amarshall/nta/nupic/nupic/swarming/permutations_runner.py", line 160, in _runHyperSearch
    metricsKeys=search.getDiscoveredMetricsKeys())
  File "/Users/amarshall/nta/nupic/nupic/swarming/permutations_runner.py", line 822, in generateReport
    raise Exception(jobInfo.workerCompletionMsg)
Exception: E10002: Exiting due to receiving too many models failing from exceptions (6 out of 6). 
Model Exception: Exception occurred while running model 1000: IOError(2, 'No such file or directory') (<type 'exceptions.IOError'>)
Traceback (most recent call last):
  File "nupic/swarming/utils.py", line 430, in runModelGivenBaseAndParams
    (completionReason, completionMsg) = runner.run()
  File "nupic/swarming/ModelRunner.py", line 238, in run
    maxTimeout=readTimeout)
  File "nupic/data/stream_reader.py", line 209, in __init__
    self._openStream(dataUrl, isBlocking, maxTimeout, bookmark, firstRecordIdx)
  File "nupic/data/stream_reader.py", line 300, in _openStream
    firstRecord=firstRecordIdx)
  File "nupic/data/file_record_stream.py", line 164, in __init__
    self._file = open(self._filename, self._mode)
IOError: [Errno 2] No such file or directory: u'/Users/amarshall/nta/nupic/rec-center-hourly.csv'
```
