### ISSUE TITLE
NuPIC Installation Issue - No Math Module

### ISSUE THREAD

**Issue by jburman789** [numenta/nupic#2086]
> What did you do? (steps to reproduce)

I downloaded NuPIC from GitHub and followed the installation instructions for Linux (nupic-linux64).

> What happened? (actual result)

python hierarchy_network_demo.py
Traceback (most recent call last):
File "hierarchy_network_demo.py", line 38, in 
from nupic.algorithms.anomaly import computeRawAnomalyScore
File "/home/jerry/MATLAB/R2014b/bin/NuPic/nupic/algorithms/init.py", line 28, in 
from nupic.bindings.math import NearestNeighbor
ImportError: No module named math

> What should have happened? (expected results)

I was trying to run the demos and I continually get the No module named math error.

> Additional Information (operating system, python version, NuPIC commit SHA, etc.)

Python version 2.7.6
Linux Ubuntu 14.04 LTS 64 bit
NuPIC from GitHub

**Comment by breznak** [comment]
Hi,

this seems as a problem in the C++ bindings, did you get any errors during
the pip install?
Or can you try to follow the "manual install" method for nupic.core and
nupic?
I'm running 14.04 here.

Cheers, Mark

**Comment by rhyolight** [comment]
@jburman789 It would be good to see your console output during the installation process. Another think you could have tried is installing from Linux binary as defined in the README:

    pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic/releases/nupic-0.2.1-cp27-none-linux_x86_64.whl

**Comment by jburman789** [comment]
Hi Mark,

Thanks for the feedback … I did not get any errors with the pip install … I will try the manual install … Jerry

**Comment by rhyolight** [comment]
@jburman789 Wait, how did you do the pip install? Did you run `python setup.py install` or are you talking about the pip command I pasted above?

**Comment by jburman789** [comment]
I used python setup.py install

**Comment by rhyolight** [comment]
It would be really useful to see the complete console output of the `python setup.py install` command. Can you put it up on pastebin.com?

**Comment by jburman789** [comment]
I tried the pip install and here is the result (I already have Python 2.7.6 installed - I do not understand the error at the very end):

pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic/releases/nupic-0.2.1-cp27-none-linux_x86_64.whl
Downloading/unpacking https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic/releases/nupic-0.2.1-cp27-none-linux_x86_64.whl
  Downloading nupic-0.2.1-cp27-none-linux_x86_64.whl (22.6MB): 22.6MB downloaded
Downloading/unpacking PyMySQL==0.6.2 (from nupic==0.2.1)
  Downloading PyMySQL-0.6.2.tar.gz (53kB): 53kB downloaded
  Running setup.py egg_info for package PyMySQL
    
Requirement already satisfied (use --upgrade to upgrade): pyproj==1.9.3 in ./jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages (from nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): validictory==0.9.1 in ./jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages (from nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): pytest-cov==1.6 in ./jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages (from nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): mock==1.0.1 in ./jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages (from nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): pytest-xdist==1.8 in ./jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages (from nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): ordereddict==1.1 in ./jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages (from nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): DBUtils==1.1 in ./jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages (from nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): unittest2==0.5.1 in ./jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages (from nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): pillow==2.3.0 in ./jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages (from nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil==2.1 in ./jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages (from nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): pylint==1.1.0 in ./jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages (from nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): coverage==3.7.1 in ./jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages (from nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7.1 in ./jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages (from nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): tweepy==2.1 in ./jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages (from nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): prettytable==0.7.2 in ./jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages (from nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): PyYAML==3.10 in ./jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages (from nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): pytest==2.4.2 in ./jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages (from nupic==0.2.1)
Downloading/unpacking pycapnp==0.5.1 (from nupic==0.2.1)
  Downloading pycapnp-0.5.1.tar.gz (411kB): 411kB downloaded
  Running setup.py egg_info for package pycapnp
    
Requirement already satisfied (use --upgrade to upgrade): asteval==0.9.1 in ./jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages (from nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): psutil==1.0.1 in ./jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages (from nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): cov-core>=1.6 in ./jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages (from pytest-cov==1.6->nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): execnet>=1.0.8 in ./jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages (from pytest-xdist==1.8->nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): six in ./jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages (from python-dateutil==2.1->nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): logilab-common>=0.53.0 in ./jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages (from pylint==1.1.0->nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): astroid>=0.24.3 in ./jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages (from pylint==1.1.0->nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.17 in ./jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages (from pytest==2.4.2->nupic==0.2.1)
Installing collected packages: nupic, PyMySQL, pycapnp
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/home/jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages/pip-1.4.1-py2.7.egg/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "/home/jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages/pip-1.4.1-py2.7.egg/pip/commands/install.py", line 241, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/home/jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages/pip-1.4.1-py2.7.egg/pip/req.py", line 1298, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/home/jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages/pip-1.4.1-py2.7.egg/pip/req.py", line 595, in install
    self.move_wheel_files(self.source_dir)
  File "/home/jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages/pip-1.4.1-py2.7.egg/pip/req.py", line 815, in move_wheel_files
    move_wheel_files(self.name, self.req, wheeldir, user=self.use_user_site, home=self.target_dir)
  File "/home/jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages/pip-1.4.1-py2.7.egg/pip/wheel.py", line 172, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages/pip-1.4.1-py2.7.egg/pip/wheel.py", line 162, in clobber
    os.makedirs(destsubdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/tests'

Storing complete log in /home/jerry/.pip/pip.log

**Comment by jburman789** [comment]
I just posted in on GitHub under #2086

**Comment by breznak** [comment]
> OSError: [Errno 13] Permission denied:
'/usr/local/lib/python2.7/dist-packages/tests'

I think you did not install, either try:
running in python virtualenv
or pip with sudo

**Comment by rhyolight** [comment]
> or pip with sudo

Instead of using sudo, running the command with the `--user` flag. (See https://github.com/numenta/nupic#having-problems)

**Comment by jburman789** [comment]
Ok, I tried your suggestion using pip install --user and it also failed:

pip install --user https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic/releases/nupic-0.2.1-cp27-none-linux_x86_64.whl
Collecting nupic==0.2.1 from https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic/releases/nupic-0.2.1-cp27-none-linux_x86_64.whl
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic/releases/nupic-0.2.1-cp27-none-linux_x86_64.whl
Collecting pytest-cov==1.6 (from nupic==0.2.1)
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached pytest-cov-1.6.tar.gz
Requirement already satisfied (use --upgrade to upgrade): asteval==0.9.1 in ./.local/lib/python2.7/site-packages (from nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7.1 in /usr/lib/python2.7/dist-packages (from nupic==0.2.1)
Collecting unittest2==0.5.1 (from nupic==0.2.1)
  Using cached unittest2-0.5.1.tar.gz
Collecting psutil==1.0.1 (from nupic==0.2.1)
  Using cached psutil-1.0.1.tar.gz
Collecting pytest==2.4.2 (from nupic==0.2.1)
  Using cached pytest-2.4.2.tar.gz
Collecting python-dateutil==2.1 (from nupic==0.2.1)
  Using cached python-dateutil-2.1.tar.gz
Collecting pycapnp==0.5.1 (from nupic==0.2.1)
  Using cached pycapnp-0.5.1.tar.gz
Collecting pytest-xdist==1.8 (from nupic==0.2.1)
  Using cached pytest-xdist-1.8.zip
Collecting pylint==1.1.0 (from nupic==0.2.1)
  Using cached pylint-1.1.0.tar.gz
Collecting pyproj==1.9.3 (from nupic==0.2.1)
  Using cached pyproj-1.9.3.tar.gz
Collecting prettytable==0.7.2 (from nupic==0.2.1)
  Using cached prettytable-0.7.2.tar.bz2
Collecting DBUtils==1.1 (from nupic==0.2.1)
  Using cached DBUtils-1.1.tar.gz
Collecting validictory==0.9.1 (from nupic==0.2.1)
  Using cached validictory-0.9.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pillow==2.3.0 in /usr/lib/python2.7/dist-packages (from nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): ordereddict==1.1 in ./.local/lib/python2.7/site-packages (from nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): PyYAML==3.10 in /usr/lib/python2.7/dist-packages (from nupic==0.2.1)
Collecting PyMySQL==0.6.2 (from nupic==0.2.1)
  Using cached PyMySQL-0.6.2-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): coverage==3.7.1 in ./.local/lib/python2.7/site-packages (from nupic==0.2.1)
Collecting tweepy==2.1 (from nupic==0.2.1)
  Using cached tweepy-2.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): mock==1.0.1 in ./.local/lib/python2.7/site-packages (from nupic==0.2.1)
Collecting cov-core>=1.6 (from pytest-cov==1.6->nupic==0.2.1)
  Using cached cov-core-1.15.0.tar.gz
Collecting py>=1.4.17 (from pytest==2.4.2->nupic==0.2.1)
  Using cached py-1.4.26.tar.gz
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from python-dateutil==2.1->nupic==0.2.1)
Collecting execnet>=1.0.8 (from pytest-xdist==1.8->nupic==0.2.1)
  Using cached execnet-1.3.0-py2.py3-none-any.whl
Collecting logilab-common>=0.53.0 (from pylint==1.1.0->nupic==0.2.1)
  Using cached logilab-common-0.63.2.tar.gz
Collecting astroid>=0.24.3 (from pylint==1.1.0->nupic==0.2.1)
  Using cached astroid-1.3.6-py2.py3-none-any.whl
Installing collected packages: py, pytest, cov-core, pytest-cov, unittest2, psutil, python-dateutil, pycapnp, execnet, pytest-xdist, logilab-common, astroid, pylint, pyproj, prettytable, DBUtils, validictory, PyMySQL, tweepy, nupic
  Running setup.py install for py
  Running setup.py install for pytest
  Running setup.py install for cov-core
  Running setup.py install for pytest-cov
  Running setup.py install for unittest2
  Running setup.py install for psutil
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-o3gNp5/psutil/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-pubKHY-record/install-record.txt --single-version-externally-managed --compile --user:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psmswindows.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psposix.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/error.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psosx.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_pslinux.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_common.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_error.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_pssunos.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psbsd.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/__init__.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_compat.py -> build/lib.linux-x86_64-2.7/psutil
    running build_ext
    building '_psutil_linux' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/psutil
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c psutil/_psutil_linux.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_linux.o
    psutil/_psutil_linux.c:10:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
    Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-o3gNp5/psutil/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-pubKHY-record/install-record.txt --single-version-externally-managed --compile --user" failed with error code 1 in /tmp/pip-build-o3gNp5/psutil

  File "/home/jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages/pip-1.4.1-py2.7.egg/pip/req.py", line 815, in move_wheel_files
    move_wheel_files(self.name, self.req, wheeldir, user=self.use_user_site, home=self.target_dir)
  File "/home/jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages/pip-1.4.1-py2.7.egg/pip/wheel.py", line 172, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages/pip-1.4.1-py2.7.egg/pip/wheel.py", line 162, in clobber
    os.makedirs(destsubdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/tests'

Storing complete log in /home/jerry/.pip/pip.log

**Comment by jburman789** [comment]
Using sudo with pip also failed ...

**Comment by rhyolight** [comment]
> psutil/_psutil_linux.c:10:20: fatal error: Python.h: No such file or directory

This indicates that you don't have Python development headers installed. https://docs.python.org/devguide/setup.html#build-dependencies

**Comment by rhyolight** [comment]
> File "/home/jerry/NuPIC/nupic-master/nupic-linux64/lib/python2.7/site-packages/pip-1.4.1-py2.7.egg/pip/req.py", line 815, in move_wheel_files

It also looks like you might have a halfway installed version of NuPIC, so I suggest you run `pip uninstall nupic` a few times until you see nothing installed. Then try re-installing the binary.

**Comment by jburman789** [comment]
All right, I installed the Python development headers as you suggested (for Python 2.7) and removed the nupic installation.  I then tried the following and it still fails to properly install using either sudo or --user:

sudo pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic/releases/nupic-0.2.1-cp27-none-linux_x86_64.whl
[sudo] password for jerry: 
The directory '/home/jerry/.cache/pip/log' or its parent directory is not owned by the current user and the debug log has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/jerry/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/jerry/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting nupic==0.2.1 from https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic/releases/nupic-0.2.1-cp27-none-linux_x86_64.whl
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic/releases/nupic-0.2.1-cp27-none-linux_x86_64.whl (22.6MB)
    100% |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 22.6MB 23kB/s 
Requirement already satisfied (use --upgrade to upgrade): pytest-cov==1.6 in ./.local/lib/python2.7/site-packages (from nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): asteval==0.9.1 in ./.local/lib/python2.7/site-packages (from nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7.1 in /usr/lib/python2.7/dist-packages (from nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): unittest2==0.5.1 in ./.local/lib/python2.7/site-packages (from nupic==0.2.1)
Collecting psutil==1.0.1 (from nupic==0.2.1)
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Downloading psutil-1.0.1.tar.gz (156kB)
    100% |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 159kB 2.3MB/s 
Requirement already satisfied (use --upgrade to upgrade): pytest==2.4.2 in ./.local/lib/python2.7/site-packages (from nupic==0.2.1)
Collecting python-dateutil==2.1 (from nupic==0.2.1)
  Downloading python-dateutil-2.1.tar.gz (152kB)
    100% |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 155kB 1.3MB/s 
Collecting pycapnp==0.5.1 (from nupic==0.2.1)
  Downloading pycapnp-0.5.1.tar.gz (411kB)
    100% |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 413kB 990kB/s 
Collecting pytest-xdist==1.8 (from nupic==0.2.1)
  Downloading pytest-xdist-1.8.zip
Collecting pylint==1.1.0 (from nupic==0.2.1)
  Downloading pylint-1.1.0.tar.gz (369kB)
    100% |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 372kB 1.4MB/s 
Collecting pyproj==1.9.3 (from nupic==0.2.1)
  Downloading pyproj-1.9.3.tar.gz (2.7MB)
    100% |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 2.7MB 193kB/s 
Collecting prettytable==0.7.2 (from nupic==0.2.1)
  Downloading prettytable-0.7.2.tar.bz2
Collecting DBUtils==1.1 (from nupic==0.2.1)
  Downloading DBUtils-1.1.tar.gz (109kB)
    100% |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 110kB 4.3MB/s 
Collecting validictory==0.9.1 (from nupic==0.2.1)
  Downloading validictory-0.9.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): pillow==2.3.0 in /usr/lib/python2.7/dist-packages (from nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): ordereddict==1.1 in ./.local/lib/python2.7/site-packages (from nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): PyYAML==3.10 in /usr/lib/python2.7/dist-packages (from nupic==0.2.1)
Collecting PyMySQL==0.6.2 (from nupic==0.2.1)
  Downloading PyMySQL-0.6.2-py2.py3-none-any.whl (63kB)
    100% |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 65kB 4.0MB/s 
Requirement already satisfied (use --upgrade to upgrade): coverage==3.7.1 in ./.local/lib/python2.7/site-packages (from nupic==0.2.1)
Collecting tweepy==2.1 (from nupic==0.2.1)
  Downloading tweepy-2.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): mock==1.0.1 in ./.local/lib/python2.7/site-packages (from nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): cov-core>=1.6 in ./.local/lib/python2.7/site-packages (from pytest-cov==1.6->nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.17 in ./.local/lib/python2.7/site-packages (from pytest==2.4.2->nupic==0.2.1)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from python-dateutil==2.1->nupic==0.2.1)
Collecting execnet>=1.0.8 (from pytest-xdist==1.8->nupic==0.2.1)
  Downloading execnet-1.3.0-py2.py3-none-any.whl
Collecting logilab-common>=0.53.0 (from pylint==1.1.0->nupic==0.2.1)
  Downloading logilab-common-0.63.2.tar.gz (196kB)
    100% |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 200kB 1.6MB/s 
Collecting astroid>=0.24.3 (from pylint==1.1.0->nupic==0.2.1)
  Downloading astroid-1.3.6-py2.py3-none-any.whl (182kB)
    100% |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 184kB 1.5MB/s 
Installing collected packages: psutil, python-dateutil, pycapnp, execnet, pytest-xdist, logilab-common, astroid, pylint, pyproj, prettytable, DBUtils, validictory, PyMySQL, tweepy, nupic
  Running setup.py install for psutil
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-WqoceV/psutil/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-_zXQa6-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psmswindows.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psposix.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/error.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psosx.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_pslinux.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_common.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_error.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_pssunos.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_psbsd.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/__init__.py -> build/lib.linux-x86_64-2.7/psutil
    copying psutil/_compat.py -> build/lib.linux-x86_64-2.7/psutil
    running build_ext
    building '_psutil_linux' extension
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/psutil
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c psutil/_psutil_linux.c -o build/temp.linux-x86_64-2.7/psutil/_psutil_linux.o
    psutil/_psutil_linux.c:10:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
    Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-WqoceV/psutil/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-_zXQa6-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-WqoceV/psutil

**Comment by rhyolight** [comment]
> Python.h: No such file or directory

This still indicates that [Python development headers are not installed](http://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory).
