### ISSUE TITLE
capnp exception from ScalarEncoder

### ISSUE THREAD

**Issue by mj-harvey** [numenta/nupic#2113]
Against commit ec270f3918012304263db557d969c412bb705ea5 (current master HEAD):
After a clean install on a stock Centos 7 system, importing ScalarEncoder fails with a capnp exception:

$ git clone ...
$ python setup.py install
...

$ python
Python 2.7.5 (default, Jun 17 2014, 18:11:42) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> from nupic.encoders import ScalarEncoder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "nupic/encoders/__init__.py", line 34, in <module>
    from multi import MultiEncoder
  File "nupic/encoders/multi.py", line 40, in <module>
    from nupic.encoders.scalar_capnp import ScalarEncoderProto
  File "capnp/lib/capnp.pyx", line 3773, in capnp.lib.capnp._Loader.load_module (capnp/lib/capnp.cpp:71749)
  File "capnp/lib/capnp.pyx", line 3752, in capnp.lib.capnp.load (capnp/lib/capnp.cpp:71239)
  File "capnp/lib/capnp.pyx", line 3126, in capnp.lib.capnp.SchemaParser.load (capnp/lib/capnp.cpp:63334)
capnp.lib.capnp.KjException: /home/mjharvey/working/nupic/nupic/encoders/scalar.capnp:0: failed: Duplicate ID @0xfa7d16f86048a6e4.
stack: 0x7f7285302738 0x7f7285225379 0x7f7285224ec5 0x7f728524aa5a 0x7f728524af92 0x7f728524f386 0x7f728524f47b 0x7f728524f9d9 0x7f728524fa18 0x7f728522430e 0x7f72852243fb 0x7f72851d3748 0x7f72851c343e 0x7f72851a4702 0x7f7285176b3f 0x7f728519cfaa
>>>

**Comment by rhyolight** [comment]
@scottpurdy Does this look familiar? 

    capnp.lib.capnp.KjException: /home/mjharvey/working/nupic/nupic/encoders/scalar.capnp:0: failed: Duplicate ID @0xfa7d16f86048a6e4.

**Comment by mj-harvey** [comment]
Specifically, it happens when python is invoked from the top level directory (where setup.py) resides.  Run from anywhere else, and the import works fine. PYTHONPATH is unset.

**Comment by rhyolight** [comment]
Does this problem prevent you from running examples like this?

    python examples/opf/clients/hotgym/simple/hotgym.py

**Comment by mj-harvey** [comment]
Turns out this only happens when python's run interactively:

```
$ cd $REPO_ROOT
$ echo "from nupic.frameworks.opf.modelfactory import ModelFactory" > foo.py
$ python foo.py && echo $?
0
```

```
$ python
Python 2.7.8 (default, Oct 20 2014, 15:05:19) 
[GCC 4.9.1] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import foo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "foo.py", line 1, in <module>
    from nupic.frameworks.opf.modelfactory import ModelFactory
  File "nupic/frameworks/opf/modelfactory.py", line 32, in <module>
    from clamodel import CLAModel
  File "nupic/frameworks/opf/clamodel.py", line 44, in <module>
    from nupic.encoders import MultiEncoder, DeltaEncoder
  File "nupic/encoders/__init__.py", line 34, in <module>
    from multi import MultiEncoder
  File "nupic/encoders/multi.py", line 40, in <module>
    from nupic.encoders.scalar_capnp import ScalarEncoderProto
  File "capnp/lib/capnp.pyx", line 3773, in capnp.lib.capnp._Loader.load_module (capnp/lib/capnp.cpp:71749)
  File "capnp/lib/capnp.pyx", line 3752, in capnp.lib.capnp.load (capnp/lib/capnp.cpp:71239)
  File "capnp/lib/capnp.pyx", line 3126, in capnp.lib.capnp.SchemaParser.load (capnp/lib/capnp.cpp:63334)
capnp.lib.capnp.KjException: /home/mjharvey/working/nupic/nupic/encoders/scalar.capnp:0: failed: Duplicate ID @0xfa7d16f86048a6e4.
stack: 0x7fd326fbdd48 0x7fd326edfbb9 0x7fd326edf705 0x7fd326f056fa 0x7fd326f05c32 0x7fd326f0a026 0x7fd326f0a11b 0x7fd326f0a679 0x7fd326f0a6b8 0x7fd326edeb2e 0x7fd326edec1b 0x7fd326e9043b 0x7fd326e7e024 0x7fd326e63cc2 0x7fd326e2cc7f 0x7fd326e6490c
>>> 


Looking at a strace -e open  of the two, the only difference I can see is that the interactive instance uses relative paths whereas, non-interactively, they are absolute. The same packages seem to be used in either case.

**Comment by rcrowder** [comment]
That looks similar to a pycapnp current issue that Brez and Scott are investigating;  https://github.com/jparyani/pycapnp/issues/62

**Comment by breznak** [comment]
Sorry to hijack the thread, 

```
============================================================================================================ ERRORS =============================================================================================================
___________________________________________________________________________________ ERROR collecting tests/unit/nupic/encoders/multi_test.py ____________________________________________________________________________________
tests/unit/nupic/encoders/multi_test.py:33: in <module>
    from nupic.encoders.multi_capnp import MultiEncoderProto
capnp/lib/capnp.pyx:3612: in capnp.lib.capnp._Loader.load_module (capnp/lib/capnp.cpp:68827)
    ???
capnp/lib/capnp.pyx:3591: in capnp.lib.capnp.load (capnp/lib/capnp.cpp:68317)
    ???
capnp/lib/capnp.pyx:3055: in capnp.lib.capnp.SchemaParser.load (capnp/lib/capnp.cpp:62181)
    ???
E   RuntimeError: std::bad_alloc

```

Is this similar kind of problem, or a new one? 
Btw, @scottpurdy is there a workaround? ..this is kindof a blocker :no_entry_sign:

**Comment by david-ragazzi** [comment]
I had this same problem. Then I realized that I duplicate a `struct` twice in a `.capnp` file. hehe
