### ISSUE TITLE
Some UnitTests get stuck on serialization

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#2148]
running `./scripts/run_nupic_tests -u` gets stuck on SOME capnp serialization tests, but others capnp tests seem to work! 

A workaround skipping the problematic tests can be found at https://github.com/breznak/nupic/tree/failing_serialization_tests 

```
tests/unit/nupic/encoders/pass_through_encoder_test.py:72: PassThroughEncoderTest.testClosenessScores PASSED
tests/unit/nupic/encoders/pass_through_encoder_test.py:48: PassThroughEncoderTest.testEncodeArray PASSED
tests/unit/nupic/encoders/pass_through_encoder_test.py:60: PassThroughEncoderTest.testEncodeBitArray PASSED
tests/unit/nupic/encoders/pass_through_encoder_test.py:125: PassThroughEncoderTest.testReadWrite PASSED

^CTraceback (most recent call last):
  File "./scripts/run_nupic_tests", line 265, in <module>
    result = main(parser, sys.argv[1:])
  File "./scripts/run_nupic_tests", line 255, in main
    exitStatus = call(["py.test"] + args + list(tests))
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 1376, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
(pyenv)mmm@mmm-U2442:~/devel/nupic/nupic-source$ 

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! KeyboardInterrupt !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/usr/local/lib/python2.7/dist-packages/py/_process/forkedfunc.py:82: KeyboardInterrupt
============================================================================================ 217 passed, 8 skipped in 52.24 seconds ===
```

**Comment by breznak** [comment]
@oxtopus any idea why could that be?

**Comment by cogmission** [comment]
![breznak](https://cloud.githubusercontent.com/assets/2340086/7723835/7a7563fc-feb1-11e4-974f-92ed0252fed7.png)

**Comment by breznak** [comment]
:grinning: yep, ima trying to steal Austin's ideas..

**Comment by cogmission** [comment]
😜

**Comment by rhyolight** [comment]
@scottpurdy Do you think this has any similarity to the unit test stall we were having on internal pipelines a couple of weeks ago?

**Comment by breznak** [comment]
I'm still having this problem, so unittests don't complete for me locally, any hints?

**Comment by rhyolight** [comment]
I have no idea what is the problem. @breznak Maybe you can try running the Capnp tests on your local machine? If they also stall sometimes, we'll know this is a capnp problem.

**Comment by breznak** [comment]
> Maybe you can try running the Capnp tests on your local machine? If they also stall sometimes, we'll know this is a capnp problem.  

you mean reinstalling capnp from source and running their unittests?

**Comment by rhyolight** [comment]
Yes, that is what I mean.

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by breznak** [comment]
The traceback here, looks like it's not stuck in the test itself, but the program "run_nupic_tests"? 
```
tests/unit/nupic/encoders/pass_through_encoder_test.py:124: PassThroughEncoderTest.testReadWrite PASSED^CTraceback (most recent call last):
  File "./scripts/run_nupic_tests", line 265, in <module>
    result = main(parser, sys.argv[1:])
  File "./scripts/run_nupic_tests", line 255, in main
    exitStatus = call(["py.test"] + args + list(tests))
  File "/usr/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 1376, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
```

Confirmed, when I run 
```
tests/unit/nupic/encoders/pass_through_encoder_test.py
```
it finishes fine.

**Comment by scottpurdy** [comment]
What version of NuPIC are you using? We saw something similar before that had to do with the version of glibc that capnp in nupic.core was compiled against. This has been fixed for a little while I think (I think NuPIC 0.2.4 fixed it). This was totally independent of the version of capnp installed on your system or used by pycapnp since nupic.core always uses the bundled version.

**Comment by breznak** [comment]
I'm running `master` with nupic.core compiled from source too. `glibc` is
2.19 from Ubuntu 14.04 LTS (=same as Travis!)
Good to know this should not be something with capnp but rather the compile
chain. I can retest with nupic.core from the binary blobs we publish.

**Comment by breznak** [comment]
Almost solved at last! Did what Matt said, rebuilt capnp from the Readme in nupic.core, all its checks pass, rebuilt all nupic and I don't get stuck anymore! :yellow_heart: 
However, the new libs differ from upstream (mine built with clang, not sure if that matters or not): 
```
$ git status 
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   external/linux64/bin/capnp
        modified:   external/linux64/bin/capnpc-c++
        modified:   external/linux64/bin/capnpc-capnp
        modified:   external/linux64/lib/libcapnp-rpc.a
        modified:   external/linux64/lib/libcapnp.a
        modified:   external/linux64/lib/libcapnpc.a
        modified:   external/linux64/lib/libkj-async.a
        modified:   external/linux64/lib/libkj.a

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        bindings/py/nupic.bindings.egg-info/
        bindings/py/src/
        external/capnproto-c++-0.5.2.tar.gz
        external/capnproto-c++-0.5.2/
        external/linux64/lib/libcapnp-rpc.la
        external/linux64/lib/libcapnp.la
        external/linux64/lib/libcapnpc.la
        external/linux64/lib/libkj-async.la
        external/linux64/lib/libkj.la
        external/linux64/lib/pkgconfig/
``` 
What do I do about that now? I don't want to keep out of tree library builds. Or should I send the files to you to verify if that works for all of you ok? 

-----
Also, here is err output from unit tests, some are expected (CoordinateEncoder, Random), the KJExcetion is not! : 
CC https://github.com/numenta/nupic/issues/2471
```
============================================================================================================ ERRORS =============================================================================================================
____________________________________________________________________________ ERROR collecting tests/unit/nupic/research/spatial_pooler_unit_test.py _____________________________________________________________________________
tests/unit/nupic/research/spatial_pooler_unit_test.py:41: in <module>
    from nupic.bindings.proto import SpatialPoolerProto_capnp
capnp/lib/capnp.pyx:3773: in capnp.lib.capnp._Loader.load_module (capnp/lib/capnp.cpp:71749)
    ???
capnp/lib/capnp.pyx:3752: in capnp.lib.capnp.load (capnp/lib/capnp.cpp:71239)
    ???
capnp/lib/capnp.pyx:3126: in capnp.lib.capnp.SchemaParser.load (capnp/lib/capnp.cpp:63334)
    ???
E   KjException: /home/mmm/devel/nupic/nupic.core/bindings/py/nupic/proto/RandomProto.capnp:0: failed: Duplicate ID @0x88eaee6db8e1f67c.
E   stack: 0x7f2513dfcf08 0x7f2513d1c928 0x7f2513d1c530 0x7f2513d47178 0x7f2513d4768a 0x7f2513d4b9b6 0x7f2513d4baab 0x7f2513d4bb5b 0x7f2513d4bba4 0x7f2513d5792a 0x7f2513d56dbe 0x7f2513d5a338 0x7f2513d4406c 0x7f2513d4b93e 0x7f2513d44cee 0x7f2513d44fff
______________________________________________________________________________ ERROR collecting tests/unit/nupic/research/temporal_memory_test.py _______________________________________________________________________________
tests/unit/nupic/research/temporal_memory_test.py:32: in <module>
    from nupic.bindings.proto import TemporalMemoryProto_capnp
capnp/lib/capnp.pyx:3773: in capnp.lib.capnp._Loader.load_module (capnp/lib/capnp.cpp:71749)
    ???
capnp/lib/capnp.pyx:3752: in capnp.lib.capnp.load (capnp/lib/capnp.cpp:71239)
    ???
capnp/lib/capnp.pyx:3126: in capnp.lib.capnp.SchemaParser.load (capnp/lib/capnp.cpp:63334)
    ???
E   KjException: /home/mmm/devel/nupic/nupic.core/bindings/py/nupic/proto/ConnectionsProto.capnp:0: failed: Duplicate ID @0xb1b8a459d70716ad.
E   stack: 0x7f2513dfcf08 0x7f2513d1c928 0x7f2513d1c530 0x7f2513d47178 0x7f2513d4768a 0x7f2513d4b9b6 0x7f2513d4baab 0x7f2513d4bb5b 0x7f2513d4bba4 0x7f2513d5792a 0x7f2513d56dbe 0x7f2513d5a338 0x7f2513d4406c 0x7f2513d4b93e 0x7f2513d44cee 0x7f2513d44fff
=========================================================================================================== FAILURES ============================================================================================================
___________________________________________________________________________________ CoordinateEncoderTest.testEncodeRelativePositionsAndRadii ___________________________________________________________________________________
self = <tests.unit.nupic.encoders.coordinate_test.CoordinateEncoderTest testMethod=testEncodeRelativePositionsAndRadii>

    def testEncodeRelativePositionsAndRadii(self):
      # As radius increases and positions change, the overlap should decrease
      overlaps = overlapsForRelativeAreas(999, 25, np.array([100, 200]), 5,
                                          dPosition=np.array([1, 1]),
                                          dRadius=1,
                                          num=5)
>     self.assertDecreasingOverlaps(overlaps)

tests/unit/nupic/encoders/coordinate_test.py:208: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <tests.unit.nupic.encoders.coordinate_test.CoordinateEncoderTest testMethod=testEncodeRelativePositionsAndRadii>, overlaps = array([ 0.64,  0.44,  0.2 ,  0.2 ,  0.16])

    def assertDecreasingOverlaps(self, overlaps):
>     self.assertEqual((np.diff(overlaps) >= 0).sum(), 0)
E     AssertionError: 1 != 0

tests/unit/nupic/encoders/coordinate_test.py:267: AssertionError
-------------------------------------------------------------------------------------------------------- Captured stderr --------------------------------------------------------------------------------------------------------
/home/mmm/devel/nupic/nupic-source/tests/unit/nupic/encoders/coordinate_test.py:330: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  newPosition = initPosition if dPosition == None else (
_________________________________________________________________________________________ CoordinateEncoderTest.testEncodeRelativeRadii _________________________________________________________________________________________
self = <tests.unit.nupic.encoders.coordinate_test.CoordinateEncoderTest testMethod=testEncodeRelativeRadii>

    def testEncodeRelativeRadii(self):
      # As radius increases, the overlap should decrease
      overlaps = overlapsForRelativeAreas(999, 25, np.array([100, 200]), 5,
                                          dRadius=2,
                                          num=5)
>     self.assertDecreasingOverlaps(overlaps)

tests/unit/nupic/encoders/coordinate_test.py:193: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <tests.unit.nupic.encoders.coordinate_test.CoordinateEncoderTest testMethod=testEncodeRelativeRadii>, overlaps = array([ 0.52,  0.2 ,  0.16,  0.16,  0.08])

    def assertDecreasingOverlaps(self, overlaps):
>     self.assertEqual((np.diff(overlaps) >= 0).sum(), 0)
E     AssertionError: 1 != 0

tests/unit/nupic/encoders/coordinate_test.py:267: AssertionError
__________________________________________________________________________________________________ TestNupicRandom.testSample ___________________________________________________________________________________________________
self = <tests.unit.nupic.math.nupic_random_test.TestNupicRandom testMethod=testSample>

    def testSample(self):
      r = Random(42)
      population = numpy.array([1, 2, 3, 4], dtype="uint32")
      choices = numpy.zeros([2], dtype="uint32")
    
      r.sample(population, choices)
    
>     self.assertEqual(choices[0], 2)
E     AssertionError: 1 != 2

tests/unit/nupic/math/nupic_random_test.py:76: AssertionError
__________________________________________________________________________________________________ TestNupicRandom.testShuffle __________________________________________________________________________________________________
self = <tests.unit.nupic.math.nupic_random_test.TestNupicRandom testMethod=testShuffle>

    def testShuffle(self):
      r = Random(42)
      arr = numpy.array([1, 2, 3, 4], dtype="uint32")
    
      r.shuffle(arr)
    
>     self.assertEqual(arr[0], 3)
E     AssertionError: 1 != 3

tests/unit/nupic/math/nupic_random_test.py:165: AssertionError
================================================================================== 4 failed, 756 passed, 20 skipped, 2 error in 110.63 seconds ==================================================================================
```

**Comment by breznak** [comment]
@scottpurdy are the Duplicate ID KjExceptions related to https://github.com/jparyani/pycapnp/issues/62#issuecomment-134833958 ? But I get it with "develop" too.

**Comment by breznak** [comment]
Closing as the capnp rebuild magically fixed that.
