### ISSUE TITLE
hotgym.py example crashes on OS X 10.10 when using homebrewed Python

### ISSUE THREAD

**Issue by alexbool** [numenta/nupic#2155]
Nupic was built and installed from sources: I cloned the repository and ran `python setup.py install`.
I had to use the workaround to avoid https://github.com/numenta/nupic/issues/1813
This is the error:
```
alexbool@alexbool-osx ~/D/nupic-playground> python ../nupic/examples/opf/clients/hotgym/simple/hotgym.py 
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 548, in <module>
    main()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 530, in main
    known_paths = addusersitepackages(known_paths)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 266, in addusersitepackages
    user_site = getusersitepackages()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 241, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 231, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sysconfig.py", line 520, in get_config_var
    return get_config_vars().get(name)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sysconfig.py", line 453, in get_config_vars
    import re
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 108, in <module>
    import _locale
SystemError: dynamic module not initialized properly
```

When I run `import _locale` in python console, it works OK.

This also reproduces when swarming: individual tasks fail with the same message.
Seems like this is not related to nupic itself, but to the way it was built or maybe other modules in the system were built, but as for now I have no clues.

**Comment by alexbool** [comment]
Well, actually, I have a clue. When I removed "stock" system python, I started to get errors like this:
```
alexbool@alexbool-osx ~/D/nupic> python examples/opf/clients/hotgym/simple/hotgym.py
ERR:  CHECK FAILED: "p" Unable to load the pynode library: Failed to load "/Users/alexbool/Documents/nupic/nupic/libcpp_region.so": dlopen(/Users/alexbool/Documents/nupic/nupic/libcpp_region.so, 9): Library not loaded: /System/Library/Frameworks/Python.framework/Versions/2.7/Python
  Referenced from: /Users/alexbool/Documents/nupic/nupic/libcpp_region.so
  Reason: image not found [/Users/travis/build/numenta/nupic.core/src/nupic/engine/RegionImplFactory.cpp line 111]
Traceback (most recent call last):
  File "examples/opf/clients/hotgym/simple/hotgym.py", line 97, in <module>
    runHotgym()
  File "examples/opf/clients/hotgym/simple/hotgym.py", line 68, in runHotgym
    model = createModel()
  File "examples/opf/clients/hotgym/simple/hotgym.py", line 63, in createModel
    return ModelFactory.create(model_params.MODEL_PARAMS)
  File "/usr/local/lib/python2.7/site-packages/nupic-0.3.0.dev0-py2.7-macosx-10.10-x86_64.egg/nupic/frameworks/opf/modelfactory.py", line 80, in create
    return modelClass(**modelConfig['modelParams'])
  File "/usr/local/lib/python2.7/site-packages/nupic-0.3.0.dev0-py2.7-macosx-10.10-x86_64.egg/nupic/frameworks/opf/clamodel.py", line 200, in __init__
    clParams, anomalyParams)
  File "/usr/local/lib/python2.7/site-packages/nupic-0.3.0.dev0-py2.7-macosx-10.10-x86_64.egg/nupic/frameworks/opf/clamodel.py", line 1043, in __createCLANetwork
    n.addRegion("sensor", "py.RecordSensor", json.dumps(dict(verbosity=sensorParams['verbosity'])))
  File "/usr/local/lib/python2.7/site-packages/nupic-0.3.0.dev0-py2.7-macosx-10.10-x86_64.egg/nupic/engine/__init__.py", line 636, in addRegion
    engine.Network.addRegion(self, name, nodeType, nodeParams)
  File "/usr/local/lib/python2.7/site-packages/nupic-0.3.0.dev0-py2.7-macosx-10.10-x86_64.egg/nupic/bindings/engine_internal.py", line 1086, in addRegion
    return _engine_internal.Network_addRegion(self, *args, **kwargs)
RuntimeError: CHECK FAILED: "p" Unable to load the pynode library: Failed to load "/Users/alexbool/Documents/nupic/nupic/libcpp_region.so": dlopen(/Users/alexbool/Documents/nupic/nupic/libcpp_region.so, 9): Library not loaded: /System/Library/Frameworks/Python.framework/Versions/2.7/Python
  Referenced from: /Users/alexbool/Documents/nupic/nupic/libcpp_region.so
  Reason: image not found
```

Then I symlinked brewed python to /System/Library/Frameworks/Python.framework and voila! it worked.
The question is: is there a way to stop libcpp_region.so thinking it needs /System/Library/Frameworks/Python.framework and make it want homebrewed python instead?
