### ISSUE TITLE
Failing Swarming Tests

### ISSUE THREAD

**Issue by jaredweiss** [numenta/nupic#2171]
When running ```$ ./scripts/run_nupic_tests -w``` the MultiNodeTests.testAlwaysInputPredictedField test fails. 
Here's the full error:

tests/swarming/nupic/swarming/swarming_test.py:2288: MultiNodeTests.testAlwaysInputPredictedField FAILED

================================================================ FAILURES =================================================================
______________________________________________ MultiNodeTests.testAlwaysInputPredictedField _______________________________________________
self = <tests.swarming.nupic.swarming.swarming_test.MultiNodeTests testMethod=testAlwaysInputPredictedField>

    def testAlwaysInputPredictedField(self):

      self._printTestHeader()
      inst = OneNodeTests(self._testMethodName)
>     return inst.testAlwaysInputPredictedField(onCluster=True)

tests/swarming/nupic/swarming/swarming_test.py:2292:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <tests.swarming.nupic.swarming.swarming_test.OneNodeTests testMethod=testAlwaysInputPredictedField>, onCluster = True
env = {'NTA_CONF_PROP_nupic_hypersearch_minParticlesPerSwarm': '2', 'NTA_CONF_PROP_nupic_hypersearch_swarmMaturityWindow': '..._DATA_PATH': '/Users/jweiss/nta/nupic/tests/swarming/nupic/swarming/data', 'NTA_TEST_inputPredictedField': 'auto', ...}
kwargs = {}, expDir = '/Users/jweiss/nta/nupic/tests/swarming/nupic/swarming/experiments/input_predicted_field', jobID = 1133
jobInfo = _jobInfoNamedTuple(jobId=1133, client=u'test', clientInfo=u'', clientKey=u'', ...ngCjmConnId=None, engWorkerState=None, engStatus=None, engModelMilestones=None)
resultInfos = [], metricResults = [], minErrScore = None

    def testAlwaysInputPredictedField(self, onCluster=False, env=None,
                                        **kwargs):
      """
        Run a swarm where 'inputPredictedField' is set in the permutations
        file. The dummy model for this swarm is designed to give the lowest
        error when the predicted field is INCLUDED, so make sure we don't get
        this low error
        """
      self._printTestHeader()
      expDir = os.path.join(g_myEnv.testSrcExpDir, 'input_predicted_field')

      # Test it out not requiring the predicted field. This should yield a
      #  low error score
      if env is None:
        env = dict()
      env["NTA_TEST_inputPredictedField"] = "auto"
      env["NTA_TEST_numIterations"] = '99'
      env["NTA_CONF_PROP_nupic_hypersearch_minParticlesPerSwarm"] = \
                           '%d' % (2)
      env["NTA_CONF_PROP_nupic_hypersearch_swarmMaturityWindow"] = \
                           '%d' % (g_repeatableSwarmMaturityWindow)

      (jobID, jobInfo, resultInfos, metricResults, minErrScore) \
             = self.runPermutations(expDir,
                                    hsImp='v2',
                                    loggingLevel=g_myEnv.options.logLevel,
                                    onCluster=onCluster,
                                    env=env,
                                    maxModels=None,
                                    **kwargs)

>     self.assertEqual(minErrScore, -50)

tests/swarming/nupic/swarming/swarming_test.py:1398:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <tests.swarming.nupic.swarming.swarming_test.OneNodeTests testMethod=testAlwaysInputPredictedField>, first = None, second = -50
msg = None

    def assertEqual(self, first, second, msg=None):
      """unittest.TestCase.assertEqual override; adds extra log items to msg"""
>     unittest.TestCase.assertEqual(self, first, second, self.__wrapMsg(msg))
E     AssertionError: None != -50 : None

nupic/support/unittesthelpers/testcasebase.py:117: AssertionError
------------------------------------------------------------- Captured stdout -------------------------------------------------------------

CURRENT DIRECTORY: /Users/jweiss/nta/nupic
###############################################################
Running test: <class 'tests.swarming.nupic.swarming.swarming_test.MultiNodeTests'>.testAlwaysInputPredictedField...
###############################################################
Running test: <class 'tests.swarming.nupic.swarming.swarming_test.OneNodeTests'>.testAlwaysInputPredictedField...

==================================================================
Running Hypersearch job on cluster
==================================================================
2015-06-03 10:26:56,181 - com.numenta.nupic.database.Connection.ConnectionFactory(28653) - INFO - Creating db connection policy via provider <bound method type._createDefaultPolicy of <class 'nupic.database.Connection.ConnectionFactory'>>
2015-06-03 10:26:56,182 - com.numenta.nupic.database.Connection.PooledConnectionPolicy(28653) - INFO - Created PooledConnectionPolicy
2015-06-03 10:26:56,197 - com.numenta.nupic.database.ClientJobsDAO.ClientJobsDAO(28653) - INFO - clientJobsConnectionID=1463
2015-06-03 10:26:56,221 - com.numenta.nupic.database.ClientJobsDAO.ClientJobsDAO(28653) - INFO - jobInsert: returning jobID=1133. jobType='hypersearch'; client='test'; clientInfo=''; clientKey=''; jobHash='\xbb\x8f08\n\x15\x11\xe5\x80\xe9<\x07TQNt'; cmdLine='export NTA_CONF_PROP_nupic_hypersearch_minParticlesPerSwarm=2;export NTA_TEST_numIterations=99;export NTA_TEST_inputPredictedField=auto;export NTA_CONF_PROP_nupic_hypersearch_swarmMaturityWindow=5;export NTA_DATA_PATH=/Users/jweiss/nta/nupic/tests/swarming/nupic/swarming/data; python -m nupic.swarming.HypersearchWorker --jobID={JOBID} --logLevel=20'
Successfully submitted new test job, jobID=1133
Each of 4 workers executing the command line:  export NTA_CONF_PROP_nupic_hypersearch_minParticlesPerSwarm=2;export NTA_TEST_numIterations=99;export NTA_TEST_inputPredictedField=auto;export NTA_CONF_PROP_nupic_hypersearch_swarmMaturityWindow=5;export NTA_DATA_PATH=/Users/jweiss/nta/nupic/tests/swarming/nupic/swarming/data; python -m nupic.swarming.HypersearchWorker --jobID={JOBID} --logLevel=20

jobStatus          modelsStarted   modelsCompleted modelErrs       modelOrphans
-------------------------------------------------------------------
# Swarm job now running. jobID=1133
running         0               0               0               0
completed       0               0               0               0

<< completed       0               0               0               0

------------------------------------------------------------------
Hadoop completion reason: success
Worker completion reason: error
Worker completion msg: E10003: Exception occurred in Hypersearch Worker: KjException()
Traceback (most recent call last):
  File "/Users/jweiss/nta/nupic/nupic/swarming/HypersearchWorker.py", line 551, in main
    jobID = hst.run()
  File "/Users/jweiss/nta/nupic/nupic/swarming/HypersearchWorker.py", line 312, in run
    cjDAO=cjDAO, jobID=options.jobID, logLevel=options.logLevel)
  File "nupic/swarming/HypersearchV2.py", line 2577, in __init__
    modelDescription, _ = opfhelpers.loadExperiment(self._basePath)
  File "nupic/frameworks/opf/opfhelpers.py", line 46, in loadExperiment
    descriptionPyModule = loadExperimentDescriptionScriptFromDir(path)
  File "nupic/frameworks/opf/opfhelpers.py", line 60, in loadExperimentDescriptionScriptFromDir
    module = _loadDescriptionFile(descriptionScriptPath)
  File "nupic/frameworks/opf/opfhelpers.py", line 92, in _loadDescriptionFile
    descriptionPyPath)
  File "/var/folders/7g/lp19p4q91rng7mncmy27msnh0000gp/T/tmp_ugHMj/description.py", line 37, in <module>
  File "nupic/frameworks/opf/clamodelcallbacks.py", line 29, in <module>
    from clamodel import CLAModel
  File "nupic/frameworks/opf/clamodel.py", line 44, in <module>
    from nupic.encoders import MultiEncoder, DeltaEncoder
  File "nupic/encoders/__init__.py", line 34, in <module>
    from multi import MultiEncoder
  File "nupic/encoders/multi.py", line 40, in <module>
    from nupic.encoders.scalar_capnp import ScalarEncoderProto
  File "capnp/lib/capnp.pyx", line 3773, in capnp.lib.capnp._Loader.load_module (capnp/lib/capnp.cpp:71749)
    module = load(self.path, fullname, imports=imports)
  File "capnp/lib/capnp.pyx", line 3752, in capnp.lib.capnp.load (capnp/lib/capnp.cpp:71239)
    return _global_schema_parser.load(file_name, display_name, imports)
  File "capnp/lib/capnp.pyx", line 3126, in capnp.lib.capnp.SchemaParser.load (capnp/lib/capnp.cpp:63334)
    fileSchema = parser._parse_disk_file(display_name, file_name, imports)
KjException: /Users/jweiss/nta/nupic/nupic/encoders/scalar.capnp:0: failed: Duplicate ID @0xfa7d16f86048a6e4.
stack: 0x1060b4b97 0x10600d500 0x10600d717 0x105ffeae9 0x105ffe80b 0x1060032d7 0x106005541 0x106005d3d 0x10600adfb 0x10600ad5d 0x105f55577 0x105f7f275 0x105f67228 0x105f65f19 0x103d6d2ac 0x103d780cf

No models finished
------------------------------------------------------------- Captured stderr -------------------------------------------------------------
Using logging configuration file: /Users/jweiss/nta/nupic/nupic/support/nupic-logging.conf
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by breznak** [comment]
likely duplicate of https://github.com/numenta/nupic/issues/2113 and the `KjException` issues
