### ISSUE TITLE
unable to build nupic

### ISSUE THREAD

**Issue by dducro** [numenta/nupic#2201]
Hey,

I'm having trouble building nupic, this is my output building the latest version of nupic. (NuPIC 0.2.3)
I used gcc 4.8 however I can't get it to install, this is the second ubuntu system with the same problem.
Any suggestions to fix it? Maybe updating some other package?
(this is the original vm from here: https://github.com/numenta/nupic/wiki/Running-Nupic-in-a-Virtual-Machine. I just updated all the packages / repos and did a git pull on the nupic projects. After that I wanted to update nupic without success)

```
nupic@nupic-vm:~/nupic$ gcc --version
gcc (Ubuntu 4.8.1-2ubuntu1~13.04) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
nupic@nupic-vm:~/nupic$ cmake --version
cmake version 2.8.10.1
nupic@nupic-vm:~/nupic$ python --version
Python 2.7.4
nupic@nupic-vm:~/nupic$ clang --version
Ubuntu clang version 3.2-1~exp9ubuntu1 (tags/RELEASE_32/final) (based on LLVM 3.2)
Target: x86_64-pc-linux-gnu
Thread model: posix
nupic@nupic-vm:~/nupic$ python setup.py install --user
Target nupic.core package already exists at /home/nupic/nupic/extensions/core/nupic_core-a25068f00bde589f029e0cfc94ac3343bfaa9254-linux64.tar.gz.
Unpacking /home/nupic/nupic/extensions/core/nupic_core-a25068f00bde589f029e0cfc94ac3343bfaa9254-linux64.tar.gz into /home/nupic/nupic/extensions/core/build/release...
/home/nupic/nupic/external/linux64/bin/swig -c++ -python -features autodoc=0,directors=0 -noproxyimport -keyword -modern -modernargs -noproxydel -fvirtual -fastunpack -nofastproxy -fastquery -outputtuple -castmode -nosafecstrings -w402 -w503 -w511 -w302 -w362 -w312 -w389 -DSWIG_PYTHON_LEGACY_BOOL -I/home/nupic/nupic/external/common/share/swig/3.0.2/python -I/home/nupic/nupic/external/common/share/swig/3.0.2 -DNUPIC2 -DNTA_OS_LINUX -DNTA_ARCH_64 -DNTA_PYTHON_SUPPORT=2.7 -DNTA_INTERNAL -DNTA_ASSERTIONS_ON -DNTA_ASM -DHAVE_CONFIG_H -DBOOST_NO_WREGEX -I/home/nupic/nupic/external/linux64/include -I/home/nupic/nupic/external/common/include -I/home/nupic/nupic/extensions -I/home/nupic/nupic -I/home/nupic/nupic/extensions/core/build/release/include -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include nupic/bindings/algorithms.i
/home/nupic/nupic/extensions/core/build/release/include/nupic/math/Math.hpp:521: Warning 325: Nested struct not currently supported (lexicographic ignored)
/home/nupic/nupic/extensions/core/build/release/include/nupic/math/Math.hpp:533: Warning 325: Nested struct not currently supported (less_value ignored)
/home/nupic/nupic/extensions/core/build/release/include/nupic/math/Math.hpp:545: Warning 325: Nested struct not currently supported (greater_value ignored)
/home/nupic/nupic/extensions/core/build/release/include/nupic/math/SparseBinaryMatrix.hpp:566: Warning 325: Nested struct not currently supported (lexicographic_order ignored)
nupic/bindings/algorithms.i:722: Warning 303: %extend defined for an undeclared class nupic::algorithms::Inhibition.
nupic/bindings/algorithms.i:752: Warning 303: %extend defined for an undeclared class nupic::algorithms::Inhibition2.
/home/nupic/nupic/extensions/core/build/release/include/nupic/utils/LoggingException.hpp:36: Warning 401: Nothing known about base class 'Exception'. Ignored.
/home/nupic/nupic/external/linux64/bin/swig -c++ -python -features autodoc=0,directors=0 -noproxyimport -keyword -modern -modernargs -noproxydel -fvirtual -fastunpack -nofastproxy -fastquery -outputtuple -castmode -nosafecstrings -w402 -w503 -w511 -w302 -w362 -w312 -w389 -DSWIG_PYTHON_LEGACY_BOOL -I/home/nupic/nupic/external/common/share/swig/3.0.2/python -I/home/nupic/nupic/external/common/share/swig/3.0.2 -DNUPIC2 -DNTA_OS_LINUX -DNTA_ARCH_64 -DNTA_PYTHON_SUPPORT=2.7 -DNTA_INTERNAL -DNTA_ASSERTIONS_ON -DNTA_ASM -DHAVE_CONFIG_H -DBOOST_NO_WREGEX -I/home/nupic/nupic/external/linux64/include -I/home/nupic/nupic/external/common/include -I/home/nupic/nupic/extensions -I/home/nupic/nupic -I/home/nupic/nupic/extensions/core/build/release/include -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include nupic/bindings/engine_internal.i
/home/nupic/nupic/external/linux64/bin/swig -c++ -python -features autodoc=0,directors=0 -noproxyimport -keyword -modern -modernargs -noproxydel -fvirtual -fastunpack -nofastproxy -fastquery -outputtuple -castmode -nosafecstrings -w402 -w503 -w511 -w302 -w362 -w312 -w389 -DSWIG_PYTHON_LEGACY_BOOL -I/home/nupic/nupic/external/common/share/swig/3.0.2/python -I/home/nupic/nupic/external/common/share/swig/3.0.2 -DNUPIC2 -DNTA_OS_LINUX -DNTA_ARCH_64 -DNTA_PYTHON_SUPPORT=2.7 -DNTA_INTERNAL -DNTA_ASSERTIONS_ON -DNTA_ASM -DHAVE_CONFIG_H -DBOOST_NO_WREGEX -I/home/nupic/nupic/external/linux64/include -I/home/nupic/nupic/external/common/include -I/home/nupic/nupic/extensions -I/home/nupic/nupic -I/home/nupic/nupic/extensions/core/build/release/include -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include nupic/bindings/math.i
/home/nupic/nupic/extensions/core/build/release/include/nupic/math/Math.hpp:521: Warning 325: Nested struct not currently supported (lexicographic ignored)
/home/nupic/nupic/extensions/core/build/release/include/nupic/math/Math.hpp:533: Warning 325: Nested struct not currently supported (less_value ignored)
/home/nupic/nupic/extensions/core/build/release/include/nupic/math/Math.hpp:545: Warning 325: Nested struct not currently supported (greater_value ignored)
/home/nupic/nupic/extensions/core/build/release/include/nupic/math/SparseBinaryMatrix.hpp:566: Warning 325: Nested struct not currently supported (lexicographic_order ignored)
/home/nupic/nupic/extensions/core/build/release/include/nupic/utils/LoggingException.hpp:36: Warning 401: Nothing known about base class 'Exception'. Ignored.
running install
running bdist_egg
running egg_info
writing requirements to nupic.egg-info/requires.txt
writing nupic.egg-info/PKG-INFO
writing top-level names to nupic.egg-info/top_level.txt
writing dependency_links to nupic.egg-info/dependency_links.txt
reading manifest file 'nupic.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: manifest_maker: MANIFEST.in, line 15: 'recursive-include' expects <dir> <pattern1> <pattern2> ...

writing manifest file 'nupic.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying nupic/bindings/algorithms.py -> build/lib.linux-x86_64-2.7/nupic/bindings
copying nupic/bindings/math.py -> build/lib.linux-x86_64-2.7/nupic/bindings
copying nupic/bindings/engine_internal.py -> build/lib.linux-x86_64-2.7/nupic/bindings
copying nupic/bindings/algorithms_wrap.cxx -> build/lib.linux-x86_64-2.7/nupic/bindings
copying nupic/bindings/engine_internal_wrap.cxx -> build/lib.linux-x86_64-2.7/nupic/bindings
copying nupic/bindings/math_wrap.cxx -> build/lib.linux-x86_64-2.7/nupic/bindings
copying nupic/bindings/proto/RandomProto.capnp -> build/lib.linux-x86_64-2.7/nupic/bindings/proto
copying nupic/bindings/proto/SparseMatrixProto.capnp -> build/lib.linux-x86_64-2.7/nupic/bindings/proto
copying nupic/bindings/proto/SparseBinaryMatrixProto.capnp -> build/lib.linux-x86_64-2.7/nupic/bindings/proto
copying nupic/bindings/proto/SpatialPoolerProto.capnp -> build/lib.linux-x86_64-2.7/nupic/bindings/proto
copying nupic/bindings/proto/BitHistory.capnp -> build/lib.linux-x86_64-2.7/nupic/bindings/proto
copying nupic/bindings/proto/ConnectionsProto.capnp -> build/lib.linux-x86_64-2.7/nupic/bindings/proto
copying nupic/bindings/proto/ClaClassifier.capnp -> build/lib.linux-x86_64-2.7/nupic/bindings/proto
copying nupic/bindings/proto/TemporalMemoryProto.capnp -> build/lib.linux-x86_64-2.7/nupic/bindings/proto
running build_ext
building 'nupic.bindings._algorithms' extension
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DNUPIC2 -DNTA_OS_LINUX -DNTA_ARCH_64 -DNTA_PYTHON_SUPPORT=2.7 -DNTA_INTERNAL -DNTA_ASSERTIONS_ON -DNTA_ASM -DHAVE_CONFIG_H -DBOOST_NO_WREGEX -I/home/nupic/nupic/external/linux64/include -I/home/nupic/nupic/external/common/include -I/home/nupic/nupic/extensions -I/home/nupic/nupic -I/home/nupic/nupic/extensions/core/build/release/include -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c extensions/py_support/NumpyVector.cpp -o build/temp.linux-x86_64-2.7/extensions/py_support/NumpyVector.o -std=c++11 -m64 -fPIC -fvisibility=hidden -Wall -Wextra -Wreturn-type -Wunused -Wno-unused-parameter -mtune=generic -O2
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from /usr/include/python2.7/numpy/ndarraytypes.h:1728:0,
                 from /usr/include/python2.7/numpy/ndarrayobject.h:17,
                 from /usr/include/python2.7/numpy/arrayobject.h:15,
                 from extensions/py_support/NumpyVector.cpp:33:
/usr/include/python2.7/numpy/npy_deprecated_api.h:11:2: warning: #warning "Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DNUPIC2 -DNTA_OS_LINUX -DNTA_ARCH_64 -DNTA_PYTHON_SUPPORT=2.7 -DNTA_INTERNAL -DNTA_ASSERTIONS_ON -DNTA_ASM -DHAVE_CONFIG_H -DBOOST_NO_WREGEX -I/home/nupic/nupic/external/linux64/include -I/home/nupic/nupic/external/common/include -I/home/nupic/nupic/extensions -I/home/nupic/nupic -I/home/nupic/nupic/extensions/core/build/release/include -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c extensions/py_support/PyArray.cpp -o build/temp.linux-x86_64-2.7/extensions/py_support/PyArray.o -std=c++11 -m64 -fPIC -fvisibility=hidden -Wall -Wextra -Wreturn-type -Wunused -Wno-unused-parameter -mtune=generic -O2
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from /usr/include/python2.7/numpy/ndarraytypes.h:1728:0,
                 from /usr/include/python2.7/numpy/ndarrayobject.h:17,
                 from /usr/include/python2.7/numpy/arrayobject.h:15,
                 from extensions/py_support/PyArray.cpp:33:
/usr/include/python2.7/numpy/npy_deprecated_api.h:11:2: warning: #warning "Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DNUPIC2 -DNTA_OS_LINUX -DNTA_ARCH_64 -DNTA_PYTHON_SUPPORT=2.7 -DNTA_INTERNAL -DNTA_ASSERTIONS_ON -DNTA_ASM -DHAVE_CONFIG_H -DBOOST_NO_WREGEX -I/home/nupic/nupic/external/linux64/include -I/home/nupic/nupic/external/common/include -I/home/nupic/nupic/extensions -I/home/nupic/nupic -I/home/nupic/nupic/extensions/core/build/release/include -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c extensions/py_support/PyHelpers.cpp -o build/temp.linux-x86_64-2.7/extensions/py_support/PyHelpers.o -std=c++11 -m64 -fPIC -fvisibility=hidden -Wall -Wextra -Wreturn-type -Wunused -Wno-unused-parameter -mtune=generic -O2
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DNUPIC2 -DNTA_OS_LINUX -DNTA_ARCH_64 -DNTA_PYTHON_SUPPORT=2.7 -DNTA_INTERNAL -DNTA_ASSERTIONS_ON -DNTA_ASM -DHAVE_CONFIG_H -DBOOST_NO_WREGEX -I/home/nupic/nupic/external/linux64/include -I/home/nupic/nupic/external/common/include -I/home/nupic/nupic/extensions -I/home/nupic/nupic -I/home/nupic/nupic/extensions/core/build/release/include -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c extensions/py_support/PythonStream.cpp -o build/temp.linux-x86_64-2.7/extensions/py_support/PythonStream.o -std=c++11 -m64 -fPIC -fvisibility=hidden -Wall -Wextra -Wreturn-type -Wunused -Wno-unused-parameter -mtune=generic -O2
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DNUPIC2 -DNTA_OS_LINUX -DNTA_ARCH_64 -DNTA_PYTHON_SUPPORT=2.7 -DNTA_INTERNAL -DNTA_ASSERTIONS_ON -DNTA_ASM -DHAVE_CONFIG_H -DBOOST_NO_WREGEX -I/home/nupic/nupic/external/linux64/include -I/home/nupic/nupic/external/common/include -I/home/nupic/nupic/extensions -I/home/nupic/nupic -I/home/nupic/nupic/extensions/core/build/release/include -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c nupic/bindings/algorithms_wrap.cxx -o build/temp.linux-x86_64-2.7/nupic/bindings/algorithms_wrap.o -std=c++11 -m64 -fPIC -fvisibility=hidden -Wall -Wextra -Wreturn-type -Wunused -Wno-unused-parameter -mtune=generic -O2
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from /usr/include/python2.7/numpy/ndarraytypes.h:1728:0,
                 from /usr/include/python2.7/numpy/ndarrayobject.h:17,
                 from /usr/include/python2.7/numpy/arrayobject.h:15,
                 from nupic/bindings/algorithms_wrap.cxx:4383:
/usr/include/python2.7/numpy/npy_deprecated_api.h:11:2: warning: #warning "Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
In file included from /home/nupic/nupic/extensions/core/build/release/include/capnp/layout.h:37:0,
                 from /home/nupic/nupic/extensions/core/build/release/include/capnp/generated-header-support.h:31,
                 from /home/nupic/nupic/extensions/core/build/release/include/nupic/proto/RandomProto.capnp.h:7,
                 from /home/nupic/nupic/extensions/core/build/release/include/nupic/utils/Random.hpp:36,
                 from /home/nupic/nupic/extensions/core/build/release/include/nupic/math/ArrayAlgo.hpp:41,
                 from /home/nupic/nupic/extensions/core/build/release/include/nupic/math/SparseMatrix.hpp:38,
                 from nupic/bindings/algorithms_wrap.cxx:4366:
/home/nupic/nupic/extensions/core/build/release/include/kj/memory.h:213:28: error: expected ‘;’ at end of member declaration
/home/nupic/nupic/extensions/core/build/release/include/kj/memory.h:213:32: error: expected unqualified-id before ‘{’ token
/home/nupic/nupic/extensions/core/build/release/include/kj/memory.h:213:48: error: expected ‘;’ at end of member declaration
/home/nupic/nupic/extensions/core/build/release/include/kj/memory.h:214:36: error: expected ‘;’ at end of member declaration
/home/nupic/nupic/extensions/core/build/release/include/kj/memory.h:214:44: error: expected unqualified-id before ‘{’ token
/home/nupic/nupic/extensions/core/build/release/include/kj/memory.h:214:60: error: expected ‘;’ at end of member declaration
/home/nupic/nupic/extensions/core/build/release/include/kj/memory.h:215:29: error: expected ‘;’ at end of member declaration
/home/nupic/nupic/extensions/core/build/release/include/kj/memory.h:215:19: error: ‘kj::Own<T>&& kj::_::OwnOwn<T>::operator*()’ cannot be overloaded
/home/nupic/nupic/extensions/core/build/release/include/kj/memory.h:213:18: error: with ‘kj::Own<T>& kj::_::OwnOwn<T>::operator*()’
/home/nupic/nupic/extensions/core/build/release/include/kj/memory.h:215:34: error: expected unqualified-id before ‘{’ token
/home/nupic/nupic/extensions/core/build/release/include/kj/memory.h:215:58: error: expected ‘;’ at end of member declaration
/home/nupic/nupic/extensions/core/build/release/include/kj/memory.h:216:37: error: expected ‘;’ at end of member declaration
/home/nupic/nupic/extensions/core/build/release/include/kj/memory.h:216:25: error: ‘const kj::Own<T>&& kj::_::OwnOwn<T>::operator*() const’ cannot be overloaded
/home/nupic/nupic/extensions/core/build/release/include/kj/memory.h:214:24: error: with ‘const kj::Own<T>& kj::_::OwnOwn<T>::operator*() const’
/home/nupic/nupic/extensions/core/build/release/include/kj/memory.h:216:46: error: expected unqualified-id before ‘{’ token
/home/nupic/nupic/extensions/core/build/release/include/kj/memory.h:216:70: error: expected ‘;’ at end of member declaration
In file included from /home/nupic/nupic/extensions/core/build/release/include/nupic/proto/RandomProto.capnp.h:7:0,
                 from /home/nupic/nupic/extensions/core/build/release/include/nupic/utils/Random.hpp:36,
                 from /home/nupic/nupic/extensions/core/build/release/include/nupic/math/ArrayAlgo.hpp:41,
                 from /home/nupic/nupic/extensions/core/build/release/include/nupic/math/SparseMatrix.hpp:38,
                 from nupic/bindings/algorithms_wrap.cxx:4366:
/home/nupic/nupic/extensions/core/build/release/include/capnp/generated-header-support.h: In constructor ‘constexpr capnp::_::RawBrandedSchema::Binding::Binding(uint8_t, uint16_t, const capnp::_::RawBrandedSchema*)’:
/home/nupic/nupic/extensions/core/build/release/include/capnp/generated-header-support.h:82:27: error: uninitialized member ‘capnp::_::RawBrandedSchema::Binding::<anonymous>’ in ‘constexpr’ constructor
/home/nupic/nupic/extensions/core/build/release/include/capnp/generated-header-support.h: In constructor ‘constexpr capnp::_::RawBrandedSchema::Binding::Binding(uint8_t, uint16_t, uint64_t, uint16_t)’:
/home/nupic/nupic/extensions/core/build/release/include/capnp/generated-header-support.h:86:29: error: uninitialized member ‘capnp::_::RawBrandedSchema::Binding::<anonymous>’ in ‘constexpr’ constructor
/home/nupic/nupic/extensions/core/build/release/include/capnp/generated-header-support.h: In constructor ‘constexpr capnp::_::RawBrandedSchema::Binding::Binding(uint8_t, uint16_t, uint16_t)’:
/home/nupic/nupic/extensions/core/build/release/include/capnp/generated-header-support.h:89:55: error: uninitialized member ‘capnp::_::RawBrandedSchema::Binding::<anonymous>’ in ‘constexpr’ constructor
In file included from nupic/bindings/algorithms_wrap.cxx:4367:0:
/home/nupic/nupic/extensions/core/build/release/include/nupic/math/SparseBinaryMatrix.hpp: In member function ‘void nupic::SparseBinaryMatrix<UI1, UI2>::sparse_row_invariants_(InputIterator, InputIterator, const char*) const’:
/home/nupic/nupic/extensions/core/build/release/include/nupic/math/SparseBinaryMatrix.hpp:2008:12: warning: suggest explicit braces to avoid ambiguous ‘else’ [-Wparentheses]
In file included from /usr/include/python2.7/numpy/ndarrayobject.h:26:0,
                 from /usr/include/python2.7/numpy/arrayobject.h:15,
                 from nupic/bindings/algorithms_wrap.cxx:4383:
/usr/include/python2.7/numpy/__multiarray_api.h: At global scope:
/usr/include/python2.7/numpy/__multiarray_api.h:1594:1: warning: ‘int _import_array()’ defined but not used [-Wunused-function]
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
nupic@nupic-vm:~/nupic$ 
```

And the following is the output from:
    pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic/releases/nupic-0.2.3-cp27-none-linux_x86_64.whl

```
Downloading/unpacking https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic/releases/nupic-0.2.3-cp27-none-linux_x86_64.whl
  Downloading nupic-0.2.3-cp27-none-linux_x86_64.whl (22.0MB): 22.0MB downloaded
  Running setup.py egg_info for package from https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic/releases/nupic-0.2.3-cp27-none-linux_x86_64.whl
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
    IOError: [Errno 2] No such file or directory: '/tmp/pip-o3Df4R-build/setup.py'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

IOError: [Errno 2] No such file or directory: '/tmp/pip-o3Df4R-build/setup.py'

----------------------------------------
Command python setup.py egg_info failed with error code 1 in /tmp/pip-o3Df4R-build
```

Thanks!

**Comment by passiweinberger** [comment]
Did you try a sudo python setup.py install --user
Not ideal, but that worked for me...

**Comment by dducro** [comment]
Thanks for the suggestion. Unfortunately it gives the same errors.

**Comment by passiweinberger** [comment]
Hm :/ Do you use Vagrant? Doublechecked the Vagrantfile? As you're running U 13.04; you could also download and try the click'n run image?
This is weired.  I had exactly  (I think) the se error on 14.04 and sudo did the job :$

**Comment by dducro** [comment]
I'm using the "click'n run image" but that has a very old version of nupic. So I updated all the packages / repos as I stated above.
I think there is something wrong with gcc version 4.8.1, I maybe installed something incorrectly..?

**Comment by passiweinberger** [comment]
Hard to say from here ;) 
tried gcc4.9 ? I have no idea why it's not working honestly, try around a bit :)

**Comment by passiweinberger** [comment]
Or check if the location is in PATH and PYTHONPATH; maybe use the develop comand for setup.py; or use sudo -H pip ... ? this is nasty :/

**Comment by dducro** [comment]
#2102 "The only work-around is to install GCC 4.8. Sorry."

**Comment by passiweinberger** [comment]
Ok Sry :+1: And you have sufficient space for building etc. ?

**Comment by dducro** [comment]
I got it to build using clang in stead of gcc, I ran:
    sudo CC=clang CXX=clang++ python setup.py install --user

**Comment by passiweinberger** [comment]
(Y)

**Comment by breznak** [comment]
@dducro can we close now that you (partially) fixed that by using clang? I'll try to update the VM image and test with gcc 4.8

**Comment by dducro** [comment]
Hey,
Yes it can be closed, thanks!
