### ISSUE TITLE
not possible to compute and get predictedActiveCells with TM `tm_py` implementation

### ISSUE THREAD

**Issue by marionleborgne** [numenta/nupic#2341]
I am using the network API and `temporalMemoryRegion.setParameter("computePredictedActiveCellIndices", True)` [1] fails when using the `tm_py` TM implementation. [2]

See stacktrace [3]

But then, even after bypassing this parameter - so that I enforce the computation of predictedActiveCells - the computation of predictiveActiveCells still fails. See stacktrace [4]

So I ended up having to get the predictedActiveCells directly from the tmInstance [5]. But ideally, we want to get this to work using the network API, and not this workaround :grin: 

---
[1] https://github.com/numenta/nupic.research/blob/ab3bc24e1523d604723bb872ff2e6ac2b0dc8f53/classification/classification_network.py#L222-L224

[2] https://github.com/numenta/nupic.research/blob/ab3bc24e1523d604723bb872ff2e6ac2b0dc8f53/classification/classification_network.py#L63

[3] stacktrace:
```
Traceback (most recent call last):
  File "/Users/mleborgne/_git/nupic.research/classification/classify_active_cells.py", line 219, in <module>
    run(network, NUM_RECORDS, partitions, outFile)
  File "/Users/mleborgne/_git/nupic.research/classification/classify_active_cells.py", line 90, in run
    net.run(1)
  File "/Users/mleborgne/_git/nupic/nupic/engine/__init__.py", line 669, in run
    engine.Network.run(self, n)
  File "/Users/mleborgne/_git/nupic/nupic/bindings/engine_internal.py", line 1146, in run
    return _engine_internal.Network_run(self, *args, **kwargs)
  File "/Users/mleborgne/_git/nupic/nupic/regions/TPRegion.py", line 464, in compute
    self._compute(inputs, outputs)
  File "/Users/mleborgne/_git/nupic/nupic/regions/TPRegion.py", line 525, in _compute
    activeState = self._tfdr.getActiveState().reshape(-1).astype('float32')
AttributeError: 'TPShim' object has no attribute 'getActiveState'
```

[4] stacktrace:
```
Traceback (most recent call last):
  File "/Users/mleborgne/_git/nupic.research/classification/classify_active_cells.py", line 219, in <module>
    run(network, NUM_RECORDS, partitions, outFile)
  File "/Users/mleborgne/_git/nupic.research/classification/classify_active_cells.py", line 90, in run
    net.run(1)
  File "/Users/mleborgne/_git/nupic/nupic/engine/__init__.py", line 669, in run
    engine.Network.run(self, n)
  File "/Users/mleborgne/_git/nupic/nupic/bindings/engine_internal.py", line 1146, in run
    return _engine_internal.Network_run(self, *args, **kwargs)
  File "/Users/mleborgne/_git/nupic/nupic/regions/TPRegion.py", line 464, in compute
    self._compute(inputs, outputs)
  File "/Users/mleborgne/_git/nupic/nupic/regions/TPRegion.py", line 525, in _compute
    activeState = self._tfdr.getActiveState().reshape(-1).astype('float32')
AttributeError: 'TPShim' object has no attribute 'getActiveState'
```

[5] https://github.com/numenta/nupic.research/blob/ab3bc24e1523d604723bb872ff2e6ac2b0dc8f53/classification/classify_active_cells.py#L147-L152

**Comment by rhyolight** [comment]
@chetan51 Did you see this? Thoughts?

**Comment by chetan51** [comment]
We can try implementing the method `getActiveState` in the `TPShim` class, getting the active cells from the TP and returning them as a numpy array.

**Comment by marionleborgne** [comment]
As a workaround, to get the `tm_py` to work, I replaced [1] by [2] in `TPRegion.py`

[1] original code https://github.com/numenta/nupic/blob/master/nupic/regions/TPRegion.py#L523-L533
```
    if self.computePredictedActiveCellIndices:
      # Reshape so we are dealing with 1D arrays
      activeState = self._tfdr.getActiveState().reshape(-1).astype('float32')
      predictedState = self._tfdr.getPredictedState().reshape(-1).astype('float32')
      activeIndices = numpy.where(activeState != 0)[0]
      predictedIndices= numpy.where(predictedState != 0)[0]
      predictedActiveIndices = numpy.intersect1d(activeIndices, predictedIndices)
      outputs["activeCells"].fill(0)
      outputs["activeCells"][activeIndices] = 1
      outputs["predictedActiveCells"].fill(0)
      outputs["predictedActiveCells"][predictedActiveIndices] = 1
```

[2] workaround
```
    if self.computePredictedActiveCellIndices:
      activeIndices = self._tfdr.activeCells
      predictedIndices = self._tfdr.predictiveCells
      predictedActiveIndices = numpy.intersect1d(activeIndices, predictedIndices)
      outputs["activeCells"].fill(0)
      for i in activeIndices:
        outputs["activeCells"][i] = 1
      outputs["predictedActiveCells"].fill(0)
      for i in predictedActiveIndices:
        outputs["predictedActiveCells"][i] = 1
```

**Comment by chetan51** [comment]
@marionleborgne Try putting the following function in the `TPShim` class:

	def getActiveState(self):
	  activeState = numpy.zeros(self.numberOfCells())
	  for c in self.activeCells:
	  	activeState[i] = 1
	  return activeState

And similar for `getPredictedState()`.

**Comment by marionleborgne** [comment]
@chetan51 Thanks! it worked (with a few minor tweaks). Here is what I added in `TPShim`:

```
  def getActiveState(self):
    activeState = numpy.zeros(self.numberOfCells())
    activeState[self.getCellIndices(self.activeCells)] = 1
    return activeState
  
  
  def getPredictedState(self):
    predictedState = numpy.zeros(self.numberOfCells())
    predictedState[self.getCellIndices(self.predictiveCells)] = 1
    return predictedState
```
