### ISSUE TITLE
binary install fails: export NUPIC_CORE_RELEASE

### ISSUE THREAD

**Issue by breznak** [numenta/nupic#2543]
`pip install nupic` on ubuntu is failing: 

```
Downloading/unpacking nupic.bindings==0.1.5 (from nupic)
  Downloading nupic.bindings-0.1.5.tar.gz (589kB): 589kB downloaded
  Running setup.py (path:/tmp/pip_build_root/nupic.bindings/setup.py) egg_info for package nupic.bindings
    Python Bindings directory: /tmp/pip_build_root/nupic.bindings
    NUMPY VERSION: 1.9.2
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/nupic.bindings/setup.py", line 534, in <module>
        raise Exception("Must provide path to nupic core release. export NUPIC_CORE_RELEASE=<path>")
    Exception: Must provide path to nupic core release. export NUPIC_CORE_RELEASE=<path>
    Complete output from command python setup.py egg_info:
    Python Bindings directory: /tmp/pip_build_root/nupic.bindings
NUMPY VERSION: 1.9.2
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/tmp/pip_build_root/nupic.bindings/setup.py", line 534, in <module>
    raise Exception("Must provide path to nupic core release. export NUPIC_CORE_RELEASE=<path>")
Exception: Must provide path to nupic core release. export NUPIC_CORE_RELEASE=<path>
```

* Exception: Must provide path to nupic core release. export NUPIC_CORE_RELEASE=<path>
* also, I had to manually pip install numpy (nupic.bindings did not pull it in)

**Comment by rhyolight** [comment]
I just released late last night. Can you try again now?

**Comment by loretoparisi** [comment]
I have tried to install nupic and I have the same issue on the latest package

```bash
Downloading/unpacking nupic.bindings==0.1.5 (from nupic)
  Downloading nupic.bindings-0.1.5.tar.gz (589kB): 589kB downloaded
  Running setup.py egg_info for package nupic.bindings
    Python Bindings directory: /private/tmp/pip_build_root/nupic.bindings
    NUMPY VERSION: 1.8.0rc1
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/private/tmp/pip_build_root/nupic.bindings/setup.py", line 534, in <module>
        raise Exception("Must provide path to nupic core release. export NUPIC_CORE_RELEASE=<path>")
    Exception: Must provide path to nupic core release. export NUPIC_CORE_RELEASE=<path>
    Complete output from command python setup.py egg_info:
    Python Bindings directory: /private/tmp/pip_build_root/nupic.bindings

NUMPY VERSION: 1.8.0rc1

Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/private/tmp/pip_build_root/nupic.bindings/setup.py", line 534, in <module>

    raise Exception("Must provide path to nupic core release. export NUPIC_CORE_RELEASE=<path>")

Exception: Must provide path to nupic core release. export NUPIC_CORE_RELEASE=<path>

**Comment by rhyolight** [comment]
I don't understand how this could be happening unless you still have an old version of NuPIC bindings installed on your system. Can you try running the uninstall command several times ?

**Comment by codedhard** [comment]
tar zxf nupic.bindings-0.1.5.tar.gz
cd nupic.bindings-0.1.5
sudo python setup.py install

Then try installing nupic.

**Comment by loretoparisi** [comment]
Trying several times I came out with

```Shell
macbookproloreto:unittest admin$ pip uninstall nupic.bindings -y
Cannot uninstall requirement nupic.bindings, not installed
Storing complete log in /Users/admin/Library/Logs/pip.log
macbookproloreto:unittest admin$ pip uninstall nupic -y
Cannot uninstall requirement nupic, not installed
```
and the same error again.

**Comment by loretoparisi** [comment]
@codedhard If I try to install nupic.bindings before nupic I get

```Shell
macbookproloreto:unittest admin$ pip install nupic.bindings
Downloading/unpacking nupic.bindings
  Downloading nupic.bindings-0.1.5.tar.gz (589kB): 589kB downloaded
  Running setup.py egg_info for package nupic.bindings
```
and then


```Shell
Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/private/var/folders/mm/qbx_84b57sgf_f9j0cxmj__r0000gn/T/pip_build_admin/nupic.bindings/setup.py", line 538, in <module>

    raise Exception("{} does not exist".format(nupicCoreReleaseDir))

Exception: /Library/Python/2.7/site-packages/nupic does not exist
```

where ```/Library/Python/2.7/site-packages/``` are supposed to go Python packages.
Is there a circular dependency between ```nupic``` and ```nupic.bindings``` somewhere?

**Comment by codedhard** [comment]
@loretoparisi
I was wrong.

Download from https://github.com/numenta/nupic  zip archive.

unzip nupic-master
cd nupic-master
sudo python setup.py install

**Comment by rhyolight** [comment]
@breznak Is this still failing for you, too?

**Comment by rhyolight** [comment]
Guys, you should not need to manually install `nupic.bindings` if you are building from source. The nupic build process will install it for you. So, hopefully all you need is to run `python setup.py install [--user]` from the nupic checkout directory. 

If you are installing from binary on Linux, you need to manually install the `nupic.bindings` binary like this:

    pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/releases/nupic.bindings/nupic.bindings-0.1.5-cp27-none-linux_x86_64.whl

Then you can `pip install nupic`. The reason you have to do this for Linux is [explained here](https://github.com/numenta/nupic#install-linux).

**Comment by loretoparisi** [comment]
@codedhard thank you, I have installed compiling from the sources!!!

```python
>>> import nupic, sys
>>> print 'nupic' in sys.modules
True
```

@rhyolight no way to install from pip, but at least now I can work :+1: 

Thanks a lot.

**Comment by rhyolight** [comment]
@loretoparisi Ok, great! Thank you for the reports.

**Comment by rhyolight** [comment]
@codedhard And thanks for your help, too. :smile:

**Comment by felippemr** [comment]
When I try to install I still get the error:
Exception: Must provide path to nupic core release. export NUPIC_CORE_RELEASE=<path>

**Comment by rcrowder** [comment]
I face the same error when trying to convince NuPIC setup.py to download a custom NuPIC.Core repo. I always thought it maybe down to the execfile used to call the second setup.py in bindings. The environment it exec's the bindings/py/setup.py file looks quite empty. For me, to move forward I had to modify the setup to use ```nupicCoreReleaseDir = PY_BINDINGS + '/../..'```, but that is overly complicated for a user to do.. Starting to hunt down an alternative..

**Comment by rhyolight** [comment]
@breznak Can you try to uninstall NuPIC entirely and reinstall from latest source? I don't think this error should be happening unless there is an old version on your system. But I'm still getting reports of it so I just want to make sure it is not something more sinister.

**Comment by rhyolight** [comment]
@breznak I think I know what might be the problem here, see https://github.com/numenta/nupic/issues/2570#issuecomment-141189212. We'll continue the discussion here if you have any input.

**Comment by rhyolight** [comment]
@felippemr We just releases NuPIC 0.3.1. Can you please try to uninstall and reinstall for an upgrade [per these instructions](http://lists.numenta.org/pipermail/nupic_lists.numenta.org/2015-September/011719.html)? Thanks.

**Comment by rhyolight** [comment]
I will likely close this issue if I don't hear back from @breznak or @felippemr by Tuesday.

**Comment by felippemr** [comment]
Thank you @rhyolight, I followed your instructions but the error persists:

```
(nupic_lab)nupic_lab$ pip uninstall nupic nupic.bindings -y
Cannot uninstall requirement nupic, not installed
Storing debug log for failure in /Users/felippe.gestec/.pip/pip.log
(nupic_lab)nupic_lab$ pip freeze
numpy==1.9.2
wsgiref==0.1.2
(nupic_lab)nupic_lab$ pip install nupic
Downloading/unpacking nupic
  Downloading nupic-0.3.1-py2-none-any.whl (5.3MB): 5.3MB downloaded
Downloading/unpacking PyMySQL==0.6.2 (from nupic)
  Downloading PyMySQL-0.6.2-py2.py3-none-any.whl (63kB): 63kB downloaded
Requirement already satisfied (use --upgrade to upgrade): numpy==1.9.2 in /Users/felippe.gestec/.virtualenvs/nupic_lab/lib/python2.7/site-packages (from nupic)
Downloading/unpacking nupic.bindings==0.2 (from nupic)
  Downloading nupic.bindings-0.2.tar.gz (593kB): 593kB downloaded
  Running setup.py (path:/Users/felippe.gestec/.virtualenvs/nupic_lab/build/nupic.bindings/setup.py) egg_info for package nupic.bindings
    Python Bindings directory: /Users/felippe.gestec/.virtualenvs/nupic_lab/build/nupic.bindings
    NUMPY VERSION: 1.9.2
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/Users/felippe.gestec/.virtualenvs/nupic_lab/build/nupic.bindings/setup.py", line 534, in <module>
        raise Exception("Must provide nupic core release directory. --nupic-core-dir")
    Exception: Must provide nupic core release directory. --nupic-core-dir
    Complete output from command python setup.py egg_info:
    Python Bindings directory: /Users/felippe.gestec/.virtualenvs/nupic_lab/build/nupic.bindings

NUMPY VERSION: 1.9.2

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/Users/felippe.gestec/.virtualenvs/nupic_lab/build/nupic.bindings/setup.py", line 534, in <module>

    raise Exception("Must provide nupic core release directory. --nupic-core-dir")

Exception: Must provide nupic core release directory. --nupic-core-dir

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /Users/felippe.gestec/.virtualenvs/nupic_lab/build/nupic.bindings
Storing debug log for failure in /Users/felippe.gestec/.pip/pip.log
(nupic_lab)nupic_lab$ pip uninstall nupic nupic.bindings -y
Cannot uninstall requirement nupic, not installed
Storing debug log for failure in /Users/felippe.gestec/.pip/pip.log

```

**Comment by rhyolight** [comment]
@felippemr Just yesterday, we [released NuPIC 0.3.2](https://github.com/numenta/nupic/releases/tag/0.3.2). Please re-run the instructions to uninstall and re-install NuPIC again? Sorry for all the trouble.

**Comment by felippemr** [comment]
I tried, but:

```
~$ mkvirtualenv test_nupic
New python executable in test_nupic/bin/python2.7
Also creating executable in test_nupic/bin/python
Installing setuptools, pip...done.
(test_nupic)~$ pip install numpy
Downloading/unpacking numpy
  Downloading numpy-1.9.3-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.6MB): 3.6MB downloaded
Installing collected packages: numpy
Successfully installed numpy
Cleaning up...
(test_nupic)~$ pip install nupic
Downloading/unpacking nupic
  Downloading nupic-0.3.2-py2-none-any.whl (5.0MB): 5.0MB downloaded
Downloading/unpacking PyMySQL==0.6.2 (from nupic)
  Downloading PyMySQL-0.6.2-py2.py3-none-any.whl (63kB): 63kB downloaded
Downloading/unpacking nupic.bindings==0.2.1 (from nupic)
  Downloading nupic.bindings-0.2.1.tar.gz (593kB): 593kB downloaded
  Running setup.py (path:/Users/felippe.gestec/.virtualenvs/test_nupic/build/nupic.bindings/setup.py) egg_info for package nupic.bindings
    Python Bindings directory: /Users/felippe.gestec/.virtualenvs/test_nupic/build/nupic.bindings
    NUMPY VERSION: 1.9.3
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/Users/felippe.gestec/.virtualenvs/test_nupic/build/nupic.bindings/setup.py", line 534, in <module>
        raise Exception("Must provide nupic core release directory. --nupic-core-dir")
    Exception: Must provide nupic core release directory. --nupic-core-dir
    Complete output from command python setup.py egg_info:
    Python Bindings directory: /Users/felippe.gestec/.virtualenvs/test_nupic/build/nupic.bindings

NUMPY VERSION: 1.9.3

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/Users/felippe.gestec/.virtualenvs/test_nupic/build/nupic.bindings/setup.py", line 534, in <module>

    raise Exception("Must provide nupic core release directory. --nupic-core-dir")

Exception: Must provide nupic core release directory. --nupic-core-dir

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /Users/felippe.gestec/.virtualenvs/test_nupic/build/nupic.bindings
Storing debug log for failure in /Users/felippe.gestec/.pip/pip.log
```

**Comment by rhyolight** [comment]
Here is [another report of this error](http://lists.numenta.org/pipermail/nupic_lists.numenta.org/2015-September/011741.html) on OS X.

**Comment by rhyolight** [comment]
We think this is a `nupic.core` issue. Closing this in favor of https://github.com/numenta/nupic.core/issues/619.

**Comment by breznak** [comment]
@rhyolight the binary install from wheel for nupic.core and pip for nupic works for me now. :+1:

**Comment by rhyolight** [comment]
@breznak that's a relief, thanks.
