### ISSUE TITLE
nupic.bindings source release not suitable for installation

### ISSUE THREAD

**Issue by oxtopus** [numenta/nupic#2595]
In a fresh environment without numpy installed, if you install a python project with `pip` that specifies `nupic.bindings` as a dependency, it will download the source release of `nupic.bindings` and then fail.  For example, when I try to install `nupic` in Ubuntu 14.04, I get the following excerpt:

```
  Downloading from URL https://pypi.python.org/packages/source/n/nupic.bindings/nupic.bindings-0.2.1.tar.gz#md5=530c8ac0dc200ce4430c37b6cb28dfd1 (from https://pypi.python.org/simple/nupic.bindings/)
  Running setup.py (path:/tmp/pip-build-Zr6dqL/nupic.bindings/setup.py) egg_info for package nupic.bindings
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-Zr6dqL/nupic.bindings/setup.py", line 24, in <module>
        import numpy
    ImportError: No module named numpy
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-Zr6dqL/nupic.bindings/setup.py", line 24, in <module>
        import numpy
    ImportError: No module named numpy
    
    ----------------------------------------
Cleaning up...
  Removing source in /tmp/pip-build-Zr6dqL/pytest-cov
  Removing source in /tmp/pip-build-Zr6dqL/numpy
  Removing source in /tmp/pip-build-Zr6dqL/asteval
  Removing source in /tmp/pip-build-Zr6dqL/prettytable
  Removing source in /tmp/pip-build-Zr6dqL/pytest
  Removing source in /tmp/pip-build-Zr6dqL/psutil
  Removing source in /tmp/pip-build-Zr6dqL/pycapnp
  Removing source in /tmp/pip-build-Zr6dqL/PyYAML
  Removing source in /tmp/pip-build-Zr6dqL/pytest-xdist
  Removing source in /tmp/pip-build-Zr6dqL/unittest2
  Removing source in /tmp/pip-build-Zr6dqL/pyproj
  Removing source in /tmp/pip-build-Zr6dqL/DBUtils
  Removing source in /tmp/pip-build-Zr6dqL/python-dateutil
  Removing source in /tmp/pip-build-Zr6dqL/pillow
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Zr6dqL/nupic.bindings
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 305, in run
    wb.build(autobuilding=True)
  File "/usr/local/lib/python2.7/dist-packages/pip/wheel.py", line 705, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 505, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 123, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 410, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 733, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-Zr6dqL/nupic.bindings
```

The problem can be replicated by downloading the tarball directly and running `setup.py`:

```
root@6c0acbb5e6e8:~# wget https://pypi.python.org/packages/source/n/nupic.bindings/nupic.bindings-0.2.1.tar.gz
--2015-09-23 16:10:16--  https://pypi.python.org/packages/source/n/nupic.bindings/nupic.bindings-0.2.1.tar.gz
Resolving pypi.python.org (pypi.python.org)... 23.235.47.223, 23.235.47.223
Connecting to pypi.python.org (pypi.python.org)|23.235.47.223|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 593868 (580K) [application/octet-stream]
Saving to: 'nupic.bindings-0.2.1.tar.gz'

100%[====================================================================================================================================================================================================================================================================================>] 593,868     --.-K/s   in 0.1s    

2015-09-23 16:10:17 (4.77 MB/s) - 'nupic.bindings-0.2.1.tar.gz' saved [593868/593868]
root@6c0acbb5e6e8:~# tar xzvf nupic.bindings-0.2.1.tar.gz 
nupic.bindings-0.2.1/
nupic.bindings-0.2.1/nupic/
nupic.bindings-0.2.1/nupic/bindings/
nupic.bindings-0.2.1/nupic/bindings/regions/
nupic.bindings-0.2.1/nupic/bindings/regions/PyRegion.py
nupic.bindings-0.2.1/nupic/bindings/regions/TestNode.py
nupic.bindings-0.2.1/nupic/bindings/regions/__init__.py
nupic.bindings-0.2.1/nupic/bindings/tests/
nupic.bindings-0.2.1/nupic/bindings/tests/__init__.py
nupic.bindings-0.2.1/nupic/bindings/tests/pyregion_test.py
nupic.bindings-0.2.1/nupic/bindings/PySparseTensor.cpp
nupic.bindings-0.2.1/nupic/bindings/__init__.py
nupic.bindings-0.2.1/nupic/bindings/algorithms.py
nupic.bindings-0.2.1/nupic/bindings/algorithms_wrap.cxx
nupic.bindings-0.2.1/nupic/bindings/engine_internal.py
nupic.bindings-0.2.1/nupic/bindings/engine_internal_wrap.cxx
nupic.bindings-0.2.1/nupic/bindings/math.py
nupic.bindings-0.2.1/nupic/bindings/math_wrap.cxx
nupic.bindings-0.2.1/nupic/proto/
nupic.bindings-0.2.1/nupic/proto/BitHistory.capnp
nupic.bindings-0.2.1/nupic/proto/ClaClassifier.capnp
nupic.bindings-0.2.1/nupic/proto/ConnectionsProto.capnp
nupic.bindings-0.2.1/nupic/proto/LinkProto.capnp
nupic.bindings-0.2.1/nupic/proto/Map.capnp
nupic.bindings-0.2.1/nupic/proto/NetworkProto.capnp
nupic.bindings-0.2.1/nupic/proto/RandomProto.capnp
nupic.bindings-0.2.1/nupic/proto/RegionProto.capnp
nupic.bindings-0.2.1/nupic/proto/SparseBinaryMatrixProto.capnp
nupic.bindings-0.2.1/nupic/proto/SparseMatrixProto.capnp
nupic.bindings-0.2.1/nupic/proto/SpatialPoolerProto.capnp
nupic.bindings-0.2.1/nupic/proto/TemporalMemoryProto.capnp
nupic.bindings-0.2.1/nupic/proto/TemporalMemoryV1.capnp
nupic.bindings-0.2.1/nupic/proto/TestNodeProto.capnp
nupic.bindings-0.2.1/nupic/proto/VectorFileSensorProto.capnp
nupic.bindings-0.2.1/nupic/proto/__init__.py
nupic.bindings-0.2.1/nupic/__init__.py
nupic.bindings-0.2.1/nupic.bindings.egg-info/
nupic.bindings-0.2.1/nupic.bindings.egg-info/PKG-INFO
nupic.bindings-0.2.1/nupic.bindings.egg-info/SOURCES.txt
nupic.bindings-0.2.1/nupic.bindings.egg-info/dependency_links.txt
nupic.bindings-0.2.1/nupic.bindings.egg-info/namespace_packages.txt
nupic.bindings-0.2.1/nupic.bindings.egg-info/not-zip-safe
nupic.bindings-0.2.1/nupic.bindings.egg-info/requires.txt
nupic.bindings-0.2.1/nupic.bindings.egg-info/top_level.txt
nupic.bindings-0.2.1/setup.py
nupic.bindings-0.2.1/PKG-INFO
nupic.bindings-0.2.1/setup.cfg
root@6c0acbb5e6e8:~# cd nupic.bindings-0.2.1
root@6c0acbb5e6e8:~/nupic.bindings-0.2.1# python setup.py --help
Traceback (most recent call last):
  File "setup.py", line 24, in <module>
    import numpy
ImportError: No module named numpy
```

**Comment by oxtopus** [comment]
Meant to create this in numenta/nupic.core
