### ISSUE TITLE
CLAClassifier bugreport

### ISSUE THREAD

**Issue by codedhard** [numenta/nupic#2688]
https://github.com/numenta/nupic/blob/master/examples/network/hierarchy_network_demo.py
'implementation': 'py'

Writing output to: hierarchy-demo-output.csv
Traceback (most recent call last):
  File "hierarchy_network_demo.py", line 372, in <module>
    runDemo()
  File "hierarchy_network_demo.py", line 366, in runDemo
    runNetwork(network, numRecords, writer)
  File "hierarchy_network_demo.py", line 306, in runNetwork
    network.run(1)
  File "/usr/local/lib/python2.7/dist-packages/nupic-0.3.6.dev0-py2.7.egg/nupic/engine/__init__.py", line 666, in run
    engine.Network.run(self, n)
  File "/usr/local/lib/python2.7/dist-packages/nupic.bindings-0.2.2-py2.7-linux-x86_64.egg/nupic/bindings/engine_internal.py", line 1146, in run
    return _engine_internal.Network_run(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nupic-0.3.6.dev0-py2.7.egg/nupic/regions/CLAClassifierRegion.py", line 289, in compute
    categories = [category for category in inputs["categoryIn"]
KeyError: 'categoryIn'

**Comment by rhyolight** [comment]
@codedhard So when you change back to `'implementation': 'cpp'` it works fine?

Why do you want to use the python implementation (just curious)?

**Comment by codedhard** [comment]
@rhyolight No does not work with `'implementation': 'cpp'` the result is "Killed" and nothing more.

Just for debugging purpose because the other implementation was not giving any "errors" other then "Killed".

**Comment by rhyolight** [comment]
@codedhard Can you provide more info?

- operating system
- NuPIC installation method (pip install or local compile?)
- exact command you are running and the exact console output.

Thanks.

**Comment by rcrowder** [comment]
This is a nupic.core issue somewhere within the engine region interface. Same occurs with py and cpp CLA Classifier factory output. Without recreating a C++ version of the hierarchy_network_demo it's tricky to work out in PyCharm what happens in the Core. The simplest way to recreate can be;

Spin up a new Ubuntu 14.02 (LTS) VM. It comes with Python 2.7.6 and GCC 4.8.x

Add Python dependencies
- sudo apt-get build-dep python2.7

Pip not installed.. following installs 1.5.4
- sudo apt-get install python-pip

- pip list
shows wheel==0.24.0

pip install numpy fails (no Python.h)
needs;
- sudo apt-get install python-dev
then;
- sudo pip install numpy
(installs 1.10.1)

Install bindings and nupic (sudo added to get around permissions)
- sudo pip install https://s3-us-west-2.amazonaws.com/artifacts.numenta.org/numenta/nupic.core/releases/nupic.bindings/nupic.bindings-0.2.2-cp27-none-linux_x86_64.whl
- sudo pip install nupic

- sudo apt-get install git
- git clone https://github.com/numenta/nupic.git
- cd nupic
- python examples/network/hierarchy_network_demo.py  
Creating network  
Running network  
Writing output to: examples/network/hierarchy-demo-output.csv  
Traceback (most recent call last):  
  File "examples/network/hierarchy_network_demo.py", line 368, in <module>
    runDemo()  
  File "examples/network/hierarchy_network_demo.py", line 362, in runDemo
    runNetwork(network, numRecords, writer)  
  File "examples/network/hierarchy_network_demo.py", line 305, in runNetwork
    network.run(1)  
  File "/usr/local/lib/python2.7/dist-packages/nupic/engine/__init__.py", line 666, in run
    engine.Network.run(self, n)  
  File "/usr/local/lib/python2.7/dist-packages/nupic/bindings/engine_internal.py", line 1146, in run
    return _engine_internal.Network_run(self, *args, **kwargs)  
  File "/usr/local/lib/python2.7/dist-packages/nupic/regions/CLAClassifierRegion.py", line 289, in compute  
    categories = [category for category in inputs["categoryIn"]  
KeyError: 'categoryIn'

**Comment by aoman89757** [comment]
I got the exactly same issue when using SDRCategoryEncoder :(
BTW, I'm using docker version nupic

**Comment by rhyolight** [comment]
FYI @ywcui1990 Please read above.
