### ISSUE TITLE
Can't run the OHG tutorial.

### ISSUE THREAD

**Issue by alsmith** [numenta/nupic#2732]
Try as I might, I haven't been able to even get the hot gym tutorial going, and I'm out of ideas with how to fix it as the error message that comes back is not particularly informative... any clues would be much apprecated!

Steps to repro:

```
% git clone https://github.com/numenta/nupic.git
% cd nupic/examples/opf/clients/hotgym/prediction/one_gym
% ./swarm.py
./swarm.py
This script runs a swarm on the input data (rec-center-hourly.csv) and
creates a model parameters file in the `model_params` directory containing
the best model found by the swarm. Dumps a bunch of crud to stdout because
that is just what swarming does at this point. You really don't need to
pay any attention to it.

=================================================
= Swarming on rec-center-hourly data...
= Medium swarm. Sit back and relax, this could take awhile.
=================================================
Generating experiment files in directory: /u/ajs/nupic/examples/opf/clients/hotgym/prediction/one_gym/swarm...
Writing  313 lines...
Writing  114 lines...
done.
None
Successfully submitted new HyperSearch job, jobID=1014
Evaluated 0 models
HyperSearch finished!
Worker completion message: None

Results from all experiments:
----------------------------------------------------------------
Generating experiment files in directory: /tmp/tmpUWNeZJ...
Writing  313 lines...
Writing  114 lines...
done.
None
json.loads(jobInfo.results) raised an exception.  Here is some info to help with debugging:
jobInfo:  _jobInfoNamedTuple(jobId=1014, client=u'GRP', clientInfo=u'', clientKey=u'', cmdLine=u'$HYPERSEARCH', params=u'{"hsVersion": "v2", "maxModels": null, "persistentJobGUID": "40036c4a-8300-11e5-bddb-e8de27a798c5", "useTerminators": false, "description": {"includedFields": [{"fieldName": "timestamp", "fieldType": "datetime"}, {"maxValue": 53.0, "fieldName": "kw_energy_consumption", "fieldType": "float", "minValue": 0.0}], "streamDef": {"info": "kw_energy_consumption", "version": 1, "streams": [{"info": "Rec Center", "source": "file://rec-center-hourly.csv", "columns": ["*"]}]}, "inferenceType": "TemporalMultiStep", "inferenceArgs": {"predictionSteps": [1], "predictedField": "kw_energy_consumption"}, "iterationCount": -1, "swarmSize": "medium"}}', jobHash="@\x03tV\x83\x00\x11\xe5\xbd\xdb\xe8\xde'\xa7\x98\xc5", status=u'notStarted', completionReason=None, completionMsg=None, workerCompletionReason=u'success', workerCompletionMsg=None, cancel=0, startTime=None, endTime=None, results=None, engJobType=u'hypersearch', minimumWorkers=1, maximumWorkers=4, priority=0, engAllocateNewWorkers=1, engUntendedDeadWorkers=0, numFailedWorkers=0, lastFailedWorkerErrorMsg=None, engCleaningStatus=u'notdone', genBaseDescription=None, genPermutations=None, engLastUpdateTime=datetime.datetime(2015, 11, 4, 14, 28), engCjmConnId=None, engWorkerState=None, engStatus=None, engModelMilestones=None)
jobInfo.results:  None
EXCEPTION:  expected string or buffer
Traceback (most recent call last):
  File "./swarm.py", line 109, in <module>
    swarm(INPUT_FILE)
  File "./swarm.py", line 101, in swarm
    modelParams = swarmForBestModelParams(SWARM_DESCRIPTION, name)
  File "./swarm.py", line 78, in swarmForBestModelParams
    verbosity=0
  File "/usr/lib/python2.7/site-packages/nupic-0.3.5-py2.7.egg/nupic/swarming/permutations_runner.py", line 277, in runWithConfig
    return _runAction(runOptions)
  File "/usr/lib/python2.7/site-packages/nupic-0.3.5-py2.7.egg/nupic/swarming/permutations_runner.py", line 218, in _runAction
    returnValue = _runHyperSearch(runOptions)
  File "/usr/lib/python2.7/site-packages/nupic-0.3.5-py2.7.egg/nupic/swarming/permutations_runner.py", line 161, in _runHyperSearch
    metricsKeys=search.getDiscoveredMetricsKeys())
  File "/usr/lib/python2.7/site-packages/nupic-0.3.5-py2.7.egg/nupic/swarming/permutations_runner.py", line 826, in generateReport
    results = json.loads(jobInfo.results)
  File "/usr/lib/python2.7/site-packages/nupic-0.3.5-py2.7.egg/nupic/swarming/object_json.py", line 163, in loads
    json.loads(s, object_hook=objectDecoderHook, **kwargs))
  File "/usr/lib/python2.7/json/__init__.py", line 351, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
% 
```

The database connection works out fine...

```
% python $HOME/nupic/examples/swarm/test_db.py

This script will validate that your MySQL is setup correctly for NuPIC.
MySQL is required for NuPIC swarming. The settings are defined in a
configuration file found in $NUPIC/src/nupic/support/nupic-default.xml
Out of the box those settings contain MySQL's default access
credentials.

The nupic-default.xml can be duplicated to define user specific changes,
calling the copied file $NUPIC/src/nupic/support/nupic-site.xml
Refer to the nupic-default.xml for additional instructions.

Defaults: localhost, 3306, root, no password

Retrieved the following settings from NuPIC configuration:
    host   :     localhost
    port   :     3306
    user   :     nupic
    passwd :     <not saying>

Connection successful!!
% 
```

**Comment by rhyolight** [comment]
Just to be confident that NuPIC is installed correctly, can you try to run this example?

    cd $HOME/nupic/examples/opf/clients/hotgym/simple
    python hotgym.py

You should see something like this:

```
INFO:__main__:After 100 records, 1-step altMAPE=36.179900
INFO:__main__:After 200 records, 1-step altMAPE=26.685081
INFO:__main__:After 300 records, 1-step altMAPE=23.875171
INFO:__main__:After 400 records, 1-step altMAPE=22.685887
INFO:__main__:After 500 records, 1-step altMAPE=21.781040
INFO:__main__:After 600 records, 1-step altMAPE=21.820665
INFO:__main__:After 700 records, 1-step altMAPE=21.479866
INFO:__main__:After 800 records, 1-step altMAPE=21.638929
INFO:__main__:After 900 records, 1-step altMAPE=22.212049
INFO:__main__:After 1000 records, 1-step altMAPE=22.234222
```

**Comment by alsmith** [comment]
That works out fine... 

%~/nupic/examples/opf/clients/hotgym/simple> python hotgym.py
INFO:__main__:After 100 records, 1-step altMAPE=36.179900
INFO:__main__:After 200 records, 1-step altMAPE=26.685081
INFO:__main__:After 300 records, 1-step altMAPE=23.875171
INFO:__main__:After 400 records, 1-step altMAPE=22.685887
INFO:__main__:After 500 records, 1-step altMAPE=21.781040
INFO:__main__:After 600 records, 1-step altMAPE=21.820665
INFO:__main__:After 700 records, 1-step altMAPE=21.479866
INFO:__main__:After 800 records, 1-step altMAPE=21.638929
INFO:__main__:After 900 records, 1-step altMAPE=22.212049
INFO:__main__:After 1000 records, 1-step altMAPE=22.234222
%~/nupic/examples/opf/clients/hotgym/simple>

**Comment by rcrowder** [comment]
I've had this issue with some porting work recently. Will try and remember what solved it for me.

**Comment by ahaverty** [comment]
I am also hitting this exact issue with identical output as alsmith's first comment. hotgym.py also works fine for me.

**Comment by ahaverty** [comment]
Passed this particular issue, I think @rhyolight is right about an install issue, although I'm not sure why hotgym.py worked for us both?

Steps:
1. Clone the nupic project if you haven't already
`git clone https://github.com/numenta/nupic.git`
2. Export the nupic project location to a $NUPIC var
`export NUPIC=$PWD/nupic`
3. Change to the nupic dir
`cd $NUPIC`
4. Install Nupic as root
`sudo python setup.py install --user`
5. Try swarming again :thumbsup:

**Comment by rhyolight** [comment]
Hm, you should not have to install with sudo, as the --user option is
supposed to install into a non-system location. But you might need to
ensure that location pip installs python packages is discoverable by
python.

There are a lot of python problems on OS X. :/

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by Ivorforce** [comment]
Can confirm @ahaverty's solution worked, although I needed

sudo python2 setup.py install --user --prefix=

due to the changes in homebrew's python distros.

**Comment by Richardn2002** [comment]
I once encountered the problem and solved it by the solution above ,but recently i encountered it again and the solution didn't work.
After 2 days I find that deleting the 'capnp' folder from site-packages works. Write a note here for others to see :)
