### ISSUE TITLE
Error buliding pycapnp while installing nupic

### ISSUE THREAD

**Issue by jzlouis** [numenta/nupic#2790]
I am installing nupic via pip on 64bit Arch Linux. I get the following error when pip attempts to setup pycapnp.

    src/capnp/schema.c++:602:12: error: converting to 'bool' from 'std::nullptr_t' requires direct-initialization [-fpermissive]
         return nullptr;
                ^
    make: *** [src/capnp/schema.lo] Error 1
    make: *** Waiting for unfinished jobs....
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-b1QSf7/pycapnp/setup.py", line 168, in <module>
        'Topic :: Communications'],
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-b1QSf7/pycapnp/setup.py", line 112, in run
        build_libcapnp(bundle_dir, build_dir)
      File "buildutils/build.py", line 26, in build_libcapnp
        raise RuntimeError('Make failed')
    RuntimeError: Make failed

I did a little hunting around and it turns out this problem in was fixed in pycapnp 0.5.7. The problem is acknowledged here (https://github.com/jparyani/pycapnp/issues/70) for reference.

Is it possible to update to 0.5.7 without any issue?

Thanks,
Jenna

**Comment by rhyolight** [comment]
Why don't you first try running `pip install pycapnp==0.5.7`, then reinstall and see what happens?

**Comment by jzlouis** [comment]
I did that. The nupic install removes 0.5.7 in favor of 0.5.5 which is denoted as a dependency.

**Comment by rhyolight** [comment]
Ah, I see the dependency in [NuPIC's `setup.py`](https://github.com/numenta/nupic/blob/master/setup.py#L91) now. That seems strange. @scottpurdy @oxtopus why is this dependency in setup instead of `requirements.txt`?

Also @jzlouis if you are building from source, you could possibly just update the version in that file and try again?

**Comment by jzlouis** [comment]
Changing the dependency in setup.py and rebuilding from source works. I ran all of the unit tests and those appeared to complete successfully. I will let you know if I encounter any errant behavior using pycapnp 0.5.7.

**Comment by rhyolight** [comment]
Thanks! I guess we should think about updating @scottpurdy

**Comment by oxtopus** [comment]
@rhyolight pycapnp was removed from requirements.txt in https://github.com/numenta/nupic/commit/4e004530ac93228f3484bb616c6a600dc45ed94c, I believe due to an issue in getting nupic up and running in windows.  Updating nupic to specify 0.5.7 and any other references to previous versions should be done.

**Comment by MZamanMughal** [comment]
Still getting the same error :( on ubuntu.
