### ISSUE TITLE
Error when installing on Windows

### ISSUE THREAD

**Issue by DefinitlyEvil** [numenta/nupic#2926]
```
Collecting unittest2==0.5.1 (from nupic)
  Using cached unittest2-0.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\Davel\AppData\Local\Temp\pip-build-5dr27o4q\unittest2\setup.py", line 12, in <module>
        from unittest2 import __version__ as VERSION
      File "C:\Users\Davel\AppData\Local\Temp\pip-build-5dr27o4q\unittest2\unittest2\__init__.py", line 40, in <module>
        from unittest2.collector import collector
      File "C:\Users\Davel\AppData\Local\Temp\pip-build-5dr27o4q\unittest2\unittest2\collector.py", line 3, in <module>
        from unittest2.loader import defaultTestLoader
      File "C:\Users\Davel\AppData\Local\Temp\pip-build-5dr27o4q\unittest2\unittest2\loader.py", line 92
        except Exception, e:
                        ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Davel\AppData\Local\Temp\pip-build-5dr27o4q\unittest2
```

**Comment by rhyolight** [comment]
Can you provide more information? What steps did you take before you got this error? What command caused this error?

**Comment by rhyolight** [comment]
cc @rcrowder

**Comment by rcrowder** [comment]
That exception looks like a Python v3 error. Is that cached unittest2 package compatible with Python 2.7?

**Comment by DefinitlyEvil** [comment]
@rcrowder Yes, I got Python 3.5 installation. It seems it doesn't support 3.5 rather than 2.7. :P My bad. xD
