### ISSUE TITLE
Switching from "tm_py" to "tm_cpp" causes an error

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#3023]
The way I understand it, all temporal implementation options should have the exact same interface, so I should be able to switch between them from any client code without problems. But simply changing `tm_py` to `tm_cpp` does throw an error in the basic [river-runner](https://github.com/nupic-community/river-runner) utility.

To replicate...

```
git clone git@github.com:nupic-community/river-runner.git
cd river-runner
./run.py
```

This should run successfully and dump an output file into the working directory. Now edit the model params and [change line 86 to](https://github.com/nupic-community/river-runner/blob/master/model_params/anomaly_params.py#L86):

```
'temporalImp': 'tm_cpp',
```

Now run again:

```
./run.py
Traceback (most recent call last):
  File "./run.py", line 225, in <module>
    model = createModel(modelParams)
  File "./run.py", line 123, in createModel
    model = ModelFactory.create(modelParams)
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nupic/frameworks/opf/modelfactory.py", line 80, in create
    return modelClass(**modelConfig['modelParams'])
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nupic/frameworks/opf/clamodel.py", line 213, in __init__
    clParams, anomalyParams)
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nupic/frameworks/opf/clamodel.py", line 1184, in __createCLANetwork
    n.initialize()
  File "/Users/mtaylor/nta/nupic/src/nupic/engine/__init__.py", line 704, in initialize
    engine.Network.initialize(self, *args, **kwargs)
  File "/Users/mtaylor/Library/Python/2.7/lib/python/site-packages/nupic/bindings/engine_internal.py", line 1078, in initialize
    return _engine_internal.Network_initialize(self)
  File "/Users/mtaylor/nta/nupic/src/nupic/regions/TPRegion.py", line 431, in initialize
    **autoArgs)
  File "/Users/mtaylor/nta/nupic/src/nupic/research/TP_shim.py", line 81, in __init__
    seed=seed)
TypeError: __init__() got an unexpected keyword argument 'maxSegmentsPerCell'
```

**Comment by rhyolight** [comment]
cc @scottpurdy

**Comment by BoltzmannBrain** [comment]
@rhyolight what versions of nupic and nupic.core?

**Comment by rhyolight** [comment]
Latest of both.

**Comment by scottpurdy** [comment]
"tm_cpp" is only newly available. I'm not sure if this is broken as a result of final integration or broke after. We should get a test in to make sure each implementation works. But AFAIK nothing is using tm_cpp yet.

**Comment by BoltzmannBrain** [comment]
I'm unable to reproduce the error. This is the output for both `tm_py` and `tm_cpp`:
```
Preparing to output solar_radiation data to solar_radiation_out.csv
Done. Wrote 3000 data lines to solar_radiation.
```

**Comment by rhyolight** [comment]
Hm, that's weird. There is a chance I was not using the most recent
versions because I test installations so much. I will retry after building
off tip of master. Standby...

---------
Matt Taylor
OS Community Flag-Bearer
Numenta

**Comment by BoltzmannBrain** [comment]
@rhyolight standing by...
:smile:

**Comment by rhyolight** [comment]
Fixed. Sorry for the wait!
