### ISSUE TITLE
Error when following the "Instructions for running a swarm with Docker"

### ISSUE THREAD

**Issue by aoman89757** [numenta/nupic#3051]
Hi,
I'm trying to connect the nupic  with mysql by following the Instructions for running a swarm with Docker. But when doing the test, I got the error:

root@d173451e6433:/home/docker# ${NUPIC}/scripts/run_swarm.py $NUPIC/examples/swarm/simple/search_def.json --maxWorkers=4
Generating experiment files in directory: /usr/local/src/nupic/examples/swarm/simple...
Writing  313 lines...
Writing  114 lines...
done.
None
No handlers could be found for logger "nupic.database.ClientJobsDAO"
Traceback (most recent call last):
  File "/usr/local/src/nupic/scripts/run_swarm.py", line 187, in <module>
    runPermutations(sys.argv[1:])
  File "/usr/local/src/nupic/scripts/run_swarm.py", line 178, in runPermutations
    fileArgPath, optionsDict, outputLabel, permWorkDir)
  File "/usr/local/lib/python2.7/dist-packages/nupic-0.5.1.dev0-py2.7.egg/nupic/swarming/permutations_runner.py", line 310, in runWithJsonFile
    verbosity=verbosity)
  File "/usr/local/lib/python2.7/dist-packages/nupic-0.5.1.dev0-py2.7.egg/nupic/swarming/permutations_runner.py", line 277, in runWithConfig
    return _runAction(runOptions)
  File "/usr/local/lib/python2.7/dist-packages/nupic-0.5.1.dev0-py2.7.egg/nupic/swarming/permutations_runner.py", line 218, in _runAction
    returnValue = _runHyperSearch(runOptions)
  File "/usr/local/lib/python2.7/dist-packages/nupic-0.5.1.dev0-py2.7.egg/nupic/swarming/permutations_runner.py", line 147, in _runHyperSearch
    search = _HyperSearchRunner(runOptions)
  File "/usr/local/lib/python2.7/dist-packages/nupic-0.5.1.dev0-py2.7.egg/nupic/swarming/permutations_runner.py", line 418, in __init__
    self.__cjDAO = _clientJobsDB()
  File "/usr/local/lib/python2.7/dist-packages/nupic-0.5.1.dev0-py2.7.egg/nupic/swarming/permutations_runner.py", line 382, in _clientJobsDB
    return cjdao.ClientJobsDAO.get()
  File "/usr/local/lib/python2.7/dist-packages/nupic-0.5.1.dev0-py2.7.egg/nupic/support/decorators.py", line 56, in exceptionLoggingWrap
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nupic-0.5.1.dev0-py2.7.egg/nupic/database/ClientJobsDAO.py", line 548, in get
    cjDAO.connect()
  File "/usr/local/lib/python2.7/dist-packages/nupic-0.5.1.dev0-py2.7.egg/nupic/support/decorators.py", line 56, in exceptionLoggingWrap
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nupic-0.5.1.dev0-py2.7.egg/nupic/support/decorators.py", line 208, in retryWrap
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nupic-0.5.1.dev0-py2.7.egg/nupic/database/ClientJobsDAO.py", line 636, in connect
    recreate=recreate)
  File "/usr/local/lib/python2.7/dist-packages/nupic-0.5.1.dev0-py2.7.egg/nupic/support/decorators.py", line 56, in exceptionLoggingWrap
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nupic-0.5.1.dev0-py2.7.egg/nupic/database/ClientJobsDAO.py", line 802, in _initTables
    cursor.execute(query)
  File "/usr/local/lib/python2.7/dist-packages/DBUtils-1.1-py2.7.egg/DBUtils/SteadyDB.py", line 631, in tough_method
    raise error # reraise the original error again
pymysql.err.InternalError: (1067, u"Invalid default value for 'start_time'")

**Comment by rhyolight** [comment]
This is probably because of #2983. Can you downgrade to MySQL < 5.7 and see if that helps?

**Comment by cbb83** [comment]
I am having the same issue I am using OSX 10.9 and I followed the advice on the other issue but changing to DATETIME DEFAULT CURRENT_TIMESTAMP did not seem to help. Did down grading help for aoman89757?

**Comment by rhyolight** [comment]
@cbb83 I don't know yet... Hey @aoman89757 did downgrading MySQL to 5.6 help? Or have you tried?

**Comment by cbb83** [comment]
I was eventually able to remove the zero date on start up but it is rather irritating. I haven't found a way to make it stick.
