### ISSUE TITLE
Installation fails on SUSE Linux Enterprise Server 12 SP1

### ISSUE THREAD

**Issue by agvse** [numenta/nupic#3061]
I've been trying to build nupic.core from core for a while. The error I'm getting is:
`./setup.py install`

Gets to

```
Installing /tmp/tmpyCtKvK/scripts/ThirdParty/Install/share/swig/3.0.2/std/std_wsstream.i
Installing /tmp/tmpyCtKvK/scripts/ThirdParty/Install/share/swig/3.0.2/std/std_wstreambuf.i
Installing /tmp/tmpyCtKvK/scripts/ThirdParty/Install/share/swig/3.0.2/std/std_wstring.i
Installing /tmp/tmpyCtKvK/scripts/ThirdParty/Install/share/swig/3.0.2/std/std_carray.swg
Installation complete
[ 20%] Completed 'Swig'
[ 20%] Built target Swig
Makefile:136: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 58, in <module>
    
  File "/home/ec2-user/nupic.core/bindings/py/setup.py", line 201, in <module>
    getExtensionFiles(platform)
  File "/home/ec2-user/nupic.core/bindings/py/setup.py", line 166, in getExtensionFiles
    generateExtensions()
  File "/home/ec2-user/nupic.core/bindings/py/setup.py", line 185, in generateExtensions
    subprocess.check_call(["make", "-j3"])
  File "/usr/lib64/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j3']' returned non-zero exit status 2
```

Tried the developer installation as well:
```
suse12:/home/ec2-user/nupic.core/build/scripts # make -j3
[  0%] [  4%] [  8%] Built target capnp_specs
Built target Swig
Built target CapnProto
[  8%] Built target gtest
[  8%] [  9%] Building CXX object src/CMakeFiles/nupic_core_solo.dir/nupic/algorithms/BitHistory.cpp.o
[ 10%] Building CXX object src/CMakeFiles/nupic_core_solo.dir/nupic/py_support/CapnpToPycapnp.cpp.o
Building CXX object src/CMakeFiles/nupic_core_solo.dir/nupic/algorithms/Cell.cpp.o
/home/ec2-user/nupic.core/src/nupic/py_support/CapnpToPycapnp.cpp:236:41: fatal error: capnp/helpers/checkCompiler.h: No such file or directory
 #include "capnp/helpers/checkCompiler.h"
                                         ^
compilation terminated.
src/CMakeFiles/nupic_core_solo.dir/build.make:580: recipe for target 'src/CMakeFiles/nupic_core_solo.dir/nupic/py_support/CapnpToPycapnp.cpp.o' failed
make[2]: *** [src/CMakeFiles/nupic_core_solo.dir/nupic/py_support/CapnpToPycapnp.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:512: recipe for target 'src/CMakeFiles/nupic_core_solo.dir/all' failed
make[1]: *** [src/CMakeFiles/nupic_core_solo.dir/all] Error 2
Makefile:136: recipe for target 'all' failed
make: *** [all] Error 2
```

gcc:
`gcc version 4.8.5 (SUSE Linux) `

g++:
`gcc-c++-4.8-6.189.x86_64`

cmake:
`2.8.12.1`

**Comment by rhyolight** [comment]
@agvse Very sorry I missed this issue. You shouldn't have to wait so long for an answer. I'll try to help. 

First of all, did you happen to already have Capn Proto installed on your system already? I have had issues in the past where I've needed to [manually install Capnp with their installation instructions](https://capnproto.org/install.html), and once that was done, the nupic.core build worked. Maybe you can try that?

**Comment by agvse** [comment]
No worries, I remember discussing the problem with you on gitter. Running setup.py clean and installing the Ubuntu wheel fixed the problem. But yes, I remember installing capnp separately.

**Comment by rhyolight** [comment]
Great, thanks for the follow-up.
