### ISSUE TITLE
KeyError: 'categoryIn' when using CLAClassifier

### ISSUE THREAD

**Issue by aoman89757** [numenta/nupic#3074]
Traceback (most recent call last):
  File "network.py", line 353, in <module>
    runDemo()
  File "network.py", line 345, in runDemo
    runNetwork(network, numRecords, writer)
  File "network.py", line 279, in runNetwork
    network.run(1)
  File "/usr/local/lib/python2.7/dist-packages/nupic-0.5.1.dev0-py2.7.egg/nupic/engine/__init__.py", line 681, in run
    engine.Network.run(self, n)
  File "/usr/local/lib/python2.7/dist-packages/nupic.bindings-0.4.1.dev0-py2.7-linux-x86_64.egg/nupic/bindings/engine_internal.py", line 1147, in run
    return _engine_internal.Network_run(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nupic-0.5.1.dev0-py2.7.egg/nupic/regions/CLAClassifierRegion.py", line 357, in compute
    categories = [category for category in inputs["categoryIn"]
KeyError: 'categoryIn'

**Comment by rhyolight** [comment]
I'm sorry @aoman89757 I have had a busy week. Did you find out what was wrong? Or just get frustrated that no one answered?

**Comment by aoman89757** [comment]
In fact, both :(
I have opened another issue where I dig deeper @rhyolight

**Comment by scottpurdy** [comment]
Replaced by #3078
