### ISSUE TITLE
Error running hierarchy_network_demo.py

### ISSUE THREAD

**Issue by Containerhouse** [numenta/nupic#3257]
Running the stock file `hierarchy_network_demo.py` (`nupic/examples/network`) the following error is thrown before it is able to write the .csv:

``` console
Writing output to: hierarchy-demo-output.csv
Traceback (most recent call last):
  File "hierarchy_network_demo.py", line 368, in <module>
    runDemo()
  File "hierarchy_network_demo.py", line 362, in runDemo
    runNetwork(network, numRecords, writer)
  File "hierarchy_network_demo.py", line 305, in runNetwork
    network.run(1)
  File "/usr/local/lib/python2.7/dist-packages/nupic-0.5.5.dev0-py2.7.egg/nupic/engine/__init__.py", line 693, in run
    engine.Network.run(self, n)
  File "/usr/local/lib/python2.7/dist-packages/nupic.bindings-0.4.5.dev0-py2.7-linux-x86_64.egg/nupic/bindings/engine_internal.py", line 1147, in run
    return _engine_internal.Network_run(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nupic.bindings-0.4.5.dev0-py2.7-linux-x86_64.egg/nupic/bindings/regions/PyRegion.py", line 178, in guardedCompute
    return self.compute(inputs, DictReadOnlyWrapper(outputs))
  File "/usr/local/lib/python2.7/dist-packages/nupic-0.5.5.dev0-py2.7.egg/nupic/regions/SDRClassifierRegion.py", line 352, in compute
    categories = [category for category in inputs["categoryIn"]
KeyError: 'categoryIn'
```

**Comment by rhyolight** [comment]
I can replicate this error. @scottpurdy can @andrewmalta13 look into this?

**Comment by scottpurdy** [comment]
@mrcslws can you take a look

**Comment by rhyolight** [comment]
@mrcslws Just told me that there is [some history around this issue](https://github.com/numenta/nupic/search?utf8=%E2%9C%93&q=categoryIn&type=Issues), but now I'm more confused. We probably just need to fix this demo so an error is not thrown, perhaps we don't need to crawl down that `categoryIn` rabbit hole.

**Comment by rhyolight** [comment]
I tried running the example by switching the params [`spatialImp`](https://github.com/numenta/nupic/blob/master/examples/network/hierarchy_network_demo.py#L54) & [`temporalImp`](https://github.com/numenta/nupic/blob/master/examples/network/hierarchy_network_demo.py#L72) to `py` instead of `cpp`, and it ran for a long while before having the same error. 

However with `cpp` it crashed right away. Using `py` it was able to run a lot of records through before crashing. 🤷‍♂️

**Comment by scottpurdy** [comment]
There appear to be a couple issues. One is recent changes to do away with `customCompute` in the classifier region. I've made those changes and will push a new version of the hierarchy demo soon to close out this issue. The predictions will still be incorrect though until we address #3651
