### ISSUE TITLE
testing OneHotGym. ./swarm.py

### ISSUE THREAD

**Issue by kleineLi** [numenta/nupic#3375]
Hey, I have been tried to test OneHotGym prediction with a tutorial on YouTube https://www.youtube.com/watch?v=S-0thrzOHTc

and when I try to execute swarm.py, then I have mistake, and I don't know how I can it fix.

```console
Generating experiment files in directory: /home/lis/nupic/examples/opf/clients/hotgym/prediction/one_gym/swarm...
Writing  312 lines...
Writing  114 lines...
done.
None
WARNING:nupic.database.ClientJobsDAO:[] First failure in <function connect at 0x7f0ee32231b8>; initial retry in 0.1 sec.; timeoutSec=300. Caller stack:
  File "./swarm.py", line 109, in <module>
    swarm(INPUT_FILE)
  File "./swarm.py", line 101, in swarm
    modelParams = swarmForBestModelParams(SWARM_DESCRIPTION, name)
  File "./swarm.py", line 78, in swarmForBestModelParams
    verbosity=0
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/swarming/permutations_runner.py", line 271, in runWithConfig
    return _runAction(runOptions)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/swarming/permutations_runner.py", line 212, in _runAction
    returnValue = _runHyperSearch(runOptions)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/swarming/permutations_runner.py", line 141, in _runHyperSearch
    search = _HyperSearchRunner(runOptions)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/swarming/permutations_runner.py", line 412, in __init__
    self.__cjDAO = _clientJobsDB()
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/swarming/permutations_runner.py", line 376, in _clientJobsDB
    return cjdao.ClientJobsDAO.get()
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/support/decorators.py", line 56, in exceptionLoggingWrap
    return func(*args, **kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/database/ClientJobsDAO.py", line 549, in get
    cjDAO.connect()
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/support/decorators.py", line 56, in exceptionLoggingWrap
    return func(*args, **kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/support/decorators.py", line 234, in retryWrap
    timeoutSec, ''.join(traceback.format_stack()), exc_info=True)
Traceback (most recent call last):
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/support/decorators.py", line 208, in retryWrap
    result = func(*args, **kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/database/ClientJobsDAO.py", line 634, in connect
    with ConnectionFactory.get() as conn:
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/database/Connection.py", line 167, in get
    return cls._connectionPolicy.acquireConnection()
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/database/Connection.py", line 553, in acquireConnection
    dbConn = self._pool.connection(shareable=False)
  File "/home/lis/.local/lib/python2.7/site-packages/DBUtils/PooledDB.py", line 331, in connection
    con = self.steady_connection()
  File "/home/lis/.local/lib/python2.7/site-packages/DBUtils/PooledDB.py", line 279, in steady_connection
    *self._args, **self._kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/DBUtils/SteadyDB.py", line 134, in connect
    failures, ping, closeable, *args, **kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/DBUtils/SteadyDB.py", line 186, in __init__
    self._store(self._create())
  File "/home/lis/.local/lib/python2.7/site-packages/DBUtils/SteadyDB.py", line 190, in _create
    con = self._creator(*self._args, **self._kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/pymysql/__init__.py", line 88, in Connect
    return Connection(*args, **kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/pymysql/connections.py", line 626, in __init__
    self._connect()
  File "/home/lis/.local/lib/python2.7/site-packages/pymysql/connections.py", line 818, in _connect
    2003, "Can't connect to MySQL server on %r (%s)" % (self.host, e))
OperationalError: (2003, 'Can\'t connect to MySQL server on \'localhost\' ((1045, u"Access denied for user \'root\'@\'localhost\' (using password: NO)"))')
ERROR:nupic.database.ClientJobsDAO:[] Exhausted retry timeout (300 sec.; 37 attempts) for <function connect at 0x7f0ee32231b8>. Caller stack:
  File "./swarm.py", line 109, in <module>
    swarm(INPUT_FILE)
  File "./swarm.py", line 101, in swarm
    modelParams = swarmForBestModelParams(SWARM_DESCRIPTION, name)
  File "./swarm.py", line 78, in swarmForBestModelParams
    verbosity=0
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/swarming/permutations_runner.py", line 271, in runWithConfig
    return _runAction(runOptions)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/swarming/permutations_runner.py", line 212, in _runAction
    returnValue = _runHyperSearch(runOptions)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/swarming/permutations_runner.py", line 141, in _runHyperSearch
    search = _HyperSearchRunner(runOptions)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/swarming/permutations_runner.py", line 412, in __init__
    self.__cjDAO = _clientJobsDB()
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/swarming/permutations_runner.py", line 376, in _clientJobsDB
    return cjdao.ClientJobsDAO.get()
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/support/decorators.py", line 56, in exceptionLoggingWrap
    return func(*args, **kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/database/ClientJobsDAO.py", line 549, in get
    cjDAO.connect()
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/support/decorators.py", line 56, in exceptionLoggingWrap
    return func(*args, **kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/support/decorators.py", line 227, in retryWrap
    ''.join(traceback.format_stack()))
Traceback (most recent call last):
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/support/decorators.py", line 208, in retryWrap
    result = func(*args, **kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/database/ClientJobsDAO.py", line 634, in connect
    with ConnectionFactory.get() as conn:
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/database/Connection.py", line 167, in get
    return cls._connectionPolicy.acquireConnection()
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/database/Connection.py", line 553, in acquireConnection
    dbConn = self._pool.connection(shareable=False)
  File "/home/lis/.local/lib/python2.7/site-packages/DBUtils/PooledDB.py", line 331, in connection
    con = self.steady_connection()
  File "/home/lis/.local/lib/python2.7/site-packages/DBUtils/PooledDB.py", line 279, in steady_connection
    *self._args, **self._kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/DBUtils/SteadyDB.py", line 134, in connect
    failures, ping, closeable, *args, **kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/DBUtils/SteadyDB.py", line 186, in __init__
    self._store(self._create())
  File "/home/lis/.local/lib/python2.7/site-packages/DBUtils/SteadyDB.py", line 190, in _create
    con = self._creator(*self._args, **self._kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/pymysql/__init__.py", line 88, in Connect
    return Connection(*args, **kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/pymysql/connections.py", line 626, in __init__
    self._connect()
  File "/home/lis/.local/lib/python2.7/site-packages/pymysql/connections.py", line 818, in _connect
    2003, "Can't connect to MySQL server on %r (%s)" % (self.host, e))
OperationalError: (2003, 'Can\'t connect to MySQL server on \'localhost\' ((1045, u"Access denied for user \'root\'@\'localhost\' (using password: NO)"))')
ERROR:nupic.database.ClientJobsDAO:Unhandled exception OperationalError(2003, 'Can\'t connect to MySQL server on \'localhost\' ((1045, u"Access denied for user \'root\'@\'localhost\' (using password: NO)"))') from <function connect at 0x7f0ee3223230>. Caller stack:
  File "./swarm.py", line 109, in <module>
    swarm(INPUT_FILE)
  File "./swarm.py", line 101, in swarm
    modelParams = swarmForBestModelParams(SWARM_DESCRIPTION, name)
  File "./swarm.py", line 78, in swarmForBestModelParams
    verbosity=0
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/swarming/permutations_runner.py", line 271, in runWithConfig
    return _runAction(runOptions)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/swarming/permutations_runner.py", line 212, in _runAction
    returnValue = _runHyperSearch(runOptions)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/swarming/permutations_runner.py", line 141, in _runHyperSearch
    search = _HyperSearchRunner(runOptions)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/swarming/permutations_runner.py", line 412, in __init__
    self.__cjDAO = _clientJobsDB()
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/swarming/permutations_runner.py", line 376, in _clientJobsDB
    return cjdao.ClientJobsDAO.get()
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/support/decorators.py", line 56, in exceptionLoggingWrap
    return func(*args, **kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/database/ClientJobsDAO.py", line 549, in get
    cjDAO.connect()
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/support/decorators.py", line 60, in exceptionLoggingWrap
    sys.exc_info()[1], func, ''.join(traceback.format_stack()), )
Traceback (most recent call last):
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/support/decorators.py", line 56, in exceptionLoggingWrap
    return func(*args, **kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/support/decorators.py", line 208, in retryWrap
    result = func(*args, **kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/database/ClientJobsDAO.py", line 634, in connect
    with ConnectionFactory.get() as conn:
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/database/Connection.py", line 167, in get
    return cls._connectionPolicy.acquireConnection()
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/database/Connection.py", line 553, in acquireConnection
    dbConn = self._pool.connection(shareable=False)
  File "/home/lis/.local/lib/python2.7/site-packages/DBUtils/PooledDB.py", line 331, in connection
    con = self.steady_connection()
  File "/home/lis/.local/lib/python2.7/site-packages/DBUtils/PooledDB.py", line 279, in steady_connection
    *self._args, **self._kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/DBUtils/SteadyDB.py", line 134, in connect
    failures, ping, closeable, *args, **kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/DBUtils/SteadyDB.py", line 186, in __init__
    self._store(self._create())
  File "/home/lis/.local/lib/python2.7/site-packages/DBUtils/SteadyDB.py", line 190, in _create
    con = self._creator(*self._args, **self._kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/pymysql/__init__.py", line 88, in Connect
    return Connection(*args, **kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/pymysql/connections.py", line 626, in __init__
    self._connect()
  File "/home/lis/.local/lib/python2.7/site-packages/pymysql/connections.py", line 818, in _connect
    2003, "Can't connect to MySQL server on %r (%s)" % (self.host, e))
OperationalError: (2003, 'Can\'t connect to MySQL server on \'localhost\' ((1045, u"Access denied for user \'root\'@\'localhost\' (using password: NO)"))')
ERROR:nupic.database.ClientJobsDAO:Unhandled exception OperationalError(2003, 'Can\'t connect to MySQL server on \'localhost\' ((1045, u"Access denied for user \'root\'@\'localhost\' (using password: NO)"))') from <function get at 0x7f0ee3222de8>. Caller stack:
  File "./swarm.py", line 109, in <module>
    swarm(INPUT_FILE)
  File "./swarm.py", line 101, in swarm
    modelParams = swarmForBestModelParams(SWARM_DESCRIPTION, name)
  File "./swarm.py", line 78, in swarmForBestModelParams
    verbosity=0
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/swarming/permutations_runner.py", line 271, in runWithConfig
    return _runAction(runOptions)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/swarming/permutations_runner.py", line 212, in _runAction
    returnValue = _runHyperSearch(runOptions)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/swarming/permutations_runner.py", line 141, in _runHyperSearch
    search = _HyperSearchRunner(runOptions)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/swarming/permutations_runner.py", line 412, in __init__
    self.__cjDAO = _clientJobsDB()
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/swarming/permutations_runner.py", line 376, in _clientJobsDB
    return cjdao.ClientJobsDAO.get()
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/support/decorators.py", line 60, in exceptionLoggingWrap
    sys.exc_info()[1], func, ''.join(traceback.format_stack()), )
Traceback (most recent call last):
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/support/decorators.py", line 56, in exceptionLoggingWrap
    return func(*args, **kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/database/ClientJobsDAO.py", line 549, in get
    cjDAO.connect()
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/support/decorators.py", line 56, in exceptionLoggingWrap
    return func(*args, **kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/support/decorators.py", line 208, in retryWrap
    result = func(*args, **kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/database/ClientJobsDAO.py", line 634, in connect
    with ConnectionFactory.get() as conn:
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/database/Connection.py", line 167, in get
    return cls._connectionPolicy.acquireConnection()
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/database/Connection.py", line 553, in acquireConnection
    dbConn = self._pool.connection(shareable=False)
  File "/home/lis/.local/lib/python2.7/site-packages/DBUtils/PooledDB.py", line 331, in connection
    con = self.steady_connection()
  File "/home/lis/.local/lib/python2.7/site-packages/DBUtils/PooledDB.py", line 279, in steady_connection
    *self._args, **self._kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/DBUtils/SteadyDB.py", line 134, in connect
    failures, ping, closeable, *args, **kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/DBUtils/SteadyDB.py", line 186, in __init__
    self._store(self._create())
  File "/home/lis/.local/lib/python2.7/site-packages/DBUtils/SteadyDB.py", line 190, in _create
    con = self._creator(*self._args, **self._kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/pymysql/__init__.py", line 88, in Connect
    return Connection(*args, **kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/pymysql/connections.py", line 626, in __init__
    self._connect()
  File "/home/lis/.local/lib/python2.7/site-packages/pymysql/connections.py", line 818, in _connect
    2003, "Can't connect to MySQL server on %r (%s)" % (self.host, e))
OperationalError: (2003, 'Can\'t connect to MySQL server on \'localhost\' ((1045, u"Access denied for user \'root\'@\'localhost\' (using password: NO)"))')
Traceback (most recent call last):
  File "./swarm.py", line 109, in <module>
    swarm(INPUT_FILE)
  File "./swarm.py", line 101, in swarm
    modelParams = swarmForBestModelParams(SWARM_DESCRIPTION, name)
  File "./swarm.py", line 78, in swarmForBestModelParams
    verbosity=0
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/swarming/permutations_runner.py", line 271, in runWithConfig
    return _runAction(runOptions)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/swarming/permutations_runner.py", line 212, in _runAction
    returnValue = _runHyperSearch(runOptions)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/swarming/permutations_runner.py", line 141, in _runHyperSearch
    search = _HyperSearchRunner(runOptions)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/swarming/permutations_runner.py", line 412, in __init__
    self.__cjDAO = _clientJobsDB()
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/swarming/permutations_runner.py", line 376, in _clientJobsDB
    return cjdao.ClientJobsDAO.get()
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/support/decorators.py", line 56, in exceptionLoggingWrap
    return func(*args, **kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/database/ClientJobsDAO.py", line 549, in get
    cjDAO.connect()
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/support/decorators.py", line 56, in exceptionLoggingWrap
    return func(*args, **kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/support/decorators.py", line 208, in retryWrap
    result = func(*args, **kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/database/ClientJobsDAO.py", line 634, in connect
    with ConnectionFactory.get() as conn:
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/database/Connection.py", line 167, in get
    return cls._connectionPolicy.acquireConnection()
  File "/home/lis/.local/lib/python2.7/site-packages/nupic/database/Connection.py", line 553, in acquireConnection
    dbConn = self._pool.connection(shareable=False)
  File "/home/lis/.local/lib/python2.7/site-packages/DBUtils/PooledDB.py", line 331, in connection
    con = self.steady_connection()
  File "/home/lis/.local/lib/python2.7/site-packages/DBUtils/PooledDB.py", line 279, in steady_connection
    *self._args, **self._kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/DBUtils/SteadyDB.py", line 134, in connect
    failures, ping, closeable, *args, **kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/DBUtils/SteadyDB.py", line 186, in __init__
    self._store(self._create())
  File "/home/lis/.local/lib/python2.7/site-packages/DBUtils/SteadyDB.py", line 190, in _create
    con = self._creator(*self._args, **self._kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/pymysql/__init__.py", line 88, in Connect
    return Connection(*args, **kwargs)
  File "/home/lis/.local/lib/python2.7/site-packages/pymysql/connections.py", line 626, in __init__
    self._connect()
  File "/home/lis/.local/lib/python2.7/site-packages/pymysql/connections.py", line 818, in _connect
    2003, "Can't connect to MySQL server on %r (%s)" % (self.host, e))
pymysql.err.OperationalError: (2003, 'Can\'t connect to MySQL server on \'localhost\' ((1045, u"Access denied for user \'root\'@\'localhost\' (using password: NO)"))')
```

Help me, please.

I have Ubuntu 16.04

**Comment by rhyolight** [comment]
Do you have mysql running?

**Comment by kleineLi** [comment]
yes, I think so.
But it works only by command mysql -u root -p.

**Comment by kleineLi** [comment]
I have read some cases with a similar problem, but not fully understood what I need to do with nupic-default.xml file. How must I configure this file that it will work

**Comment by rhyolight** [comment]
You should not have to do anything if you are using the defaults you mentioned above. Are you sure that you can create databases and tables? Go into mysql manually and true to make sure.

**Comment by kleineLi** [comment]
Yeah, I corrected my trouble
Thank you.

**Comment by YuanZhonghua** [comment]
may I ask you how to solve this problem.

**Comment by kleineLi** [comment]
if python $NUPIC/examples/swarm/test_db.py failed

Solution
copyed nupic-default.xml to nupic-site.xml
in a direction nupic/src/nupic/support/

mysql
error:1045 (using password: NO)
1 sudo service mysql stop
2 sudo mysql --skip-grant-tables
#2.1 sudo mysql_safe --skip-grant-tables
#2.2 sudo mysql --skip-grant-tables
3 sudo mysql -u root


if all of this doesn't works then
1. sudo service mysql stop
2. add 
	[mysqld]
	skip-grant-tables
   to etc/mysql/my.cnf
3. service mysql restart
4. check status
	service mysql status

python $NUPIC/examples/swarm/test_db.py 

success val:

>This script will validate that your MySQL is setup correctly for 
>NuPIC. MySQL is required for NuPIC swarming. The settings are
>defined in a configuration file found in  
>$NUPIC/src/nupic/support/nupic-default.xml Out of the box those 
>settings contain MySQL's default access credentials.

>The nupic-default.xml can be duplicated to define user specific 
>changes calling the copied file 
>$NUPIC/src/nupic/support/nupic-site.xml Refer to the 
>nupic-default.xml for additional instructions.

>Defaults: localhost, 3306, root, no password

>Retrieved the following NuPIC configuration using:  nupic-default.xml
>    host   :     localhost
>    port   :     3306
>    user   :     root
>    passwd :     
>Connection successful!!

One Hot Gym
cd nupic/examples/opf/clients/hotgym/predication/one_gym

./swarm.py

./run.py rec-center-hourly.csv

**Comment by YuanZhonghua** [comment]
**thank you**, **adding skip_grant_table** solved my problem, the ubuntu16.04 distribution has lots changes compared with 15.10. when I 'python run.py --plot' it prompt me that '**the global name plt is not defined**' so the matplotlib is not available , then I found the **tkinter** missed. but I still have question that  why the database configure dict couldn't be passed to mysql.
