### ISSUE TITLE
oserror always exists when I implemented some programs.

### ISSUE THREAD

**Issue by lizhidan** [numenta/nupic#3425]
from nupic.encoders import MultiEncoder, DeltaEncoder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dl/anaconda2/lib/python2.7/site-packages/nupic/encoders/__init__.py", line 22, in <module>
    from scalar import ScalarEncoder
  File "/home/dl/anaconda2/lib/python2.7/site-packages/nupic/encoders/scalar.py", line 29, in <module>
    from nupic.bindings.math import SM32, GetNTAReal
  File "/home/dl/anaconda2/lib/python2.7/site-packages/nupic/bindings/math.py", line 42, in <module>
    _nupic_bindings_load_capnp_shared_object()
  File "/home/dl/anaconda2/lib/python2.7/site-packages/nupic/bindings/math.py", line 40, in _nupic_bindings_load_capnp_shared_object
    ctypes.CDLL(capnpDLLPath, ctypes.RTLD_GLOBAL)
  File "/home/dl/anaconda2/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/dl/anaconda2/lib/python2.7/site-packages/capnp/lib/capnp.so: undefined symbol: _ZNSt16invalid_argumentC1EPKc

**Comment by rhyolight** [comment]
I am sorry, but we don't support Anaconda yet. You can help if you can: https://github.com/numenta/nupic/issues/2522
