### ISSUE TITLE
Example hotgym swarming not working

### ISSUE THREAD

**Issue by kenanbirkan** [numenta/nupic#3432]
example swarm aplication cannot work properly , here is the output and possible reason;
in permutations_runner.py 
 modelIDs = hyperSearchJob.queryModelIDs()
modelIDS returns ; <type 'tuple'>: ()

```
Generating experiment files in directory: /home/user/Desktop/test-project/nupic-master/examples/opf/clients/hotgym/prediction/one_gym/swarm...
Writing  312 lines...
Writing  114 lines...
done.
None
Successfully submitted new HyperSearch job, jobID=1007
**Evaluated 0 models**
**HyperSearch finished!**
Worker completion message: None

Results from all experiments:
----------------------------------------------------------------
Generating experiment files in directory: /tmp/tmp_W4sqK...
Writing  312 lines...
Writing  114 lines...
done.
None
Traceback (most recent call last):
  File "/home/user/Desktop/pycharm-community-2016.1.2/helpers/pydev/pydevd.py", line 1531, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/user/Desktop/pycharm-community-2016.1.2/helpers/pydev/pydevd.py", line 938, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/user/Desktop/test-project/nupic-master/examples/opf/clients/hotgym/prediction/one_gym/swarm.py", line 108, in <module>
    swarm(INPUT_FILE)
  File "/home/user/Desktop/test-project/nupic-master/examples/opf/clients/hotgym/prediction/one_gym/swarm.py", line 100, in swarm
    modelParams = swarmForBestModelParams(SWARM_DESCRIPTION, name)
json.loads(jobInfo.results) raised an exception.  Here is some info to help with debugging:
  File "/home/user/Desktop/test-project/nupic-master/examples/opf/clients/hotgym/prediction/one_gym/swarm.py", line 77, in swarmForBestModelParams
    verbosity=0
  File "/home/user/Desktop/test-project/detection_virtual_env/lib/python2.7/site-packages/nupic/swarming/permutations_runner.py", line 271, in runWithConfig
    return _runAction(runOptions)
  File "/home/user/Desktop/test-project/detection_virtual_env/lib/python2.7/site-packages/nupic/swarming/permutations_runner.py", line 212, in _runAction
    returnValue = _runHyperSearch(runOptions)
  File "/home/user/Desktop/test-project/detection_virtual_env/lib/python2.7/site-packages/nupic/swarming/permutations_runner.py", line 155, in _runHyperSearch
    metricsKeys=search.getDiscoveredMetricsKeys())
  File "/home/user/Desktop/test-project/detection_virtual_env/lib/python2.7/site-packages/nupic/swarming/permutations_runner.py", line 822, in generateReport
jobInfo:  _jobInfoNamedTuple(jobId=1007, client=u'GRP', clientInfo=u'', clientKey=u'', cmdLine=u'$HYPERSEARCH', params=u'{"hsVersion": "v2", "maxModels": null, "persistentJobGUID": "9ed187a0-c6c2-11e6-99e2-08002735d4ff", "useTerminators": false, "description": {"inferenceArgs": {"predictionSteps": [1], "predictedField": "kw_energy_consumption"}, "iterationCount": -1, "swarmSize": "medium", "includedFields": [{"fieldName": "timestamp", "fieldType": "datetime"}, {"minValue": 0.0, "fieldName": "kw_energy_consumption", "fieldType": "float", "maxValue": 53.0}], "streamDef": {"info": "kw_energy_consumption", "version": 1, "streams": [{"info": "Rec Center", "source": "file://rec-center-hourly.csv", "columns": ["*"]}]}, "inferenceType": "TemporalMultiStep"}}', jobHash="\x9e\xd2\xb1\x16\xc6\xc2\x11\xe6\x99\xe2\x08\x00'5\xd4\xff", status=u'notStarted', completionReason=None, completionMsg=None, workerCompletionReason=u'success', workerCompletionMsg=None, cancel=0, startTime=None, endTime=None, results=None, engJobType=u'hypersearch', minimumWorkers=1, maximumWorkers=4, priority=0, engAllocateNewWorkers=1, engUntendedDeadWorkers=0, numFailedWorkers=0, lastFailedWorkerErrorMsg=None, engCleaningStatus=u'notdone', genBaseDescription=None, genPermutations=None, engLastUpdateTime=datetime.datetime(2016, 12, 20, 14, 43, 7), engCjmConnId=None, engWorkerState=None, engStatus=None, engModelMilestones=None)
    results = json.loads(jobInfo.results)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
jobInfo.results:  None
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
EXCEPTION:  expected string or buffer
TypeError: expected string or buffer
```

**Comment by rhyolight** [comment]
Please paste the exact command you ran to generate this error, including the current working directory.

**Comment by kenanbirkan** [comment]
it looks like problem occurred debug|run mode of pycharm , runs successfully from terminal 
path:nupic-master/examples/opf/clients/hotgym/prediction/one_gym
python swarm.py

**Comment by rhyolight** [comment]
Ok great, thanks for the report anyway. I've had some troubles setting up my pycharm environment as well. I just run from the command line. ;)
