### ISSUE TITLE
Error running simple hotgym example

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#3504]
```
python examples/opf/clients/hotgym/simple/hotgym.py
Traceback (most recent call last):
  File "examples/opf/clients/hotgym/simple/hotgym.py", line 96, in <module>
    runHotgym()
  File "examples/opf/clients/hotgym/simple/hotgym.py", line 67, in runHotgym
    model = createModel()
  File "examples/opf/clients/hotgym/simple/hotgym.py", line 62, in createModel
    return ModelFactory.create(model_params.MODEL_PARAMS)
  File "/Users/mtaylor/nta/nupic/venv/lib/python2.7/site-packages/nupic-0.6.0-py2.7.egg/nupic/frameworks/opf/modelfactory.py", line 80, in create
    return modelClass(**modelConfig['modelParams'])
  File "/Users/mtaylor/nta/nupic/venv/lib/python2.7/site-packages/nupic-0.6.0-py2.7.egg/nupic/frameworks/opf/clamodel.py", line 207, in __init__
    clParams, anomalyParams)
  File "/Users/mtaylor/nta/nupic/venv/lib/python2.7/site-packages/nupic-0.6.0-py2.7.egg/nupic/frameworks/opf/clamodel.py", line 1180, in __createCLANetwork
    n.initialize()
  File "/Users/mtaylor/nta/nupic/venv/lib/python2.7/site-packages/nupic-0.6.0-py2.7.egg/nupic/engine/__init__.py", line 697, in initialize
    engine_internal.Network.initialize(self, *args, **kwargs)
  File "/Users/mtaylor/nta/nupic.core/bindings/py/nupic/bindings/engine_internal.py", line 1172, in initialize
    return _engine_internal.Network_initialize(self)
TypeError: initialize() takes exactly 1 argument (3 given)
```

@oxtopus I think you made a change here recently, yes? Does this look like it is related? Perhaps something in the OPF needs to be adjusted.

**Comment by oxtopus** [comment]
It is related, yes.  I'm guessing your nupic.bindings is out of date, or otherwise nupic version is out of sync w/ nupic.bindings.

**Comment by rhyolight** [comment]
ok will check

**Comment by rhyolight** [comment]
Bingo, thanks!
