### ISSUE TITLE
Syntax error in unittest2/loader.py", line 92

### ISSUE THREAD

**Issue by BrianBut** [numenta/nupic#3732]
On running pip install nupic:
(cv) brian@son:~/projects/sparse-images$ pip install nupic
Collecting nupic
  Downloading nupic-0.5.6.tar.gz (4.6MB)
    100% |████████████████████████████████| 4.6MB 112kB/s 
Collecting asteval==0.9.1 (from nupic)
  Downloading asteval-0.9.1.tar.gz
Collecting coverage==3.7.1 (from nupic)
  Downloading coverage-3.7.1.tar.gz (284kB)
    100% |████████████████████████████████| 286kB 158kB/s 
Collecting mock==1.0.1 (from nupic)
  Downloading mock-1.0.1.zip (861kB)
    100% |████████████████████████████████| 870kB 220kB/s 
Collecting ordereddict==1.1 (from nupic)
  Downloading ordereddict-1.1.tar.gz
Collecting psutil==1.0.1 (from nupic)
  Downloading psutil-1.0.1.tar.gz (156kB)
    100% |████████████████████████████████| 163kB 176kB/s 
Collecting pytest==2.5.1 (from nupic)
  Downloading pytest-2.5.1.tar.gz (577kB)
    100% |████████████████████████████████| 583kB 1.4MB/s 
Collecting pytest-cov==1.6 (from nupic)
  Downloading pytest-cov-1.6.tar.gz
Collecting pytest-xdist==1.8 (from nupic)
  Downloading pytest-xdist-1.8.zip
Collecting python-dateutil==2.1 (from nupic)
  Downloading python-dateutil-2.1.tar.gz (152kB)
    100% |████████████████████████████████| 153kB 182kB/s 
Collecting PyYAML==3.10 (from nupic)
  Downloading PyYAML-3.10.tar.gz (241kB)
    100% |████████████████████████████████| 245kB 167kB/s 
Collecting unittest2==0.5.1 (from nupic)
  Downloading unittest2-0.5.1.zip (78kB)
    100% |████████████████████████████████| 81kB 151kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-k0sbttvu/unittest2/setup.py", line 12, in <module>
        from unittest2 import __version__ as VERSION
      File "/tmp/pip-build-k0sbttvu/unittest2/unittest2/__init__.py", line 40, in <module>
        from unittest2.collector import collector
      File "/tmp/pip-build-k0sbttvu/unittest2/unittest2/collector.py", line 3, in <module>
        from unittest2.loader import defaultTestLoader
      File "/tmp/pip-build-k0sbttvu/unittest2/unittest2/loader.py", line 92
        except Exception, e:
                        ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-k0sbttvu/unittest2/

**Comment by rhyolight** [comment]
What version of python are you using?

**Comment by rhyolight** [comment]
Also reported [here](https://discourse.numenta.org/t/install-nupic-on-ubuntu-failed/2947).

**Comment by BrianBut** [comment]
I am using Python 3.9.5. When I reported this problem I was confused about shell use so there may have been conflicting versions. Since I switched from venv to conda the problem has solved itself.
I have not been able to achieve a working installation as my computer is too old.

**Comment by RaiNova** [comment]
I have the same problem. When I run pip with python 2.7 `py -2 -m pip install nupic`, I get hthe error `RuntimeError: support for python < 3.6 has been removed in setuptools_scm>=6.0.0`
