### ISSUE TITLE
 Import failed: /nupic/frameworks/opf/model.capnp

### ISSUE THREAD

**Issue by pxc3113** [numenta/nupic#3755]
zhiwei@zhiwei-Lenovo-Rescuer-15ISK:~/nupic/src/nupic$ python simple_server.py
Traceback (most recent call last):
  File "simple_server.py", line 41, in <module>
    from nupic.frameworks.opf.model_factory import ModelFactory
  File "/home/zhiwei/nupic/src/nupic/frameworks/opf/model_factory.py", line 32, in <module>
    from htm_prediction_model import HTMPredictionModel
  File "/home/zhiwei/nupic/src/nupic/frameworks/opf/htm_prediction_model.py", line 57, in <module>
    from nupic.frameworks.opf.HTMPredictionModelProto_capnp \
  File "capnp/lib/capnp.pyx", line 3876, in capnp.lib.capnp._Loader.load_module (capnp/lib/capnp.cpp:75312)
  File "capnp/lib/capnp.pyx", line 3855, in capnp.lib.capnp.load (capnp/lib/capnp.cpp:74806)
  File "capnp/lib/capnp.pyx", line 3192, in capnp.lib.capnp.SchemaParser.load (capnp/lib/capnp.cpp:65957)
capnp.lib.capnp.KjException: /home/zhiwei/nupic/src/nupic/frameworks/opf/HTMPredictionModelProto.capnp:3: failed: Import failed: /nupic/frameworks/opf/model.capnp
stack: 0x7fa193ffcfc5 0x7fa193f02b1b 0x7fa193f02ff5 0x7fa193f4179d 0x7fa193f418ef 0x7fa193f43915 0x7fa193f2c936 0x7fa193f321c5 0x7fa193f2e1be 0x7fa193f2e577 0x7fa193f422d3 0x7fa193f42fc3 0x7fa193f43078 0x7fa193f5a803 0x7fa193f4b121 0x7fa193f4fdc9

**Comment by rhyolight** [comment]
I don't think you have NuPIC installed properly. Please try to reinstall and paste your output logs on https://discourse.numenta.org/c/nupic and I will help you out there.
