### ISSUE TITLE
Problem running category_prediction example

### ISSUE THREAD

**Issue by alanbernstein** [numenta/nupic#3758]
I'm trying to use this for the first time. I can `pip install nupic` with no trouble, but when I try `python examples/prediction/category_prediction/run.py`, I get this:

```
Traceback (most recent call last):
  File "run.py", line 29, in <module>
    from nupic.frameworks.opf.model_factory import ModelFactory
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nupic/frameworks/opf/model_factory.py", line 32, in <module>
    from htm_prediction_model import HTMPredictionModel
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nupic/frameworks/opf/htm_prediction_model.py", line 57, in <module>
    from nupic.frameworks.opf.HTMPredictionModelProto_capnp \
  File "capnp/lib/capnp.pyx", line 3949, in capnp.lib.capnp._Loader.load_module (capnp/lib/capnp.cpp:75559)
  File "capnp/lib/capnp.pyx", line 3928, in capnp.lib.capnp.load (capnp/lib/capnp.cpp:75047)
  File "capnp/lib/capnp.pyx", line 3251, in capnp.lib.capnp.SchemaParser.load (capnp/lib/capnp.cpp:65948)
capnp.lib.capnp.KjException: /usr/local/lib/python2.7/site-packages/nupic/proto/NetworkProto.capnp:0: failed: Duplicate ID @0xbec20a8f487acf07.
stack: 0x10785409d 0x1077b20ab 0x1077afd97 0x1077a3a64 0x1077a384f 0x1077a8a67 0x1077aa8b1 0x1077a8401 0x1077824d6 0x107782901 0x10779257d 0x1077a3265 0x1077a7d74 0x1077a786b 0x1077a7b6f 0x107782ba6
```

I found a couple references to a "Duplicate ID" failure, but not in this context.

OSX 10.12.6, python 2.7.13

**Comment by rhyolight** [comment]
This example seems to be running fine for me. Can you try this:

- [uninstall nupic completely](https://discourse.numenta.org/t/uninstalling-nupic/2175)
- reinstall using `pip install nupic` and save the console output
- [show us the versions of nupic that were installed](https://discourse.numenta.org/t/how-to-check-what-version-of-nupic-is-installed/1045)
- paste the installation logs here

**Comment by alanbernstein** [comment]
There seems to be some unrelated problem with my python installation, I don't think it will be useful to discuss that here.

I tried installing nupic in a virtual environment, and had no trouble running the example in that context.

**Comment by rhyolight** [comment]
😌
