### ISSUE TITLE
pip install nupic gives error "Command "python setup.py egg_info" failed with error code 1 in..."

### ISSUE THREAD

**Issue by cpoptic** [numenta/nupic#3797]
I'm running Windows 10.
To reproduce the error:

I've created a virtual environment "numenta-env" with python=3.6
`activate numenta-env`
`pip install nupic`

It begins installing and then halts while collected unittest2==0.5.1 (from nupic)

Command "python setup.py egg_info" failed with error code 1 in C:\Users\Chris\AppData\Local\Temp\pip-build-r5de8_q3\unittest2\

Here is the complete output after running `pip install nupic`

Collecting nupic
  Using cached nupic-0.5.6.tar.gz
Collecting asteval==0.9.1 (from nupic)
  Using cached asteval-0.9.1.tar.gz
Collecting coverage==3.7.1 (from nupic)
  Using cached coverage-3.7.1.tar.gz
Collecting mock==1.0.1 (from nupic)
  Using cached mock-1.0.1.zip
Collecting ordereddict==1.1 (from nupic)
  Using cached ordereddict-1.1.tar.gz
Collecting psutil==1.0.1 (from nupic)
  Using cached psutil-1.0.1.tar.gz
Collecting pytest==2.5.1 (from nupic)
  Using cached pytest-2.5.1.tar.gz
Collecting pytest-cov==1.6 (from nupic)
  Using cached pytest-cov-1.6.tar.gz
Collecting pytest-xdist==1.8 (from nupic)
  Using cached pytest-xdist-1.8.zip
Collecting python-dateutil==2.1 (from nupic)
  Using cached python-dateutil-2.1.tar.gz
Collecting PyYAML==3.10 (from nupic)
  Using cached PyYAML-3.10.tar.gz
Collecting unittest2==0.5.1 (from nupic)
  Using cached unittest2-0.5.1.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Chris\AppData\Local\Temp\pip-build-r5de8_q3\unittest2\setup.py", line 12, in <module>
        from unittest2 import __version__ as VERSION
      File "C:\Users\Chris\AppData\Local\Temp\pip-build-r5de8_q3\unittest2\unittest2\__init__.py", line 40, in <module>
        from unittest2.collector import collector
      File "C:\Users\Chris\AppData\Local\Temp\pip-build-r5de8_q3\unittest2\unittest2\collector.py", line 3, in <module>
        from unittest2.loader import defaultTestLoader
      File "C:\Users\Chris\AppData\Local\Temp\pip-build-r5de8_q3\unittest2\unittest2\loader.py", line 92
        except Exception, e:
                        ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Chris\AppData\Local\Temp\pip-build-r5de8_q3\unittest2\

I've tried unintstalling and reinstalling setuptools, but no joy.
Incredibly frustrating to sink several hours debugging and reinstalling packages with zero to show for the effort.

**Comment by MikeZhu92** [comment]
Same here. I'm using python 3.5 fresh install and here is the error msgs
```
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lnltf0jn/unittest2/setup.py", line 12, in <module>
        from unittest2 import __version__ as VERSION
      File "/tmp/pip-build-lnltf0jn/unittest2/unittest2/__init__.py", line 40, in <module>
        from unittest2.collector import collector
      File "/tmp/pip-build-lnltf0jn/unittest2/unittest2/collector.py", line 3, in <module>
        from unittest2.loader import defaultTestLoader
      File "/tmp/pip-build-lnltf0jn/unittest2/unittest2/loader.py", line 92
        except Exception, e:
                        ^
    SyntaxError: invalid syntax
  
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lnltf0jn/unittest2/
```

**Comment by MikeZhu92** [comment]
It seems like Nupic only works for Python 2.7 so this issue should be closed.
According to my knowledge Python 2.7 will not be maintained past 2020 though.

**Comment by MZamanMughal** [comment]
No same here for python 2.7 @MikeZhu92

**Comment by MikeZhu92** [comment]
Is that for Ubuntu or Windows ?
Ubuntu works for me at least.
For windows platform I would recommend to check the C++ compiler.

**Comment by rhyolight** [comment]
@MZamanMughal Are you saying that you go this error with python 2.7? This error looks like a python 3 error. Sometimes it happens when you have multiple pythons installed and the wrong one is being invoked.

**Comment by CJJC1220** [comment]
I have come across such a problem, anybody has a solution for this？thanks
C:\Users\CJJC>pip install gdsCAD
Collecting gdsCAD
Using cached https://files.pythonhosted.org/packages/d0/54/60b48ee74d5ba364c4aaaf6a73e0d47274a501aafd3d64b04ce7b03b40f9/gdsCAD-0.4.5.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "", line 1, in 
File "C:\Users\CJJC\AppData\Local\Temp\pip-install-q3i3z0gl\gdsCAD\setup.py", line 4, in 
from git_version import sdist, get_version
File "C:\Users\CJJC\AppData\Local\Temp\pip-install-q3i3z0gl\gdsCAD\git_version.py", line 107
print get_version()
^
SyntaxError: invalid syntax

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\CJJC\AppData\Local\Temp\pip-install-q3i3z0gl\gdsCAD\

**Comment by paris18e** [comment]
@MikeZhu92 Happened for Mac too...

**Comment by rhyolight** [comment]
To Everyone having this problem: Try [uninstalling NuPIC completely](https://discourse.numenta.org/t/uninstalling-nupic/2175), then run `pip install nupic [--user]` again. Make sure you are not running python 3.

**Comment by ibobak** [comment]
Guys, now is the year 2019.  Python 2 will soon be shut down.   We all are migrating code on Python 3. 

And, until now you did not do migration onto Python 3 ???

**Comment by rhyolight** [comment]
This codebase is in maintenance mode. New HTM python code will not be written here. See the [community fork](https://github.com/htm-community/nupic.py) for Python 3.

**Comment by arb-git** [comment]
Thanks @rhyolight!
Though the community fork also has a problem, which makes it unusable:
> ERROR: Could not find a version that satisfies the requirement nupic.bindings>=1.0.6 (from nupic==1.0.6.dev0) (from versions: 1.0.1)
> ERROR: No matching distribution found for nupic.bindings>=1.0.6 (from nupic==1.0.6.dev0)
