### ISSUE TITLE
python setup.py egg_info" failed with error code 1 

### ISSUE THREAD

**Issue by ddobric** [numenta/nupic#3801]
Getting following error when trying to install:
`pip install nupic --user`

Here is the error:

```
Collecting` unittest2==0.5.1 (from nupic)
  Using cached unittest2-0.5.1.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\AAA\AppData\Local\Temp\pip-build-4ratl3a2\unittest2\setup.py", line 12, in <module>
        from unittest2 import __version__ as VERSION
      File "c:\users\AAA\appdata\local\temp\pip-build-4ratl3a2\unittest2\unittest2\__init__.py", line 40, in <module>
        from unittest2.collector import collector
      File "c:\users\AAA\appdata\local\temp\pip-build-4ratl3a2\unittest2\unittest2\collector.py", line 3, in <module>
        from unittest2.loader import defaultTestLoader
      File "c:\users\AAA\appdata\local\temp\pip-build-4ratl3a2\unittest2\unittest2\loader.py", line 92
        except Exception, e:
                        ^
    SyntaxError: invalid syntax


Command "python setup.py egg_info" failed with error code 1 in C:\Users\AAA\AppData\Local\Temp\pip-build-4ratl3a2\unittest2\
```

**Comment by rhyolight** [comment]
are you using python 3? we do not support it

**Comment by ddobric** [comment]
Yes. v3.3.

Thanks

**Comment by rhyolight** [comment]
:( Sorry, we do not support python 3, but there is a [community fork of NuPIC](https://discourse.numenta.org/t/proposal-to-introduce-pybind-for-move-toward-python-3-compatibility/3110), and they are working on it.
