### ISSUE TITLE
SyntaxError: Invalid Syntax Error While Installing the Library

### ISSUE THREAD

**Issue by sam6889** [numenta/nupic#3885]
I get the following error message when attempting to install nupic library:

 Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-64z_waut/unittest2/setup.py", line 12, in <module>
        from unittest2 import __version__ as VERSION
      File "/tmp/pip-install-64z_waut/unittest2/unittest2/__init__.py", line 40, in <module>
        from unittest2.collector import collector
      File "/tmp/pip-install-64z_waut/unittest2/unittest2/collector.py", line 3, in <module>
        from unittest2.loader import defaultTestLoader
      File "/tmp/pip-install-64z_waut/unittest2/unittest2/loader.py", line 92
        except Exception, e:

**Comment by xhulianoThe1** [comment]
Think this a python version issue, think it only supports python 2.7 
There should be a community fork
