### ISSUE TITLE
Install nupic in windows10 by command: pip install nupic, gaven this error message: 

### ISSUE THREAD

**Issue by fenfeibani** [numenta/nupic#3893]
Collecting pytest-cov==2.5.0
  Using cached pytest_cov-2.5.0-py2.py3-none-any.whl (21 kB)
Collecting prettytable==0.7.2
  Using cached prettytable-0.7.2.tar.bz2 (21 kB)
Collecting pyproj==1.9.3
  Using cached pyproj-1.9.3.tar.gz (2.7 MB)
    ERROR: Command errored out with exit status 1:
     command: 'd:\python27\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\kzy\\appdata\\local\\temp\\pip-install-6eztzc\\pyproj\\setup.py'"'"'; __file__='"'"'c:\\users\\kzy\\appdata\\local\\temp\\pip-install-6eztzc\\pyproj\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'c:\users\kzy\appdata\local\temp\pip-pip-egg-info-nxnfyl'
         cwd: c:\users\kzy\appdata\local\temp\pip-install-6eztzc\pyproj\
    Complete output (17 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\kzy\appdata\local\temp\pip-install-6eztzc\pyproj\setup.py", line 14, in <module>
        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])
      File "d:\python27\lib\distutils\msvc9compiler.py", line 473, in compile
        self.initialize()
      File "d:\python27\lib\distutils\msvc9compiler.py", line 383, in initialize
        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "d:\python27\lib\site-packages\setuptools\msvc.py", line 147, in msvc9_query_vcvarsall
        return EnvironmentInfo(arch, ver).return_env()
      File "d:\python27\lib\site-packages\setuptools\msvc.py", line 1227, in return_env
        [self.VCIncludes,
      File "d:\python27\lib\site-packages\setuptools\msvc.py", line 876, in VCIncludes
        return [os.path.join(self.si.VCInstallDir, 'Include'),
      File "d:\python27\lib\site-packages\setuptools\msvc.py", line 555, in VCInstallDir
        raise distutils.errors.DistutilsPlatformError(msg)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 9.0 is required. Get it from http://aka.ms/vcpython27
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by NomandChan** [comment]
install "VC 9 for python" in this link:
https://web.archive.org/web/20200709160228if_/https://download.microsoft.com/download/7/9/6/796EF2E4-801B-4FC4-AB28-B59FBF6D907B/VCForPython27.msi
it was hard to find because C++ 2008 download was expired long ago.

**Comment by Lxnus** [comment]
You can mark this as answer. Worked fine for me! Thank you. 💯
