### ISSUE TITLE
pip install nupic 

### ISSUE THREAD

**Issue by chaoens** [numenta/nupic#3903]
Using cached pytest-xdist-1.16.0.tar.gz (88 kB)
    ERROR: Command errored out with exit status 1:
     command: 'f:\python27\python2.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\94016\\appdata\\local\\temp\\pip-insta
ll-ebxihk\\pytest-xdist\\setup.py'"'"'; __file__='"'"'c:\\users\\94016\\appdata\\local\\temp\\pip-install-ebxihk\\pytest-xdist\\setup.py'"'"';f=ge
tattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'ex
ec'"'"'))' egg_info --egg-base 'c:\users\94016\appdata\local\temp\pip-pip-egg-info-inyb83'
         cwd: c:\users\94016\appdata\local\temp\pip-install-ebxihk\pytest-xdist\
    Complete output (37 lines):
    running egg_info
    creating c:\users\94016\appdata\local\temp\pip-pip-egg-info-inyb83\pytest_xdist.egg-info
    writing requirements to c:\users\94016\appdata\local\temp\pip-pip-egg-info-inyb83\pytest_xdist.egg-info\requires.txt
    writing c:\users\94016\appdata\local\temp\pip-pip-egg-info-inyb83\pytest_xdist.egg-info\PKG-INFO
    writing top-level names to c:\users\94016\appdata\local\temp\pip-pip-egg-info-inyb83\pytest_xdist.egg-info\top_level.txt
    writing dependency_links to c:\users\94016\appdata\local\temp\pip-pip-egg-info-inyb83\pytest_xdist.egg-info\dependency_links.txt
    writing entry points to c:\users\94016\appdata\local\temp\pip-pip-egg-info-inyb83\pytest_xdist.egg-info\entry_points.txt
    writing manifest file 'c:\users\94016\appdata\local\temp\pip-pip-egg-info-inyb83\pytest_xdist.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\94016\appdata\local\temp\pip-install-ebxihk\pytest-xdist\setup.py", line 37, in <module>
        'Programming Language :: Python :: 3',
      File "f:\python27\lib\site-packages\setuptools\__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "f:\python27\lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "f:\python27\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "f:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "f:\python27\lib\site-packages\setuptools\command\egg_info.py", line 296, in run
        self.find_sources()
      File "f:\python27\lib\site-packages\setuptools\command\egg_info.py", line 303, in find_sources
        mm.run()
      File "f:\python27\lib\site-packages\setuptools\command\egg_info.py", line 534, in run
        self.add_defaults()
      File "f:\python27\lib\site-packages\setuptools\command\egg_info.py", line 573, in add_defaults
        rcfiles = list(walk_revctrl())
      File "f:\python27\lib\site-packages\setuptools\command\sdist.py", line 20, in walk_revctrl
        for item in ep.load()(dirname):
      File "f:\python27\lib\site-packages\setuptools_scm\integration.py", line 36, in find_files
        res = command(path)
      File "f:\python27\lib\site-packages\setuptools_scm\file_finder_git.py", line 77, in git_find_files
        toplevel = _git_toplevel(path)
      File "f:\python27\lib\site-packages\setuptools_scm\file_finder_git.py", line 30, in _git_toplevel
        assert cwd.replace("\\", "/").endswith(out)
    AssertionError
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by chaoens** [comment]
pytest-xdist==1.16.0 need the python3，but nupic only install python2
