### ISSUE TITLE
Subsequent calls to Configuration.get() after a RunTime error succeed

### ISSUE THREAD

**Issue by rhyolight** [numenta/nupic#484]
> This issues was migrated from an internal ticket tracker (MER-189).

Another one encountered during testing.  If you encounter a RuntimeError when calling Configuration.get(), for example if the configuration element has a child element that is not a property, subsequent calls to Configuration.get() will succeed.

For example, configuration file looks like this:

```
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
<configuration>
<foo>bar <baz/></foo>
<property>
  <name>nupic.cluster.database.host</name>
  <value>localhost</value>
  <description>Name of the machine running the MySQL database server</description>
</property>
</configuration>
```

Then:

```
>>> from nupic.support.configuration import Configuration
>>> Configuration.get('nupic.cluster.database.host')
Error while parsing configuration file: /Users/amarshall/nta/current/conf/default/nupic-default.xml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/amarshall/nta/current/lib/python2.6/site-packages/nupic/support/configuration.py", line 67, in get
    Configuration._readStdConfigFiles()
  File "/Users/amarshall/nta/current/lib/python2.6/site-packages/nupic/support/configuration.py", line 310, in _readStdConfigFiles
    Configuration.readConfigFile('nupic-default.xml')
  File "/Users/amarshall/nta/current/lib/python2.6/site-packages/nupic/support/configuration.py", line 163, in readConfigFile
    "an element named '%s': {%s}" % (prop.tag, desc))
RuntimeError: Unexpected only 'property' elements but encountered an element named 'foo': {bar baz:None, }
>>> Configuration.get('nupic.cluster.database.host')
```

**Comment by rhyolight** [comment]
### Please review this issue

This issue needs to be reviewed by the original author or another contributor for applicability to the current codebase. The issue might be obsolete or need updating to match current standards and practices. If the issue is out of date, please close. Otherwise please leave a comment to justify its continuing existence. It may be closed in the future if no further activity is noted.
